<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addAddress_button</name>
   <tag></tag>
   <elementGuidId>81b20b00-6b95-454b-9614-e097f477091e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > input.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Add Address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a8d53d4-f8da-42fc-9f67-600dca42a59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98b2ff65-cf88-49ce-ad38-883d1e2f1c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aa92d532-6518-424b-8293-881027822e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Operator.ContactAddressSave();</value>
      <webElementGuid>2847c3a6-6159-4bed-aa50-ccae736e5fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Address</value>
      <webElementGuid>51d7b2ce-6cee-4784-8d78-20cf133de998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operator-contact-form&quot;)/table[3]/tbody[1]/tr[1]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>a7fc284b-1c88-4db6-a965-3da9f05a9ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Add Address']</value>
      <webElementGuid>379117f5-51d8-4f28-bee8-b0b3be3fc230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[3]/tbody/tr/td/input</value>
      <webElementGuid>22e6836d-46c7-41f3-8050-81f6b1f729f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/input</value>
      <webElementGuid>e36b5ddc-6bb5-4a57-a08c-ce1aa1bc73a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>d603114e-9752-48d4-8370-04a5cde55d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
