<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addressLine2_textBox</name>
   <tag></tag>
   <elementGuidId>dc0265f8-f838-4732-9012-573bc3eba90c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Street2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Street2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02bfaa06-0f31-48ad-a0e5-73c85bf277bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tighter-input</value>
      <webElementGuid>7d426d22-a9e6-4d64-ae23-35e21de9f94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Street2</value>
      <webElementGuid>b251b016-c1e8-4a0d-991f-32a7e5f3a69c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street2</value>
      <webElementGuid>333e00a0-e0ba-4cf8-a51e-f7e9f9ab3d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70736b1b-f501-4830-940c-3343cdcbcdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Street2&quot;)</value>
      <webElementGuid>cb63e782-4000-418b-8241-1f62f9fe4941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Street2']</value>
      <webElementGuid>de6078e9-470d-4151-9913-739e2b71a991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table/tbody/tr[4]/td/input</value>
      <webElementGuid>3b0c3000-8edf-458c-baa3-647725f59a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>deafc79c-6d82-487d-8e4a-f2a029d1ed1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Street2' and @name = 'Street2' and @type = 'text']</value>
      <webElementGuid>6f8e7724-1bb8-4e96-8fe2-49fdb37174e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
