<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>heavy_button</name>
   <tag></tag>
   <elementGuidId>9891d3b7-00d8-469b-946f-bf30e10c1f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BAJ_Aircraft']/div[83]/div/div/div/div[3]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c25ec143-dc25-4b29-8d9b-3ad1bee03a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>1e80234e-7f54-42dc-94d1-1db03b09365e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn aircraft-select-button target-baj-button-aircraft-select</value>
      <webElementGuid>bdf8d005-ee44-4d7b-b731-f7bf63bf5c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aircraft-id</name>
      <type>Main</type>
      <value>1821</value>
      <webElementGuid>df310d93-184f-4c48-b9df-0095134cb34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Select 
                                </value>
      <webElementGuid>0423444f-ec12-45be-8bca-296285aa152a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAJ_Aircraft&quot;)/div[@class=&quot;col-xs-12 baj-results-aircraft clearfix colNoSideMargins&quot;]/div[@class=&quot;col-xs-12 colNoSideMargins&quot;]/div[@class=&quot;media aircraftList&quot;]/div[@class=&quot;aircraftList-top&quot;]/div[@class=&quot;media-body&quot;]/div[@class=&quot;aircraft-results-right&quot;]/div[@class=&quot;bookingDetails&quot;]/a[@class=&quot;btn aircraft-select-button target-baj-button-aircraft-select&quot;]</value>
      <webElementGuid>c8068c0b-367a-4215-913a-f423fc13af61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAJ_Aircraft']/div[83]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>10c19861-e293-446f-a9a3-c9a3c1e028cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[83]</value>
      <webElementGuid>31971818-2eb2-4c86-97e0-15bf5864a262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$75,032'])[1]/following::a[1]</value>
      <webElementGuid>03493520-3328-4937-ac40-e0c7d507f1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY RATING'])[83]/following::a[1]</value>
      <webElementGuid>8b2876ee-eb9d-4f45-a6ab-879266cdc460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer'])[83]/preceding::a[4]</value>
      <webElementGuid>650afcb5-0916-4bd1-ac10-63d6d81f580a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DASSAULT-BREGUET'])[1]/preceding::a[4]</value>
      <webElementGuid>d10f4bc3-e3d1-45b1-af99-fb8a880a2e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[420]</value>
      <webElementGuid>10c8b244-ce8c-4318-bcbb-c5165d94f7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[83]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>7ba4ea0c-3cb8-4813-b256-2906646749ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                    Select 
                                ' or . = '
                                    Select 
                                ')]</value>
      <webElementGuid>d5855a3f-3c90-4e3b-8bf3-19f521fe465b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
