<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>conciergeOrders_tab</name>
   <tag></tag>
   <elementGuidId>c5081c1a-4553-4b99-a14c-d92f5836753f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='WorkItemRow']/div/label)[23]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.black-tight-label.target-flight-plan-work-flow-item-label.target-flight-plan-work-flow-item-label-action-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>87b7c4f8-f041-42f0-8d93-7cfe5d23ce0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-18</value>
      <webElementGuid>fe6e347e-72a1-4368-97fb-8f368c89ac99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580511</value>
      <webElementGuid>bcfa6f87-91bb-4a5b-a3f8-3aae84a51832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-work-flow-id</name>
      <type>Main</type>
      <value>14622317</value>
      <webElementGuid>b47d1ce8-c5e6-4bf4-89ed-19e664f133cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-work-flow-item-id</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e12da512-3a1d-449a-a07c-4caf55f4336d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>z4622317</value>
      <webElementGuid>49a07656-30f4-4288-a915-4fe77af8c42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Concierge Orders</value>
      <webElementGuid>18dddd3a-2a1e-484b-96eb-376a54494b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-4 target-flight-plan-work-flow-main&quot;]/div[@class=&quot;target-flight-plan-work-flow-task-div&quot;]/div[@id=&quot;WorkItemRow&quot;]/div[@class=&quot;col-xs-6 black-tight-label&quot;]/label[@class=&quot;black-tight-label target-flight-plan-work-flow-item-label target-flight-plan-work-flow-item-label-action-18&quot;]</value>
      <webElementGuid>f4b62d0f-ed50-4185-80a6-34bd1193b1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='WorkItemRow']/div/label)[23]</value>
      <webElementGuid>33cb39e7-feec-42cd-9512-3418e6891cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concierge Assigned'])[1]/following::label[1]</value>
      <webElementGuid>d4d9456b-a4a7-4ed3-9078-a16dbe66a33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good To Go Sent'])[1]/following::label[2]</value>
      <webElementGuid>58680b32-ea81-4fa4-b6ce-dd750033e81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concierge Checklist'])[1]/preceding::label[1]</value>
      <webElementGuid>8c2a38b3-5e17-48be-99e6-db4d5891d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Quality'])[1]/preceding::label[2]</value>
      <webElementGuid>c92eb6d4-f07b-484a-92a6-d8a4083fd330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Concierge Orders']/parent::*</value>
      <webElementGuid>b62005bc-aea6-4aaf-a6c0-267388c58a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div/label</value>
      <webElementGuid>3937226d-466a-4349-9ecd-499ecf31ef17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Concierge Orders' or . = 'Concierge Orders')]</value>
      <webElementGuid>686dd865-7533-4592-b23b-23da998aaee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
