<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>privacyPolicy_checkBox</name>
   <tag></tag>
   <elementGuidId>cf912961-1b2a-4732-96ac-5012be765877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanOriginal_UserAgreement_PrivacyPolicy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanOriginal_UserAgreement_PrivacyPolicy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81f75a7b-0563-4225-a137-681ae45fe7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-absolute</value>
      <webElementGuid>802942c9-f1a7-453f-85c8-e6aefd8b89ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f9e9de95-a85d-4d91-afda-1aba37d6aa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Must Agree to Privacy Policy</value>
      <webElementGuid>58052dc7-4eab-4664-8e0f-556df6d234e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>0234d52c-0b0d-41e6-a274-6ee2f1d4afd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>9004b5c2-6dae-4c0e-b2c7-25c729a58344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Privacy Policy field is required.</value>
      <webElementGuid>b1fe5b51-334a-4646-9dd2-0fedc8eb246c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanOriginal_UserAgreement_PrivacyPolicy</value>
      <webElementGuid>4b05fe58-6951-4da2-a85c-bc3a34b52676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanOriginal.UserAgreement_PrivacyPolicy</value>
      <webElementGuid>17b5b218-0aa9-4a55-b404-a923dd12721f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>973f542c-f283-40cf-b0ef-94f711d57256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd808e37-44e7-4d01-9db0-e94352b1b9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanOriginal_UserAgreement_PrivacyPolicy&quot;)</value>
      <webElementGuid>953a6687-bd2c-466a-a7ce-a68a646de2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanOriginal_UserAgreement_PrivacyPolicy']</value>
      <webElementGuid>fab366bb-b3d1-4a37-9998-0e49c04c18f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ItineraryPaymentForm']/div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>4344f43e-ae75-43f9-a5d8-6958d01eb805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>08d5aaf8-10b6-429d-8978-68e9e9a342e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanOriginal_UserAgreement_PrivacyPolicy' and @name = 'FlightPlanOriginal.UserAgreement_PrivacyPolicy' and @type = 'checkbox']</value>
      <webElementGuid>16c8e438-168d-464f-b3f1-b31e714c2e76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
