<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>travelDocuments_checkBox</name>
   <tag></tag>
   <elementGuidId>2d68a996-5ffe-40f1-887b-003bbc38f598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanOriginal_UserAgreement_TravelDocuments']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanOriginal_UserAgreement_TravelDocuments</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7858b69-30dd-48f4-8c4d-bdff6ec033ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-absolute</value>
      <webElementGuid>bb21b10c-d4f9-4251-a1c4-c0da9889d5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a47af30-564c-4e7a-beb0-48f01b7fed9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Must Agree to Travel Documents</value>
      <webElementGuid>c2d99260-21b6-4e4b-97ac-b4c840a1ca39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>c460f6e3-f09f-4e90-9c3a-80f3e61f9405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>5a7e4046-9fbc-4bb2-8b0c-3c9bee130238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Travel Documents field is required.</value>
      <webElementGuid>1f0b73e9-2f0f-47fe-91a4-b2dfbc2b033e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanOriginal_UserAgreement_TravelDocuments</value>
      <webElementGuid>c85370ed-056d-46ea-9a96-81bcf465606f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanOriginal.UserAgreement_TravelDocuments</value>
      <webElementGuid>b4fb0173-88ec-4ba5-9123-13d25d250c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3fc06277-1342-4609-a847-bbd7d631859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5a21fc6-b5bb-493e-8fff-2141b7877adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanOriginal_UserAgreement_TravelDocuments&quot;)</value>
      <webElementGuid>0d2d8449-7b90-4fdb-8082-ee9acfc4d9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanOriginal_UserAgreement_TravelDocuments']</value>
      <webElementGuid>220cb5cd-a2c7-43a1-9cce-02e0ce40b692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ItineraryPaymentForm']/div[3]/div/div[3]/div/div[4]/input</value>
      <webElementGuid>c95e8605-8feb-4215-94da-d534a7ab5f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/input</value>
      <webElementGuid>22f64d8c-b549-4bc6-a0be-fc96c02d38d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanOriginal_UserAgreement_TravelDocuments' and @name = 'FlightPlanOriginal.UserAgreement_TravelDocuments' and @type = 'checkbox']</value>
      <webElementGuid>cbd122c8-445d-4587-98d0-f3fbf1bc5cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
