<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aircraft_object</name>
   <tag></tag>
   <elementGuidId>2e97d06c-c22f-4043-b272-1e71425a47ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Aircraft']/div/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ams-table</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d02f402a-9b5b-43b7-8813-554cc7c1516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ams-table</value>
      <webElementGuid>8c6237e6-838d-410d-ae73-15677701d7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Operator/OperatorAircraftDetail/1037/9404</value>
      <webElementGuid>16297c39-ea39-40ca-b2cc-e0ef0b5c7242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>N12309</value>
      <webElementGuid>b9e95f5d-8891-4b87-9612-b88888c12b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Aircraft&quot;)/div[@class=&quot;row&quot;]/table[@class=&quot;table ams-table&quot;]/tbody[1]/tr[@class=&quot;bgcolor=&quot;]/td[@class=&quot;of-red&quot;]/a[@class=&quot;ams-table&quot;]</value>
      <webElementGuid>87112a73-da87-4d11-b257-d182d92add8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Aircraft']/div/table/tbody/tr/td/a</value>
      <webElementGuid>727d271d-0a96-492f-9bcc-c061f87c8266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'N12309')]</value>
      <webElementGuid>313c5500-c8f8-4340-9e67-4b5ff9dc55bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJ Rating'])[1]/following::a[1]</value>
      <webElementGuid>4e68bf1e-cc80-45d4-9aca-aa08ec399f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[3]/following::a[1]</value>
      <webElementGuid>4d90d384-7ea2-4683-8e35-f03db814fef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K-122'])[1]/preceding::a[1]</value>
      <webElementGuid>18c7e3c4-d5b6-456e-8323-11a4ca35b699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bombardier'])[1]/preceding::a[1]</value>
      <webElementGuid>ba1d51a2-bf60-4e0f-b6a5-26ce7008378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='N12309']/parent::*</value>
      <webElementGuid>78579704-deee-409a-bff3-f1db56cd8e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Operator/OperatorAircraftDetail/1037/9404')]</value>
      <webElementGuid>adad9e0f-a9a9-4301-8818-74a734f99685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td/a</value>
      <webElementGuid>c7a00574-7e11-4aaa-aac0-67b73fcf3688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Operator/OperatorAircraftDetail/1037/9404' and (text() = 'N12309' or . = 'N12309')]</value>
      <webElementGuid>ec7cfc64-b49f-4ca6-8759-6d608874159f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
