<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>currentAirportIdent_textBox</name>
   <tag></tag>
   <elementGuidId>e2450efb-f708-4c70-ace5-4bfa98e17554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CurrentAirportIdent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CurrentAirportIdent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89326955-f11e-4fa6-bc58-9b3e1dd177bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-label black-tight-input target-airport-entry ui-autocomplete-input</value>
      <webElementGuid>07ba6bc9-a0a4-4d20-84e8-a201c3de6b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92e20de7-3079-49d5-bd45-92912e8e8cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The Current Airport must be at least 2 characters long.</value>
      <webElementGuid>91c00b3c-0cb9-47a1-910e-2446c79b4fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>008857c3-8f1f-42a6-8572-f2d7ea514be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ac7d949e-1893-4ddc-a6bf-fb5eb095adb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CurrentAirportIdent</value>
      <webElementGuid>ab28e251-f2c0-46e0-9f5d-329211511b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>be46046e-c7b3-4370-85bd-c086949facff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CurrentAirportIdent</value>
      <webElementGuid>0746ff9c-6e4e-4705-9570-f9d11ea86cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83fd714c-3fb7-4a8b-9aaa-2be78e33ac7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KAPA</value>
      <webElementGuid>1bf63590-c824-4cde-83e8-20a952f65fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>44e35a34-bedb-470e-b03a-395cb37475bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CurrentAirportIdent&quot;)</value>
      <webElementGuid>45799506-5f72-4c88-a943-1bc7cd42a58a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CurrentAirportIdent']</value>
      <webElementGuid>d599c9be-b261-4b7e-87c5-f3fed3945d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AircraftDetailForm']/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>db854d6a-3a00-432c-be4a-b6603d2afb2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/input</value>
      <webElementGuid>f116dab2-1d40-44ca-9314-f04c60271056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CurrentAirportIdent' and @name = 'CurrentAirportIdent' and @type = 'text']</value>
      <webElementGuid>b61c008e-09e6-446e-b86e-4c4e786ffd8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
