<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>exterior_textBox</name>
   <tag></tag>
   <elementGuidId>5e60d7f9-0e68-4802-9ecb-2fd6dbe29a58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YearRefurbishedExterior']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#YearRefurbishedExterior</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15346203-1bd8-4299-b9d3-7ca41ee44935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-label black-tight-input</value>
      <webElementGuid>4c1ccb13-1108-49fa-b954-5358b13c1a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c760f293-2400-4936-b94e-655801473a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Please enter a valid Exterior Refurbished Year</value>
      <webElementGuid>d7e1d2e9-31f6-43b8-8c3f-f76d25ac985d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>(19|20)\d{2}$</value>
      <webElementGuid>9a914dda-dccb-4072-8598-85772f586678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YearRefurbishedExterior</value>
      <webElementGuid>b6736040-abed-4725-b5e8-01406cfc23ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>YearRefurbishedExterior</value>
      <webElementGuid>adc8af77-38c9-4baa-ba88-507a2505865f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>038236df-c7c0-4dd2-9112-355e6c51003f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2018</value>
      <webElementGuid>5dd43e38-f72c-44ee-8171-589141dc6e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YearRefurbishedExterior&quot;)</value>
      <webElementGuid>dc180237-d45d-4327-abe1-914045333cde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='YearRefurbishedExterior']</value>
      <webElementGuid>0bce1d23-be45-4cb5-b549-e2a564a22287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AircraftDetailForm']/div/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>8984d99f-dac8-4766-a5e9-2b89b3bfd618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>2db2650d-3855-4c53-a00a-89eafb10a03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'YearRefurbishedExterior' and @name = 'YearRefurbishedExterior' and @type = 'text']</value>
      <webElementGuid>2377704b-6e91-432c-ba25-f64e9cb762af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
