<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wiFi_checkBox</name>
   <tag></tag>
   <elementGuidId>a0310df9-1fb7-43f9-babb-c7295585f63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='HasWiFi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#HasWiFi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e58e6c4e-dbce-450b-8fac-84507b420ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label black-tight-label</value>
      <webElementGuid>39f35414-55cd-487a-bc8e-f21869d6381d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13c37d8e-22b4-4b43-8ee1-33d46b587ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Wi-Fi Available field is required.</value>
      <webElementGuid>aca7060f-c99c-43a2-aabc-c601de788590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HasWiFi</value>
      <webElementGuid>9f6d3444-40c9-4057-b432-3905a56d5c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HasWiFi</value>
      <webElementGuid>294d9102-a288-4135-a6e5-396b349013e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e1ccdb4e-21e6-4409-bd9e-1198a056f797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d97a697f-38ae-45a7-b9b6-3ccef93fe8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HasWiFi&quot;)</value>
      <webElementGuid>b08bd8e9-46ab-4eeb-a349-3ef5ce5509ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='HasWiFi']</value>
      <webElementGuid>99f80fbf-3ecc-4be4-a637-d3462ab7ac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AircraftDetailForm']/div/div[2]/div/div/div/input</value>
      <webElementGuid>269fe7ec-c32f-4e95-9ffd-52c4ddd4dcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>01f55d87-0e16-45f8-a222-d496d8ffdaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'HasWiFi' and @name = 'HasWiFi' and @type = 'checkbox']</value>
      <webElementGuid>6c6e25bc-683e-4b28-80a0-24722a5fd59b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
