<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>initialDepartureDateTime_field</name>
   <tag></tag>
   <elementGuidId>53c37dc0-0e22-4d5f-a44a-64529489fe88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SelectedDepartureFromDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedDepartureFromDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ee43238-a75e-44fb-bbdb-046b80ddbc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3df1c9c2-4eb8-45b2-a980-16e94cd579eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectedDepartureFromDate</value>
      <webElementGuid>255da171-b26e-4dbc-8d7f-7fcea78d1ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box target-one-loop-selected-departure-datetime date-time-picker</value>
      <webElementGuid>bc96abd7-667e-4c0c-a6bc-0f3ca73da7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7effcecd-8775-434e-aa36-56252667d920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date/Time</value>
      <webElementGuid>bd1f3783-c635-4f71-83e0-01c2e023d395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedDepartureFromDate&quot;)</value>
      <webElementGuid>26ca0916-c0b3-44e0-ba5e-ec7375c4d4fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SelectedDepartureFromDate']</value>
      <webElementGuid>ea559de8-5380-4694-a9c5-c267eb847316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoopTool']/div[2]/div/div/div/div/fieldset/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>9fd769de-ad3b-4f56-80cd-257b9244c460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>e12cdebf-8f13-40cb-aea0-4dcc754aafe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SelectedDepartureFromDate' and @placeholder = 'Select Date/Time']</value>
      <webElementGuid>fcbbb34c-2ff3-4a1f-aa46-16f9044e9295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
