<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>birdDate_dropDown</name>
   <tag></tag>
   <elementGuidId>2b385a56-0720-435a-a0c0-8dd2606044eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_0__BirthDate_Month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_0__BirthDate_Month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e7b0466-1b53-4ecf-8abc-15a612512099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control float-left target-birthdate-el target-pax-birthmonth</value>
      <webElementGuid>94ad20dd-d5fa-41a5-88cd-2a3356f4598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1646f07c-bc2f-4590-b3b9-24c88d2e59a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The BirthDate_Month field is required.</value>
      <webElementGuid>1c928843-3c22-4fba-82c9-05f527de5647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_0__BirthDate_Month</value>
      <webElementGuid>27f5dfd9-63ab-4580-9c0f-66b884b2573b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[0].BirthDate_Month</value>
      <webElementGuid>29c3474f-4eb7-4705-a796-5aa967789150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            </value>
      <webElementGuid>dfbf1be2-0c47-450e-8433-372be0f4a2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_0__BirthDate_Month&quot;)</value>
      <webElementGuid>6017f0e3-59e4-49ba-999c-1e677abae921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_0__BirthDate_Month']</value>
      <webElementGuid>3f3d1c6e-276d-4a58-8e73-0117282b556b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-1']/div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>b7a0b2f5-fa04-4056-a1db-1c80e18de646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[1]/following::select[1]</value>
      <webElementGuid>a7441d57-b99f-4a2d-bab4-32da2f6f294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[4]/preceding::select[2]</value>
      <webElementGuid>fe66056b-e6e3-49dc-be39-cf02615ad328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>89692ccd-3ad4-4971-b3e4-6d3180173793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_0__BirthDate_Month' and @name = 'Legs[0].Passengers[0].BirthDate_Month' and (text() = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ' or . = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ')]</value>
      <webElementGuid>e670eb68-0c1a-4ba5-9f3f-e3edb58b57be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
