<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gender _dropDown</name>
   <tag></tag>
   <elementGuidId>330aad05-dc58-4a20-99c4-ba7d8038c3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_0__Gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_0__Gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>82741ee6-442c-41b9-b2db-d9636b2e47a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-gender</value>
      <webElementGuid>02d6ba79-6125-42a3-b9e5-0bfa4b9a853f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>309c5546-44ea-4e60-85ac-0693cb8f8101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Gender field is required.</value>
      <webElementGuid>7aab1c11-a325-47eb-8559-a22defdc1b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_0__Gender</value>
      <webElementGuid>1a1f7d91-02fd-4e30-992b-c2a6ba76537b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[0].Gender</value>
      <webElementGuid>ada1b9ed-1ec1-4133-b5c6-ba2baa64e06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Gender
                                    M
                                    F
                        </value>
      <webElementGuid>40fff68b-1b9e-4b17-9a2c-83c31be86ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_0__Gender&quot;)</value>
      <webElementGuid>16ed75fa-15ce-41df-963e-daef52970ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_0__Gender']</value>
      <webElementGuid>08404143-6a99-4776-99bd-2ed6e85fc1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-1']/div[3]/div[2]/div/div[2]/div[4]/div/select</value>
      <webElementGuid>6b8a3524-f3da-4a60-b804-64fbefc88eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::select[1]</value>
      <webElementGuid>486bf002-5d5e-47a4-95d3-df8ae56514ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::select[1]</value>
      <webElementGuid>ff85be51-1b17-4008-9025-c58533235699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>1218bdee-6975-4860-bbbd-4ab3a0bc27c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_0__Gender' and @name = 'Legs[0].Passengers[0].Gender' and (text() = '
                            Gender
                                    M
                                    F
                        ' or . = '
                            Gender
                                    M
                                    F
                        ')]</value>
      <webElementGuid>53819f23-d829-4bac-9ebc-8a5d615edf2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
