<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addNewQuote_button</name>
   <tag></tag>
   <elementGuidId>81d2bae2-8d8b-48f5-83ca-3c4bdb3287be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Add New Quote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.target-add-operator-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29e50718-5b21-4570-9da9-e1caff063f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b873f940-b89f-4b2a-a1aa-14fada923229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary target-add-operator-quote</value>
      <webElementGuid>3632aee5-20ad-4123-9fbd-98508a3b413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add New Quote</value>
      <webElementGuid>a66b835d-5d95-4742-bde6-67d679bf3866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OperatorQuotes&quot;)/div[@class=&quot;col-xs-12 float-right text-right&quot;]/input[@class=&quot;btn btn-primary target-add-operator-quote&quot;]</value>
      <webElementGuid>3cd82d62-42c7-4227-8f04-3fc289f4c541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Add New Quote']</value>
      <webElementGuid>f3328568-0ae3-45b3-8e58-feb7f46c15a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OperatorQuotes']/div/input[2]</value>
      <webElementGuid>1d3d8b92-212a-4343-972e-b5de49d3fbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input[2]</value>
      <webElementGuid>c7848485-a5a5-4813-93ae-50233f398fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>974ba169-6511-4b3c-a316-0f03e6626b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
