<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amount_textBox</name>
   <tag></tag>
   <elementGuidId>6f56eeb9-4966-4e9a-87db-1cc921dc4d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Bill_NewBillItem_Rate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Bill_NewBillItem_Rate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ffdf0a7-e66f-42e7-892c-26aa6e5a857b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>681e7690-3872-4ac5-9021-a06e8cc38d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8961b2eb-4614-4b4d-a84b-cf8958541374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6a136805-e2dd-4b50-946b-a178cc40d90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>7055809a-d8e6-4a37-8ece-4aa77518d825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2653c99f-0617-4fa3-a1c3-8fff168672c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Rate must be a number.</value>
      <webElementGuid>892e7806-dcfe-45b5-8ad9-f9e4165f37ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Rate field is required.</value>
      <webElementGuid>ff0921e9-0a30-4a36-b0d6-3ded6535fe4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Bill_NewBillItem_Rate</value>
      <webElementGuid>82516ea2-8673-4a15-aae0-08bdfd53c0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Bill.NewBillItem.Rate</value>
      <webElementGuid>defa4922-03f7-4b9d-a509-e21aa108f4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Bill_NewBillItem_Rate&quot;)</value>
      <webElementGuid>c8a21203-a2d8-4b46-87da-9e2b78d6ca45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Bill_NewBillItem_Rate']</value>
      <webElementGuid>9419ee7f-ef35-4143-9ad1-e99408ceb9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newbillitem']/div/div[3]/input</value>
      <webElementGuid>108003ab-b203-48d0-9a45-6dadfb58a713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/input</value>
      <webElementGuid>125507d6-34d3-4bfd-b2e3-482f37e3eae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Amount' and @type = 'number' and @id = 'FlightPlan_Bill_NewBillItem_Rate' and @name = 'FlightPlan.Bill.NewBillItem.Rate']</value>
      <webElementGuid>045c368e-417f-4420-8e50-053d85102425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
