<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_textArea</name>
   <tag></tag>
   <elementGuidId>87cdb012-482c-48ee-a92f-ad8eab0ef5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_2__LuggageDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__LuggageDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>981132d7-64d7-460a-9ab4-44635b5c6ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-luggage-description</value>
      <webElementGuid>f06a8a99-6b55-4515-bc8f-08d76d285222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e1590aea-4d0a-47c1-8200-a931901c4cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__LuggageDescription</value>
      <webElementGuid>b00b9fd8-9cf4-4f07-895c-8d40e68846c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].LuggageDescription</value>
      <webElementGuid>a82846a5-9216-4083-9f9c-7c0508efbec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c86adee8-d2fe-4f4f-a8d6-8474dace7949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__LuggageDescription&quot;)</value>
      <webElementGuid>63930b41-ba6e-41cf-bd60-e617494703e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_2__LuggageDescription']</value>
      <webElementGuid>cd9ae8e1-aea9-413a-94cc-4441da6af8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div/div[5]/textarea)[7]</value>
      <webElementGuid>d670dfd4-46fd-483f-befc-990072b404bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div/div/div/div/div[5]/textarea</value>
      <webElementGuid>6998c3c6-b47a-4a73-91ad-82d95fcafd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_2__LuggageDescription' and @name = 'Legs[2].LuggageDescription']</value>
      <webElementGuid>496a39b4-e013-483e-b5d1-a33a7885b5d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
