<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>blueCheeseDressing_checkBox</name>
   <tag></tag>
   <elementGuidId>f5ac3b2a-c896-49ae-8701-ee8316e267b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CobbSalad-options']/li[6]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>804ac46a-b6cf-47da-93e3-406db043509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CobbSaladBlue Cheese Dressing</value>
      <webElementGuid>d5aa9726-c1f4-4de3-b585-9dab835f6b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blue Cheese Dressing</value>
      <webElementGuid>3bd825f0-d419-4783-8e72-60f4a4f26b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CobbSalad-options&quot;)/li[6]/label[1]</value>
      <webElementGuid>dec59447-1fd3-4997-8328-bddb12760ece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CobbSalad-options']/li[6]/label</value>
      <webElementGuid>6be6777c-59fd-4219-afd7-ab2e34e962c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caesar Dressing'])[1]/following::label[1]</value>
      <webElementGuid>ec3dd766-b3ca-4c09-a084-4be63c2eafa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Dressing'])[1]/following::label[2]</value>
      <webElementGuid>54fd18c3-db9f-4709-9028-3056480fdcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinaigrette Dressing'])[1]/preceding::label[1]</value>
      <webElementGuid>695f956c-c2ec-43f8-94da-cf3d39696b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[2]/preceding::label[2]</value>
      <webElementGuid>3f3d4b16-5908-4ba7-8bd8-102f50067b53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blue Cheese Dressing']/parent::*</value>
      <webElementGuid>5a27878f-75fd-434e-a915-f7282a0da968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/label</value>
      <webElementGuid>8705cb6c-6c8b-4e68-93a6-aa79afba7085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Blue Cheese Dressing' or . = 'Blue Cheese Dressing')]</value>
      <webElementGuid>02609a19-0772-448f-b3b0-750a427a7423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
