<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>caesarDressing_checkBox</name>
   <tag></tag>
   <elementGuidId>9ae89035-91e5-4ab8-8563-8128a2460140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CobbSalad-options']/li[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2258843f-3cbe-41de-933f-208882fa816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CobbSaladCaesar Dressing</value>
      <webElementGuid>571d5cdc-3f48-4134-9ab6-dae049d3b132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Caesar Dressing</value>
      <webElementGuid>5ec3c579-7bcb-4280-a9d4-dd20f9c41ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CobbSalad-options&quot;)/li[5]/label[1]</value>
      <webElementGuid>b9154a44-d12d-43a3-9eea-a665d8a99eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CobbSalad-options']/li[5]/label</value>
      <webElementGuid>58c926d6-3bdb-4cf1-92f8-2ff7525fddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Dressing'])[1]/following::label[1]</value>
      <webElementGuid>74af3dd3-a3d0-4161-9bb6-eded4a9821d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turkey Breast'])[1]/following::label[2]</value>
      <webElementGuid>69e2453a-c8f3-4916-acda-13ce3b933b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Cheese Dressing'])[1]/preceding::label[1]</value>
      <webElementGuid>7b5f9d12-4afe-4f4c-bcd2-8f40f8e30988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinaigrette Dressing'])[1]/preceding::label[2]</value>
      <webElementGuid>8582c499-8264-41b0-862e-02e4d83f05f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Caesar Dressing']/parent::*</value>
      <webElementGuid>e0601fda-87c2-4dc0-881c-2b5f2ef27d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/label</value>
      <webElementGuid>511607d5-447f-484f-bb5d-56498fdcbc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Caesar Dressing' or . = 'Caesar Dressing')]</value>
      <webElementGuid>80de84dd-3c44-4680-b8cd-9c24e8d38514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
