<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shreddedChicken_checkBox</name>
   <tag></tag>
   <elementGuidId>f4d2c16d-85b4-4f69-bf94-81d42b3c865d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CobbSalad-options']/li[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>171561f9-e5bf-4984-a055-a9452cceb211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CobbSaladShredded Chicken</value>
      <webElementGuid>233ffd99-9d88-488e-8759-9278c1b4f4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shredded Chicken</value>
      <webElementGuid>c87ea288-27f6-42e5-a16a-e8d64080b724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CobbSalad-options&quot;)/li[2]/label[1]</value>
      <webElementGuid>d3267fdd-caf9-442c-af34-14507b8e3322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CobbSalad-options']/li[2]/label</value>
      <webElementGuid>a6967a04-7053-4868-9362-c633d36b4cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[14]/following::label[1]</value>
      <webElementGuid>820f15ef-e452-4303-b7dc-9a903cf74095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[7]/following::label[1]</value>
      <webElementGuid>a5a6f4fe-a710-4721-bf90-2a1a691a12ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turkey Breast'])[1]/preceding::label[1]</value>
      <webElementGuid>0c6874b3-5be8-4070-92a5-3f08bbc878af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Dressing'])[1]/preceding::label[2]</value>
      <webElementGuid>97555323-c70d-4f50-a228-8cb0350fbbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shredded Chicken']/parent::*</value>
      <webElementGuid>1ef6d538-f659-4c8d-9867-064cbebb1270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/h4[2]/ul/li[2]/label</value>
      <webElementGuid>d8b7fc6a-0dc5-41ed-8653-481c57d33f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Shredded Chicken' or . = 'Shredded Chicken')]</value>
      <webElementGuid>e6bcba68-d148-46b4-9da5-2456b7e4b4d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
