<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>member Information_textBox</name>
   <tag></tag>
   <elementGuidId>b2499688-ebe0-4cf3-9364-5d3df157ed0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_DestinationGroundTransportationMembershipInfo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_DestinationGroundTransportationMembershipInfo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>beff952f-8a76-44b7-a061-bc18773e47a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>701d30f5-1e9b-42d8-8893-801c91884700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3b8c751e-156d-48fe-8320-8ad23fb6350c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93cade58-2ee5-4f14-a4c0-88a0cf0a86bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_DestinationGroundTransportationMembershipInfo</value>
      <webElementGuid>1e9f8e14-eb11-46e0-a90c-b4a3d7949860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.DestinationGroundTransportationMembershipInfo</value>
      <webElementGuid>84d2669e-7550-422e-8e78-36ae5a3b359b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_DestinationGroundTransportationMembershipInfo&quot;)</value>
      <webElementGuid>5dca8267-57da-4f93-aaa7-64da929d20b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_0__ActiveConciergeOrder_DestinationGroundTransportationMembershipInfo']</value>
      <webElementGuid>57669f3e-dfab-486c-862f-baf8c9a37179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-dropoffform']/div[2]/input</value>
      <webElementGuid>b2f16388-7bb2-47c7-9e25-bca974074d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/form/div[2]/div/div/div[3]/div/div[2]/input</value>
      <webElementGuid>86e0fca3-a568-42b2-9346-0dcc9ad00a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_0__ActiveConciergeOrder_DestinationGroundTransportationMembershipInfo' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.DestinationGroundTransportationMembershipInfo']</value>
      <webElementGuid>1b620ca1-f1f0-4dc4-a112-bb0a1511a15f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
