<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cancelSavingPassengerbutton</name>
   <tag></tag>
   <elementGuidId>e5a56b41-e6c2-4810-b61c-f2b42293b287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Cancel'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propagatepassengermodal-leg-1-passenger-2 > div.modal-dialog > div.modal-content > div.modal-body > div.row > div.col-xs-4 > #Cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbd4b5fa-84d8-4de0-adfc-bd0efbed1c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn-small</value>
      <webElementGuid>3460e070-1ffe-4b60-9bf5-34930de9058a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9902953-fd6b-44ab-ab2a-921f7a28592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>18b52ff4-7f21-47d5-8548-6e6d1ebe9751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>1ca131da-4d84-4847-a5d3-60d8757891bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propagatepassengermodal-leg-1-passenger-2&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/input[@id=&quot;Cancel&quot;]</value>
      <webElementGuid>d0e7feca-0a50-4a93-aea7-966f6cf28757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Cancel'])[2]</value>
      <webElementGuid>eb83d5a9-f2c5-490a-877c-dd0bc60ed42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propagatepassengermodal-leg-1-passenger-2']/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>062fdabe-4d7a-4db8-99b0-cbb249aadda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>885874b1-031e-4056-9257-564cf411209b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Cancel']</value>
      <webElementGuid>a7210a64-a796-4755-a764-f1aecae1ebeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
