<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departTo_field</name>
   <tag></tag>
   <elementGuidId>bb92ae98-5a9f-48c1-b94e-f071aa199479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DepartureToDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DepartureToDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a12f3e57-d2df-4149-814f-03b814482717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ea12656-fdf8-481a-ad7b-8ff0ecd41946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box input-date target-one-loop-to-date date-picker</value>
      <webElementGuid>005db35e-93e5-4c74-9d60-df413d4abc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DepartureToDate</value>
      <webElementGuid>4bd78431-ca3c-4448-a57b-6e47f3efac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/17/2023</value>
      <webElementGuid>565c99d0-90aa-4ecb-ad5f-bf091ec3ef42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DepartureToDate&quot;)</value>
      <webElementGuid>41276668-1cea-4613-86ac-d6f0f5574818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DepartureToDate']</value>
      <webElementGuid>11f6c816-d6f0-4d65-ac10-78af8e0e860c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LoopTool']/div[2]/div/div/div/div/fieldset[2]/div/div/div[2]/input</value>
      <webElementGuid>c8e9fad2-b7d9-4183-a4da-b14b693b4df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div[2]/input</value>
      <webElementGuid>04ff3627-d010-4a8e-93f3-295fd64ddaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DepartureToDate']</value>
      <webElementGuid>93a8be48-2544-4be7-a3b3-2cfa030cac8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
