<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leadPassenger_dropDown</name>
   <tag></tag>
   <elementGuidId>2dd5d7a7-6447-4a12-9ebb-54c2ed5ca1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='LeadPassengerId'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-3-leg-909636 > #new-executive-quote-noorder > #dropoff-quote-0 > div.panel-body > div.row > div.col-xs-7 > div.row > div.col-xs-7 > #LeadPassengerId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>734f3816-1779-43b4-955f-86b710a02a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec068ff3-91c8-4713-bc16-6b90c7456b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LeadPassengerId</value>
      <webElementGuid>96ed0d67-dbf0-4863-866b-b8fb491bebe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeadPassengerId</value>
      <webElementGuid>da2d50a2-e282-447e-9c56-471eef05ec3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon, Chris
</value>
      <webElementGuid>eaf7d314-cba2-438b-91de-0fae805db783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-2&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-2&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909636&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909636&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909636&quot;]/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/select[@id=&quot;LeadPassengerId&quot;]</value>
      <webElementGuid>439fe576-64f9-4acb-b097-6762c8e79659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='LeadPassengerId'])[5]</value>
      <webElementGuid>22047d23-e6f9-45c6-acbd-1b8bc67146f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dropoff-quote-0']/div/div/div[3]/div/div[2]/select)[3]</value>
      <webElementGuid>a3108594-ce74-461b-af6b-dd67e1c9f24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Passenger'])[5]/following::select[1]</value>
      <webElementGuid>5bdb5be4-e11d-461c-8ebd-9b4ec7bc9104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Of Passengers'])[5]/following::select[1]</value>
      <webElementGuid>13b476bf-7c30-4e89-b885-13de064b2f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Type Quantities'])[5]/preceding::select[1]</value>
      <webElementGuid>e02082ad-9a81-4ee8-b707-e79c8ca7444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUV:'])[5]/preceding::select[1]</value>
      <webElementGuid>4d5965a6-c324-4a28-8430-44f19529ccaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[2]/select</value>
      <webElementGuid>b0f550a6-9178-476f-988f-c94527ea7dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LeadPassengerId' and @name = 'LeadPassengerId' and (text() = 'Katalon, Chris
' or . = 'Katalon, Chris
')]</value>
      <webElementGuid>2191b83d-adfe-4792-a4dc-30f8a3852129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
