<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addFStop_icon</name>
   <tag></tag>
   <elementGuidId>6a9a4813-8084-43dc-81bb-89a87a41ec13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='target-leg_909768-fuel-stops-info']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-leg_909768-fuel-stops-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a2c0901e-dba2-4af8-a229-15fb74d7617d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle target-expand-leg-fuel-stops cursor</value>
      <webElementGuid>257740bb-d908-47ae-bcd0-3c7130300e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>909768</value>
      <webElementGuid>39ebfb71-1fce-4d12-bdf7-c0eb4df81ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-leg_909768-fuel-stops-info</value>
      <webElementGuid>cc0da6c7-de97-41b6-b1d1-e76d7f2c7cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-leg_909768-fuel-stops-info&quot;)</value>
      <webElementGuid>8f11ef0d-fb48-44f8-98ee-3f302fedb002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='target-leg_909768-fuel-stops-info']</value>
      <webElementGuid>61b1400c-fc18-4847-a666-a3374f24c8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909768']/div[5]/span/i</value>
      <webElementGuid>d4947240-229a-4990-ba3a-d79ef9a0f16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/span/i</value>
      <webElementGuid>69a131bd-308d-4d17-a8f7-db1ff9eebfa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'target-leg_909768-fuel-stops-info']</value>
      <webElementGuid>ed8e2e6e-a4b8-4fd8-ab05-170bde6f9290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
