<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>from_textBox</name>
   <tag></tag>
   <elementGuidId>cc337ee9-4a1c-471c-b548-a0adfbf3320a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_2__AirportOriginIdent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_2__AirportOriginIdent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57b166de-ff92-4864-899c-3caf9b243feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input form-control ui-autocomplete-input</value>
      <webElementGuid>673c3523-fd9a-4147-897f-f9618a00d25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_2__AirportOriginIdent</value>
      <webElementGuid>58a1c2af-8c71-4772-9573-3c76fdb3d352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[2].AirportOriginIdent</value>
      <webElementGuid>68ce07f3-48a2-4252-ac3f-4cbb6d23d03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d77369c-070d-4fe0-babc-b8378d9dfb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KDEN</value>
      <webElementGuid>249b118e-7414-4a84-9583-a240d005c0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6104c2c1-de74-4196-85e2-ade12c43d33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_2__AirportOriginIdent&quot;)</value>
      <webElementGuid>0033f570-5099-4874-a933-fc59b071609b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_2__AirportOriginIdent']</value>
      <webElementGuid>2a09a90d-6eef-45bc-bbef-eadf33452ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909768']/div[3]/input</value>
      <webElementGuid>4f416c86-66d8-456d-897f-547b23c37d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div[3]/div[3]/input</value>
      <webElementGuid>d8280fb7-00fd-4cad-a1ce-7075798ec4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_2__AirportOriginIdent' and @name = 'Legs[2].AirportOriginIdent' and @type = 'text']</value>
      <webElementGuid>efc45c9e-cb9c-478c-9b00-75bd0b983064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
