<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>airport_textBox</name>
   <tag></tag>
   <elementGuidId>19896f3f-468e-4084-a6d8-30e20e507901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operator_HomeBaseAirportIdent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Operator_HomeBaseAirportIdent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1be7206a-3e9c-4361-b862-c09bf89a29db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input target-airport-entry ui-autocomplete-input</value>
      <webElementGuid>16523e65-c198-48a5-ad75-4bf132fe47b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c345e26-5c15-4cf9-a2b3-6d9a4865a705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc1a2169-f8c4-4e74-a425-13c9870e5e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The Airport must be at least 2 characters long.</value>
      <webElementGuid>4bfb8ae1-0e75-438e-98bb-a61cdb6e5737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>87e9074a-d496-46f8-b98c-292628a011e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>aab205e4-def6-455e-9554-cdb2c80a90a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Operator_HomeBaseAirportIdent</value>
      <webElementGuid>fbbbf970-213f-49b7-8d43-7ff77dda10be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1c08d9db-073a-4265-a439-0b742b37539a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Operator.HomeBaseAirportIdent</value>
      <webElementGuid>2d65f796-9aa4-4e34-999f-ea1d93bb10ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6878bec6-3997-4ba6-898a-19805544725f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operator_HomeBaseAirportIdent&quot;)</value>
      <webElementGuid>09fc35dd-dca6-49df-a87c-c6e9d1a93818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Operator_HomeBaseAirportIdent']</value>
      <webElementGuid>81dd9287-0325-438b-877b-685ef11a8d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div/div[2]/div[6]/div[2]/input</value>
      <webElementGuid>3cf9faa5-f0ab-4174-8372-64bd09f08562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>a1241f62-5dfa-4b71-98af-ad4b863be869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Operator_HomeBaseAirportIdent' and @name = 'Operator.HomeBaseAirportIdent']</value>
      <webElementGuid>19d5a1ac-a2f4-4b7a-ba04-90572f125153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
