<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>incertificate_textBox</name>
   <tag></tag>
   <elementGuidId>956d6c5b-0406-43cc-b938-a4ea714467a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operator_CertificateNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Operator_CertificateNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f9aac98-bf5d-4042-83fb-f2696252d2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>0d1f8eec-4b76-4d4a-97e3-fdd093e7b2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input</value>
      <webElementGuid>e7d288d0-add8-4726-99b6-07066d3511eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a78df65e-0d2a-4722-8961-9d48b9f7884a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb30ee39-d88f-439a-a360-f711c6cb7c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The Certificate must be at least 2 characters long.</value>
      <webElementGuid>2f4c8949-7ee3-4ec5-8780-3152c4b20352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7be6af1f-b522-4dc1-8ba7-e9de94471e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a6b471f9-7b07-4953-88f5-90576269dbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Operator_CertificateNumber</value>
      <webElementGuid>abd969b6-2119-4b14-8ab9-5059bdffa08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a6161b51-875d-4545-876d-6185939232e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Operator.CertificateNumber</value>
      <webElementGuid>940fb58d-6a5c-4efc-918d-0c06227187d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operator_CertificateNumber&quot;)</value>
      <webElementGuid>9c6057a9-ea96-43ff-8833-81df0b82c707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Operator_CertificateNumber']</value>
      <webElementGuid>64a4325b-4763-42ef-a4d4-90edd71a1340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div/div[2]/div/div[6]/input</value>
      <webElementGuid>a6c5045c-b9ae-43ba-a2f9-329744650695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>4064ed7e-fb50-4de7-b82f-521aa2ba4832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Operator_CertificateNumber' and @name = 'Operator.CertificateNumber']</value>
      <webElementGuid>ca652f46-b22f-43f3-8680-38e08588f9d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
