<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name_textBox</name>
   <tag></tag>
   <elementGuidId>d8868896-ec8f-41b4-96f5-4b5d771d4eba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operator_Name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Operator_Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1ffd84f-127f-4cf4-aaa2-56f84849f41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>test12</value>
      <webElementGuid>4171e526-b6fe-4840-9411-44a103b015bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input ams-required</value>
      <webElementGuid>658f9ca6-df62-42da-b8f4-bd8aac357b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71d40998-8180-4cdd-a6f8-0ab211cfa439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c585f8df-0f75-46d2-8624-b20001add2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The Name must be at least 2 characters long.</value>
      <webElementGuid>2dbbce54-0eea-454a-ba02-b44bf1c364c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>5ddd0373-679e-48b7-961a-5f8d231ef472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-min</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a410380d-3efd-4713-877a-657069e95ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Operator_Name</value>
      <webElementGuid>5039009b-b222-4d0b-9333-779290c40a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>f60a8378-bc02-4728-9da4-36764acbb1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Operator.Name</value>
      <webElementGuid>c67f5539-10ba-4fa4-aaee-79fc6cd87a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operator_Name&quot;)</value>
      <webElementGuid>4738932d-86e6-4f4d-b8c4-3136a0d26fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Operator_Name']</value>
      <webElementGuid>afb44768-07d1-4271-bc79-bd12ea3144ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>7853624a-2c19-492b-b5b4-c6aa9c2fe3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>f17d2880-b8c0-40d1-b495-efcbae2a0eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Operator_Name' and @name = 'Operator.Name']</value>
      <webElementGuid>105f83ee-14c1-40b9-9355-3e25d5e09016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
