<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>primContact_dropDown</name>
   <tag></tag>
   <elementGuidId>5c6c5c3d-deda-4497-973b-810976d0ea12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PrimaryContactId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PrimaryContactId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ad522e2-8832-47d8-aff2-fb163ec6b40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-select</value>
      <webElementGuid>6d6749d5-72dc-4995-a86d-adb32252b855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrimaryContactId</value>
      <webElementGuid>230ea8d8-f853-4a0e-981b-a6f355b13134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimaryContactId</value>
      <webElementGuid>4f4923e1-8ec0-4451-a9f0-eac3435fea72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    
                (No Name Entered)
Katalon,Test1,contact1
Katalon,Test2,contact2
Katalon,Test3,contact3
</value>
      <webElementGuid>8fc7c825-dc69-4cf8-b56c-3cec9a185b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrimaryContactId&quot;)</value>
      <webElementGuid>3138b721-f0e8-4f64-a474-233a38f147e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PrimaryContactId']</value>
      <webElementGuid>ed237f21-ba73-4f3a-afa0-713e736f45ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div/div[2]/div[3]/div[2]/select</value>
      <webElementGuid>4dd773a0-b18a-4ddb-b95d-87eb08b88a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prim. Contact'])[1]/following::select[1]</value>
      <webElementGuid>afd5084d-8279-4f88-ba23-1c81d9a16d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cert Date'])[1]/following::select[1]</value>
      <webElementGuid>acf03796-7e52-4ec4-b27c-97bc9f6acc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prim. Phone'])[1]/preceding::select[1]</value>
      <webElementGuid>d006ab90-2ff3-445c-9f34-7b3f0dddfb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prim. Email'])[1]/preceding::select[1]</value>
      <webElementGuid>bcf5ec9c-85d1-4b70-b69c-c6804d05a5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>ba43f9a4-3300-4792-aea3-7999ce19d4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PrimaryContactId' and @name = 'PrimaryContactId' and (text() = '
                    
                (No Name Entered)
Katalon,Test1,contact1
Katalon,Test2,contact2
Katalon,Test3,contact3
' or . = '
                    
                (No Name Entered)
Katalon,Test1,contact1
Katalon,Test2,contact2
Katalon,Test3,contact3
')]</value>
      <webElementGuid>bfddb0c2-f04d-4bbf-8ca4-ff4abf15a15f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
