<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>url_textBox</name>
   <tag></tag>
   <elementGuidId>a66296b4-075b-4d5e-8307-9fec48b05ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operator_Url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Operator_Url']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>960cdf46-6403-4c1a-86de-7214f9d8f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>operatorKatalon/</value>
      <webElementGuid>147e7081-e83c-4719-9b69-4eb422a42479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input</value>
      <webElementGuid>8ba3ef45-a85d-47d6-affa-47616cd80224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31a7eee4-8c6b-481f-84ac-ae819580eb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Operator_Url</value>
      <webElementGuid>ae971aa4-c143-472e-abfa-3f7f697c6f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Operator.Url</value>
      <webElementGuid>6b29f957-40e0-46c4-8834-d583a7af1544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operator_Url&quot;)</value>
      <webElementGuid>295c166a-deef-4e51-9fc3-a51768afb03b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Operator_Url']</value>
      <webElementGuid>b33a7b67-43b1-4b8e-96a8-e311bb155327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>7c9a02e1-caf9-44ec-b466-8da35023601e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>0b92e8e3-d278-4a58-b754-62f8bda6361e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Operator_Url' and @name = 'Operator.Url']</value>
      <webElementGuid>dbcb7fa6-a26c-4a51-97ca-4a165614b866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
