<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>middle_textBox</name>
   <tag></tag>
   <elementGuidId>4f91b8d0-339d-4498-8229-2e3d8dc0845e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_1__MiddleName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__MiddleName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb9f12c5-0a1f-44cf-8f3c-39f7789ecad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>4be3209e-5295-4733-a7c5-23ef6201a86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-middlename</value>
      <webElementGuid>e88c7c78-8b41-4916-b5b6-2e1b6df2a3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74550d3d-36df-498c-ae06-38ada684d3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ccbe166-c6e0-474a-a347-24ae4abbcb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Middle must be a string or array type with a maximum length of '64'.</value>
      <webElementGuid>bba64cfa-7eb4-4521-86b5-6abf8e6a6d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>2cebd017-5e62-4ddf-9e39-0ddc502d2d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__MiddleName</value>
      <webElementGuid>73abb80d-1bbf-482a-8db0-130f73deff59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>14bfd926-ed62-4905-a048-1aee9dbacbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].MiddleName</value>
      <webElementGuid>69f7f81e-02da-45b4-8dad-af1ceebc17f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__MiddleName&quot;)</value>
      <webElementGuid>f3cc9f93-7fa3-47af-adb7-7a065818b730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_1__MiddleName']</value>
      <webElementGuid>b6f361d1-3af7-411e-94c5-0267235baf91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>96eedd0e-2736-4415-a750-ba095985c30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>d0cca5d0-2050-45d6-835d-6eda84315b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_1__MiddleName' and @name = 'Legs[0].Passengers[1].MiddleName']</value>
      <webElementGuid>a4035cc2-d2c9-4ea0-bbe6-c7db0aa4e4f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
