<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savePassenger_button</name>
   <tag></tag>
   <elementGuidId>df39424a-944e-41c2-bb54-662ed33c4f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Passenger'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.target-baj-results-button-save-passenger.l1p2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41143580-ad0d-4f6b-b4c9-d80872312391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn target-baj-results-button-save-passenger l1p2</value>
      <webElementGuid>9dc311b0-a540-4849-bf87-d0c5626e2e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>768ba9e3-34e2-48fa-acc7-7564cdda7900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ed3fc1ae-04b8-478d-ba1d-90cd8b0b11a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-id</name>
      <type>Main</type>
      <value>1861055</value>
      <webElementGuid>56ac4b38-f56a-43f1-8033-7f500838c9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-class</name>
      <type>Main</type>
      <value>l1p2</value>
      <webElementGuid>d4f560a0-8ad1-43f2-9526-2245229fc9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-number-of-legs</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9dc69b4b-48ba-4c96-8ef3-a1244ffb738c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f4b54e1-dd01-4e69-90ea-a7dcd818d6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Passenger</value>
      <webElementGuid>37fb0f2b-d013-4b6f-95a7-a081f1d1605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengercontainer-leg-1-number-2&quot;)/div[@class=&quot;clearfix baj-results-pax-grid-box&quot;]/div[@class=&quot;save-passenger-container   no-margin&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-xs-12 text-center&quot;]/input[@class=&quot;baj-btn target-baj-results-button-save-passenger l1p2&quot;]</value>
      <webElementGuid>5dc4a25e-b22a-471e-9313-5c8fb7f389a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Passenger'])[2]</value>
      <webElementGuid>68fa4fab-1abe-46f5-a3e4-ff3d9256d33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>982bcfeb-c946-4f7f-bd6c-629f0e107517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>0c64d06a-4ece-47e9-ad14-a373f7aa7dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ca51e30b-5a2d-4ed9-8aa4-f302b3929123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
