<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveToMyPassengers_checkBox</name>
   <tag></tag>
   <elementGuidId>c6c4d205-1a0c-4158-8c03-7b9a6f435f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_1__SaveToMyGuests']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__SaveToMyGuests</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7097dc6-3a8c-4cd3-a254-a75851b35785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4dd3ed82-e65d-4393-877f-ee70c1a1be6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Save to My Passengers field is required.</value>
      <webElementGuid>d78238f4-7721-4990-8a29-3eb76bc5eed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__SaveToMyGuests</value>
      <webElementGuid>80d76cfa-72c8-4f9d-9a43-922f9574712b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].SaveToMyGuests</value>
      <webElementGuid>f7ddaf57-8f08-49d6-b4db-6544c163da64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>80e009aa-03e8-44b5-a4f5-8b3e90521b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b80752be-30ee-4195-9e0b-1327cb62e481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__SaveToMyGuests&quot;)</value>
      <webElementGuid>8f13de75-06cb-4922-8820-b7e2eea6060b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_1__SaveToMyGuests']</value>
      <webElementGuid>e56d273f-4f19-4430-82e7-c9e346c8751d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div[7]/div/div[3]/div/input</value>
      <webElementGuid>e4100483-605a-4792-811c-1fc1fd2f4ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/div/div[7]/div/div[3]/div/input</value>
      <webElementGuid>2478c99f-b361-4181-be93-eb78665d3960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__Passengers_1__SaveToMyGuests' and @name = 'Legs[0].Passengers[1].SaveToMyGuests' and @type = 'checkbox']</value>
      <webElementGuid>9faa81fe-8cd4-4294-805c-56babd1641df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
