<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>secondFlight_link</name>
   <tag></tag>
   <elementGuidId>29dba090-a1c4-498f-b612-1e7d19bc998a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flight-plan-list']/div/table/tbody/tr[2]/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b61da5bf-c5e5-47c5-a338-ab4806313f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flight-plan-id</name>
      <type>Main</type>
      <value>580011</value>
      <webElementGuid>ace1c407-2c50-4d07-abe2-d39c9605e31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ams-table</value>
      <webElementGuid>1a5f3149-9b30-4bfa-88d3-839f197c12e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Ams/ClientDetail/67819?loadFlightPlanId=580011&amp;tempApp=app#Flights</value>
      <webElementGuid>ff87cca1-2f9b-4dc2-ba64-c4e6b07860ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NR23031410</value>
      <webElementGuid>41350c18-e8d9-4826-b35c-876ae225c43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Flights&quot;)/div[@class=&quot;target-flight-plan-flight-list&quot;]/div[@class=&quot;target-spf-div&quot;]/div[@class=&quot;member-access-form&quot;]/div[@id=&quot;flight-plan-list&quot;]/div[@id=&quot;flight-plan-list&quot;]/div[@class=&quot;member-access-form&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;target-flight-plan-row&quot;]/td[@class=&quot;no-wrap&quot;]/a[@class=&quot;ams-table&quot;]</value>
      <webElementGuid>d92665f4-9785-4799-93d9-dddebdb247d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flight-plan-list']/div/table/tbody/tr[2]/td[3]/a</value>
      <webElementGuid>bcf28030-6fda-4b02-b38a-c8f860bdd819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NR23031410')]</value>
      <webElementGuid>a40a655b-9911-4379-8780-8826fcea2b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NadyaCL Katalon'])[3]/following::a[1]</value>
      <webElementGuid>5644e640-af19-43de-9bcd-ec4d4fe803dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Booked'])[1]/following::a[2]</value>
      <webElementGuid>aa103199-8a2f-4e24-b0fe-c25980631e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAPA'])[3]/preceding::a[1]</value>
      <webElementGuid>ae6f5f50-3bc0-4f10-ab62-a3dcf41661b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KLAX'])[3]/preceding::a[1]</value>
      <webElementGuid>0aa927aa-3081-4df1-9195-0380f1da31c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NR23031410']/parent::*</value>
      <webElementGuid>667a9392-615c-495c-8236-dd0681c48cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Ams/ClientDetail/67819?loadFlightPlanId=580011&amp;tempApp=app#Flights')]</value>
      <webElementGuid>e59e4cab-761a-4793-914b-b86907548bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/a</value>
      <webElementGuid>9920cb4f-e9b5-44c5-857d-7b725983c1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Ams/ClientDetail/67819?loadFlightPlanId=580011&amp;tempApp=app#Flights' and (text() = 'NR23031410' or . = 'NR23031410')]</value>
      <webElementGuid>f97f0c01-ecd3-4ccc-af78-920375d92523</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
