<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>attachments_checkBox</name>
   <tag></tag>
   <elementGuidId>f000df00-1eb9-48ae-88f2-bd4883fa24ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='5aaf75e5-063b-5078-02d2-545b50401128']/div/div/div[8]/div/label/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ms-Checkbox-checkmark.checkmark-401</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3fc798ee-8520-4719-868b-46daf01b4630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>CheckMark</value>
      <webElementGuid>0473191b-4e43-499a-923c-38102ef79216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f02241ef-f9c0-4ef7-9470-f4edea2924a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Checkbox-checkmark checkmark-401</value>
      <webElementGuid>640bf54d-1f27-42d3-b465-8dea3e40bbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>863d058b-6f25-4547-a21f-0cd900a48b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5aaf75e5-063b-5078-02d2-545b50401128&quot;)/div[@class=&quot;ms-Callout-main calloutMain-370&quot;]/div[@class=&quot;Ivs_N&quot;]/div[@class=&quot;Kjlf6&quot;]/div[@class=&quot;ms-Checkbox reversed is-enabled root-395&quot;]/label[@class=&quot;ms-Checkbox-label label-397&quot;]/div[@class=&quot;ms-Checkbox-checkbox checkbox-398&quot;]/i[@class=&quot;ms-Checkbox-checkmark checkmark-401&quot;]</value>
      <webElementGuid>6d27436f-90a9-4344-b917-5ac8a2718d21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5aaf75e5-063b-5078-02d2-545b50401128']/div/div/div[8]/div/label/div/i</value>
      <webElementGuid>1f09bdb3-3335-411a-a66c-e4b02b909de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/following::i[1]</value>
      <webElementGuid>15a8a273-299c-4bff-921d-d0d8fe9f3d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date'])[2]/following::i[2]</value>
      <webElementGuid>8099fb39-f79f-407e-88fb-854bd15a0683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::i[1]</value>
      <webElementGuid>a2c2cfa2-c573-439d-ad83-97c5e9a6ba8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear filters'])[1]/preceding::i[1]</value>
      <webElementGuid>f670dd04-1617-4c99-bb30-4b948cc0a82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>a531f83a-5c30-4579-a55b-0782dc331c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/i</value>
      <webElementGuid>924eb3e9-7f66-4e28-ae0b-d022936de252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>011736fc-7ecd-4950-8593-102e19ccf983</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
