<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateToSelectADate_textBox</name>
   <tag></tag>
   <elementGuidId>935ac203-f449-43df-9e56-1d4162c7ac21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DatePicker391-label']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DatePicker391-label > span.readOnlyPlaceholder-389</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a38728e6-48b4-4719-88ed-67a363453df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>readOnlyPlaceholder-389</value>
      <webElementGuid>be84f89c-fa30-41e0-ac86-7fcff7b7141a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a date</value>
      <webElementGuid>0cbb23b7-d244-4264-8054-f50898d85c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DatePicker391-label&quot;)/span[@class=&quot;readOnlyPlaceholder-389&quot;]</value>
      <webElementGuid>bb3ef38a-41bb-4745-b2c0-32ab6811121c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DatePicker391-label']/span</value>
      <webElementGuid>f11942b3-86f0-4155-908a-203d7d41d166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='to'])[1]/following::span[1]</value>
      <webElementGuid>651bcdc3-1d46-4d18-9ca7-898abc93188b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a date'])[1]/following::span[3]</value>
      <webElementGuid>4af81180-a096-4569-923f-2dc69c64a585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/preceding::span[2]</value>
      <webElementGuid>11d104c2-f822-4200-9696-7fdf589fd746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::span[2]</value>
      <webElementGuid>12c02d72-6522-409a-90ed-379a46a3bd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/div/div/span</value>
      <webElementGuid>7df517b1-ff45-47fe-a4db-43cf9648f5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select a date' or . = 'Select a date')]</value>
      <webElementGuid>92b46b1b-4b64-413b-982c-086c8183708c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
