<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstEmailONEflight_button</name>
   <tag></tag>
   <elementGuidId>bd1d300b-b243-4f4e-b2b9-ba4b0e95ce13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;ONEflightWebSystem@ONEflight.net&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a41d4da3-c825-4af5-93ac-a58fbcace523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ONEflightWebSystem@ONEflight.net</value>
      <webElementGuid>ef131a56-82aa-4d7e-bc4b-e6096ca0ebe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ONEflight</value>
      <webElementGuid>e7f8a762-1fe3-4d6b-8c59-737bf882487a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;83036e90-b29a-5564-6358-e8b65996066e&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi epBmH&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]/div[@class=&quot;S2NDX&quot;]/div[@class=&quot;lMF6w XG5Jd&quot;]/div[@class=&quot;W3BHj gy2aJ Dc0o9 Ejrkd&quot;]/span[1]</value>
      <webElementGuid>01af9197-0d9b-4f1c-9c96-459d9683a69a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='83036e90-b29a-5564-6358-e8b65996066e']/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>154047c3-ff32-488f-8cd9-a0a289504859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O'])[1]/following::span[1]</value>
      <webElementGuid>ccaa8011-0907-44d4-89ad-21c0056a4119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top results'])[1]/following::span[2]</value>
      <webElementGuid>3e64fa44-c508-4135-9882-178bd583e995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staging: 2023_5_3_KAPA_KATL_KDEN_KMIA_OPENBAJ2023_FlightConfirmation'])[1]/preceding::span[9]</value>
      <webElementGuid>00e5a865-31de-43cf-9682-2981074fd7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tue 4:13 PM'])[1]/preceding::span[10]</value>
      <webElementGuid>ae53210c-43d1-4fca-9bbf-9e3ceb8a7521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ONEflight']/parent::*</value>
      <webElementGuid>d0cb3a67-ce0d-4865-bc91-39b2b8d38624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>b941d0ca-2853-4fae-9eb2-ae6e2340f683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'ONEflightWebSystem@ONEflight.net' and (text() = 'ONEflight' or . = 'ONEflight')]</value>
      <webElementGuid>1c48c766-278b-4b5a-aca1-0b7f838246c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
