<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>keywords_textBox</name>
   <tag></tag>
   <elementGuidId>4b400858-99dc-4449-928a-a8375a004a7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Keywords-ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Keywords-ID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c607a2e-400a-4786-8d6f-d80d9ea73cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>413aff44-929c-4638-8e8a-f3540fb4a187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Keywords-ID</value>
      <webElementGuid>f7093aec-8ae8-4454-b43c-7604a61e60f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-TextField-field field-406</value>
      <webElementGuid>7eaf299a-2614-4984-bd53-ca41b80963f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e790fddb-9c11-41dd-8f4c-d7830462a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Keywords-ID&quot;)</value>
      <webElementGuid>579723c4-9081-4906-9891-722d9d44a55a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Keywords-ID']</value>
      <webElementGuid>d4382cc2-1246-4fb2-b343-c8aab73f9389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5aaf75e5-063b-5078-02d2-545b50401128']/div/div/div[6]/div/div/div/input</value>
      <webElementGuid>90f68b5f-c395-4106-9d66-b3a46e0490e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>4edec5c6-7527-47b5-9e5a-2890362a88ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Keywords-ID']</value>
      <webElementGuid>51e3b4cc-35b9-4c3d-b206-6ddbccedace9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
