<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_dropDown</name>
   <tag></tag>
   <elementGuidId>021e920d-b4ce-4a4d-a455-59ed09c5aab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FlightPlan_AccountId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_AccountId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b439e37c-d028-4603-bba7-cee06f454300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input target-baj-results-selected-account-select grayback select-round form-control</value>
      <webElementGuid>cab58479-adce-4289-ae1d-70aca29c64ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_AccountId</value>
      <webElementGuid>2ebe74e5-ea06-4e98-92c5-c9a5510f1077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.AccountId</value>
      <webElementGuid>0ca1315a-1416-4f24-b088-ea92f861b420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>BAJ.ChangeSelectedAccount(this);</value>
      <webElementGuid>7aab6aee-4822-440b-85bd-c5ef7f25c48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charter Test Rassadina; Charter Charter
</value>
      <webElementGuid>dc74a5db-773a-4f7a-ba5c-c017300f723c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_AccountId&quot;)</value>
      <webElementGuid>ddf52fb9-6ef7-403c-8199-db88d65b2b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FlightPlan_AccountId']</value>
      <webElementGuid>605dda66-d6ea-40f7-88d3-980c0595b36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div/div/div/div/select</value>
      <webElementGuid>b4467f10-38a7-4241-85a1-e96fad64c385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::select[1]</value>
      <webElementGuid>90e1e047-eabb-4794-b09b-f36aec675bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='privacy policy'])[1]/following::select[1]</value>
      <webElementGuid>9d35951a-a01b-4816-8580-9c150b118643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/preceding::select[1]</value>
      <webElementGuid>ea7e8370-3324-4ccb-9a1f-4e311caa6ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AMEX Information'])[1]/preceding::select[2]</value>
      <webElementGuid>067157b2-09e7-445d-92c7-13382532b54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/select</value>
      <webElementGuid>a59919c6-57e9-48a8-b602-84dfff09fb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FlightPlan_AccountId' and @name = 'FlightPlan.AccountId' and (text() = 'Charter Test Rassadina; Charter Charter
' or . = 'Charter Test Rassadina; Charter Charter
')]</value>
      <webElementGuid>29746572-c03b-4a81-bf24-00cc78e2adb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
