<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>electronicSignature_textBox</name>
   <tag></tag>
   <elementGuidId>69a20d47-f055-45f9-a0b7-43df3f1bac07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_ElectronicSignature']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_ElectronicSignature</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99985889-e140-4b60-90fc-20e0550d2c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>17996b9f-a087-466a-8879-9e6c37f65e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cde89208-ae6e-4216-b541-ced438d60c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Electronic Signature field is required.</value>
      <webElementGuid>9110ff4f-ed70-481d-afc9-7d060d8eb30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_ElectronicSignature</value>
      <webElementGuid>49d874aa-0813-4dc8-9d7f-be73a71df086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.ElectronicSignature</value>
      <webElementGuid>ca4de0d0-6102-4e4f-8242-a711cb97df10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8ac1c59-ccc7-42bc-ad50-b4c95c2a430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_ElectronicSignature&quot;)</value>
      <webElementGuid>a15b6e9f-73ff-4c37-ad19-c873c754955d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_ElectronicSignature']</value>
      <webElementGuid>8e4666f1-ec41-4a52-9855-ef5c6a0c26eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div[2]/div/div[7]/div/input</value>
      <webElementGuid>fb28fe43-3a7f-41c2-b1a6-285cd617f9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>86daf7e4-d313-4e1d-832b-9651efdb242e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlan_ElectronicSignature' and @name = 'FlightPlan.ElectronicSignature' and @type = 'text']</value>
      <webElementGuid>50833e32-46fe-45c8-aaa5-fa33caa166b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
