<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pay_button</name>
   <tag></tag>
   <elementGuidId>09272ab2-16c0-46eb-a4e6-a239c2cf5ed3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Pay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.baj-btn-pay.target-baj-results-button-submit-payment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07ef4d93-e210-4231-9c9f-5da7fa028a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn baj-btn-pay target-baj-results-button-submit-payment</value>
      <webElementGuid>aeaf905c-3291-4ad3-9f31-4da2a4d8a185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>feff956e-4daf-4d94-a191-12ea871f9b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>BAJ.Pay(this);</value>
      <webElementGuid>c8c3f115-25f6-4057-8678-fbdefdcd196d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pay</value>
      <webElementGuid>4932f383-ddf6-49c4-bb5e-9cfe6b634824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PayForm&quot;)/div[@class=&quot;row-fluid clearfix baj-results-pax-grid-box&quot;]/div[1]/div[@class=&quot;row-fluid clearfix&quot;]/div[@class=&quot;col-xs-12 text-center&quot;]/input[@class=&quot;baj-btn baj-btn-pay target-baj-results-button-submit-payment&quot;]</value>
      <webElementGuid>e75a9898-1fcc-4609-b0d0-ea34c849ff77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Pay']</value>
      <webElementGuid>cad1247e-6e2e-400e-aaca-32aead936af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div[2]/div/div[8]/div/input</value>
      <webElementGuid>302891c8-a655-448b-89ed-6e4b3f91e829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>2e28d797-3c77-4f3c-884f-e290e206f653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ab3ece81-1619-40fd-87c1-5b05574f28ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
