<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paymentMethod_dropDown</name>
   <tag></tag>
   <elementGuidId>6c4ba1bd-0aa2-40b6-be2a-6551078f951d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FlightPlan_PaymentMethod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_PaymentMethod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b62681fe-e3f3-4845-ad92-81a387466464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input target-baj-results-method-of-payment-select grayback select-round form-control</value>
      <webElementGuid>a98911b0-4239-4633-8bc3-a407ed88b229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8252b214-b36e-4d0d-aea1-bc882427a95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Payment Method field is required.</value>
      <webElementGuid>c60c9e9b-2ba8-442c-933f-562bd8db8a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_PaymentMethod</value>
      <webElementGuid>41c4962d-61df-4733-8371-a9d11bf2b8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.PaymentMethod</value>
      <webElementGuid>76a25f55-b9ab-4a13-beba-a177055d403e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>BAJ.ChangeFormOfPayment(this);</value>
      <webElementGuid>0d869aaa-86c3-4e04-8693-d78e2f2f1dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>American Express
Member Account
</value>
      <webElementGuid>5d316bf5-2ec1-4912-9afd-dbc3c9c5a0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_PaymentMethod&quot;)</value>
      <webElementGuid>d63fc4e6-3948-4811-a638-dfac11bc388b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FlightPlan_PaymentMethod']</value>
      <webElementGuid>653bda11-d7e9-4cdc-bd3e-e7b234b7274f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayForm']/div/div/div[2]/div/select</value>
      <webElementGuid>ed7ee8a0-b16b-4eb6-827d-d24d178173b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/following::select[1]</value>
      <webElementGuid>d5e07126-a17a-4e7e-bd87-be4f2921d14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/following::select[2]</value>
      <webElementGuid>645f98b3-c4a2-4111-847d-d16f249cad8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONEflight Membership Account'])[1]/preceding::select[1]</value>
      <webElementGuid>cef57b86-7520-4222-b8b2-8e1e04161ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>8b16e3ad-4314-4ca9-b51d-fcac9089b0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/select</value>
      <webElementGuid>5dfc7dbb-804f-465d-b024-5757167662f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FlightPlan_PaymentMethod' and @name = 'FlightPlan.PaymentMethod' and (text() = 'American Express
Member Account
' or . = 'American Express
Member Account
')]</value>
      <webElementGuid>2a3a5ab6-9c52-4d10-b2d8-8bba010c0906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
