<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendFlightDocuments_button</name>
   <tag></tag>
   <elementGuidId>c660fa52-7733-4e37-84cb-0abe6b2c165a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Send Flight Documents']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-flight-plan.target-flight-plan-senddocs-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dd483e6-23f1-4349-ba8f-c39fedf73e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86cf5f08-926c-422b-9dc2-1863c8ee73fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send Flight Documents</value>
      <webElementGuid>00cb30b5-e63b-4964-a084-9589b607be9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-flight-plan-senddocs-btn</value>
      <webElementGuid>6aadbb31-9a1a-4d36-9b0a-6a0ba63e2eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Ams.SendFlightDocs(this);</value>
      <webElementGuid>bf0e0109-3b04-4963-be19-7b8b2c405568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-aircraft-list request-list&quot;]/div[@class=&quot;flightplanflow-window&quot;]/div[58]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 margin-top-5&quot;]/input[@class=&quot;btn btn-primary btn-flight-plan target-flight-plan-senddocs-btn&quot;]</value>
      <webElementGuid>38d0138c-05bf-49f6-80bd-73863b57f7e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Send Flight Documents']</value>
      <webElementGuid>9583443b-e1b0-40cf-8160-00e4d0b0b8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[2]/div[58]/div[3]/div/input</value>
      <webElementGuid>ac8d308a-dfca-4a0f-9dcd-57348a4ebc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[58]/div[3]/div/input</value>
      <webElementGuid>9777c894-44d0-4958-8530-1d8fa97a23d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>3e2f4d86-7dbf-4d57-b0c5-1b2f720a0c78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
