<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address 2_textBox</name>
   <tag></tag>
   <elementGuidId>8f13aec9-7414-4f8e-8efe-765786504007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76fab507-85e9-47b6-a827-7c815800aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>438f20e7-3eb8-429a-b7c8-a25d43c729fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d93ff68-685e-420f-8ac6-af6790404dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f256f8d2-e7fd-4826-b2ff-cadb8948605b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>74846b2f-1426-47bf-bbf0-ded3dc09598e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Address 2 must be a string or array type with a maximum length of '50'.</value>
      <webElementGuid>747004c9-1547-49e4-b268-3c9174a601e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>13d42bda-0c0e-40b6-a0de-1f693030aab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2</value>
      <webElementGuid>4674e206-22f3-4224-91a8-778e822adb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7d75d115-aaa9-4f17-b4a3-023f0c5a42a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Street2</value>
      <webElementGuid>f89176c1-dc88-4718-8f90-99f710aee748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2&quot;)</value>
      <webElementGuid>fb7af4fc-56f0-428c-a4ab-27e7226b4dfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2']</value>
      <webElementGuid>fbfe7856-7f7c-4a04-8ad1-e5aaf6d8e1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-2-pickupform']/div/div/div[2]/input</value>
      <webElementGuid>86d0e176-9870-4cbb-b490-ab79e067ef7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>d9b315fc-a8d1-4d38-b230-d718dd577555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Street2' and @name = 'FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Street2']</value>
      <webElementGuid>dca600c5-3c65-4cc7-b55a-cdd38e102099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
