<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_textBox</name>
   <tag></tag>
   <elementGuidId>39de245a-a2f6-4b07-885b-52fe49605d83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d61d0e2a-7843-4f64-b053-9033df8ee0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>37f85ef0-8ad4-48a4-8f45-c2ea8379cafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0942267e-9955-46b1-8651-01b2026c6c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address pickup-address ui-autocomplete-input</value>
      <webElementGuid>4ba9aef2-2994-4920-adc2-6d502279b6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89ed77aa-e166-4385-addb-ebb13bea7982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>420861f4-e967-42a4-810b-b7ed86576560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Country must be a string or array type with a maximum length of '30'.</value>
      <webElementGuid>68789e7a-e648-4864-bbf0-9666b0c339b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>39837f2a-4e4a-4ba4-be60-a2f9f63fb61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Country</value>
      <webElementGuid>830e8305-49f5-4ef9-85c3-d6956bf25152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6a98bf21-e67a-4e8a-bc01-c3cbfc13f30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Country</value>
      <webElementGuid>4be0d35c-eda7-42a5-9dc0-3f28f322bca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Country&quot;)</value>
      <webElementGuid>b7f4d7c1-f2c3-45f6-8574-f23857afec74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Country']</value>
      <webElementGuid>98bf3b58-9ea3-4d46-97d5-79339300b56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-2-pickupform']/div/div/div[6]/input</value>
      <webElementGuid>54a7e20f-8052-4aba-9fc3-828924aeaf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div[6]/input</value>
      <webElementGuid>6834c325-eb8d-4839-9d88-a136c22da3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupFullAddress_Country' and @name = 'FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupFullAddress.Country']</value>
      <webElementGuid>8e3608d9-b725-4fef-90ec-dae15163dcc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
