<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pickUpInstructions_textBox</name>
   <tag></tag>
   <elementGuidId>b43f02be-a968-4533-9472-626014126a3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupInstructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupInstructions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3ee9796b-aa8d-42ca-b902-74b557d47c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8eaf6a5f-593c-4f64-9805-84030c17eab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3223c933-845c-4b9d-8993-2f7baaba7ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupInstructions</value>
      <webElementGuid>6b009e5c-e079-44de-9bcb-a201830cec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupInstructions</value>
      <webElementGuid>9009fcc1-2547-47a2-b3d4-21d563a10e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupInstructions&quot;)</value>
      <webElementGuid>6fa64849-bb5f-45bc-bc37-32edb2ad9e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupInstructions']</value>
      <webElementGuid>45adaf5a-d772-44cf-b70c-f1f61dacc363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-2-pickupform']/div/textarea</value>
      <webElementGuid>ca31faa7-c380-423e-ae53-dfb6799e4f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/textarea</value>
      <webElementGuid>64d64b09-3b12-4a3d-98fd-d3c373579eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'FlightPlan_Legs_2__ActiveConciergeOrder_ExecutivePickupInstructions' and @name = 'FlightPlan.Legs[2].ActiveConciergeOrder.ExecutivePickupInstructions']</value>
      <webElementGuid>1038554f-349b-41f4-a9b7-f3c247dc5701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
