<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveToMyPass_checkBox</name>
   <tag></tag>
   <elementGuidId>c0537098-63bc-4a30-8730-cf689e4c15d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_2__SaveToMyGuests']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__SaveToMyGuests</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a97a6904-4d44-4e28-bee1-3e0e91135993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e81190a6-f38f-43bc-9430-e9ea54e612e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Save to My Passengers field is required.</value>
      <webElementGuid>a9e36bd6-ae81-42fc-a8ab-9f9b71dac488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__SaveToMyGuests</value>
      <webElementGuid>e329c404-5e94-499b-8061-551c0c54e943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].SaveToMyGuests</value>
      <webElementGuid>5e603d89-ea0b-483b-91f3-e49c2e99201b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae71a713-1c89-4fe1-8d6d-6bcfacde9008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4900dfd9-e442-4902-8624-a610241c9c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__SaveToMyGuests&quot;)</value>
      <webElementGuid>e5ec5962-061d-4cb5-b716-2c038a3eb044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_2__SaveToMyGuests']</value>
      <webElementGuid>fedafdb7-6503-4c15-bd5d-6fa39156f51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[7]/div/div[3]/div/input</value>
      <webElementGuid>deddbde6-a692-4545-9e3e-28ee8ad1e382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]/div/div[3]/div/input</value>
      <webElementGuid>166fcced-ca30-40dc-9aa7-0cfd48185e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__Passengers_2__SaveToMyGuests' and @name = 'Legs[0].Passengers[2].SaveToMyGuests' and @type = 'checkbox']</value>
      <webElementGuid>5dd10542-9f53-483b-b3be-dc3fab80ffe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
