<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>year_textBox</name>
   <tag></tag>
   <elementGuidId>cb6513aa-abb7-4232-bfac-4aa5cbcfbe3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_2__BirthDate_Year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__BirthDate_Year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aa56463-5fca-425f-896f-0d2c3255d233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f992d1b2-77a2-48f9-8da7-2cab74ccc4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maskYear baj-results-inp form-control target-birthdate-el target-pax-birthyear</value>
      <webElementGuid>94748cad-c36b-402c-9dfc-ae05cbbdf510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Year</value>
      <webElementGuid>97b18106-a34d-4d7b-bef6-498d2ab6a646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1c3cc3f4-ae9c-412d-b7fb-490b6e66c5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c428256-a3b0-4c2a-bec7-481d8f239d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The BirthDate_Year field is required.</value>
      <webElementGuid>94d3d3db-e12c-42f7-8716-0ec339ee3521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__BirthDate_Year</value>
      <webElementGuid>e5a40d59-5cc0-49e9-b7c2-cb0965744dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].BirthDate_Year</value>
      <webElementGuid>ed09a162-b4c3-41bc-a6a4-86012aa46c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__BirthDate_Year&quot;)</value>
      <webElementGuid>c4537266-4938-481a-b94b-f58d7c0cc417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_2__BirthDate_Year']</value>
      <webElementGuid>3df16aa4-1020-4436-ad2f-276b01d8f7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[2]/div/div/div[4]/input</value>
      <webElementGuid>51b4b644-01ae-4939-951f-654007d446b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[4]/input</value>
      <webElementGuid>b38c182c-f054-4921-9fb5-f6d4ae234a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Year' and @type = 'number' and @id = 'Legs_0__Passengers_2__BirthDate_Year' and @name = 'Legs[0].Passengers[2].BirthDate_Year']</value>
      <webElementGuid>0f474d14-f53c-4c15-bd4e-c5b4b2c00dc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
