<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openAnotherMailbox_textBox</name>
   <tag></tag>
   <elementGuidId>28c67093-debc-459f-9aaa-5e5ba027140e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ms-BasePicker-input.pickerInput_9f838726</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffb3aedc-3056-44a0-8602-c016257dbde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>28a4bb7a-1fcd-4d3d-a52f-f30a24979123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>85ee6427-f43a-4884-8741-405815625fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>ae6905ef-5ec8-45a6-83c9-4707ef2b8ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-BasePicker-input pickerInput_9f838726</value>
      <webElementGuid>8a4cb1c2-eac2-4716-b9d5-239260aabfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>240d908d-96dc-4b5d-80a4-26bf5659debf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86242875-f044-4545-bf4a-0ade1f988202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>0ed6400f-5af7-4307-88cc-1ae1c67e5149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lpignore</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>018e37d2-e5b1-4823-85a7-9c1e4b94fa1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eae636d8-0d37-4488-93e5-a8e683c42559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone461&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-384&quot;]/div[@class=&quot;content-390&quot;]/div[@class=&quot;ms-Dialog-inner inner-393&quot;]/div[@class=&quot;ms-Dialog-content innerContent-394&quot;]/form[1]/div[@class=&quot;LqpTj&quot;]/div[@class=&quot;FD8q0&quot;]/div[@class=&quot;w_uWs&quot;]/div[@class=&quot;E_2JE&quot;]/div[@class=&quot;ms-BasePicker ms-BaseExtendedPicker&quot;]/div[@class=&quot;ms-FocusZone css-159&quot;]/div[@class=&quot;ms-SelectionZone&quot;]/div[@class=&quot;ms-BasePicker-text pickerText_9f838726&quot;]/input[@class=&quot;ms-BasePicker-input pickerInput_9f838726&quot;]</value>
      <webElementGuid>8fb3b5dc-bf34-413e-b5d8-37c109ae3781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[6]</value>
      <webElementGuid>301833aa-56b9-4a26-9fb1-992e47aba496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone461']/div[2]/div/div[2]/div/form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ad61c782-4689-4d14-9c85-d2e2b5c01b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>93b84b36-b0d3-42a0-af85-df138d239470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
