<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openAnotherMailbox_link</name>
   <tag></tag>
   <elementGuidId>37c52867-2854-4956-8bb1-f0ed27ad3f15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mectrl_OwaOpenTargetMailboxLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mectrl_OwaOpenTargetMailboxLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>412d27a2-9c05-41e3-962a-436cb11cb338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mectrl_OwaOpenTargetMailboxLink</value>
      <webElementGuid>959877b5-da3a-48e9-889d-8ef4f642e1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mectrl_resetStyle mectrl_link mectrl_truncate</value>
      <webElementGuid>9c062e06-c561-4033-b427-233d92541679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e37f0f5a-88cd-4ff7-b477-9004523a74f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>466598e7-44e3-4356-95b2-d9589a6c8f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open another mailbox</value>
      <webElementGuid>03207566-7a45-4027-af28-8aec57264892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mectrl_OwaOpenTargetMailboxLink&quot;)</value>
      <webElementGuid>2f281be3-42af-4402-81d6-eb1bf9c6d29d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mectrl_OwaOpenTargetMailboxLink']</value>
      <webElementGuid>87c4a714-43b6-4079-8d69-ec97db9613f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mectrl_main_body']/div/div/div[3]/div/div[4]/a</value>
      <webElementGuid>d5957099-b3c0-43ca-8d87-46c8ca5bf938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open another mailbox')]</value>
      <webElementGuid>d2485484-41a8-4165-ba58-b426fb63c772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review and manage your work or school account information'])[1]/following::a[1]</value>
      <webElementGuid>70584cba-93d4-4174-846c-3d731a13527e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View account'])[1]/following::a[1]</value>
      <webElementGuid>e7ef4f93-0e9a-4a17-8413-e932fe3a5908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Microsoft 365 profile'])[1]/preceding::a[1]</value>
      <webElementGuid>d945b5d3-b839-472f-b287-78c972c92abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[1]/preceding::a[2]</value>
      <webElementGuid>02bfebb0-54fb-4c12-8dd8-8f55e8a8452c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open another mailbox']/parent::*</value>
      <webElementGuid>80294798-d846-4246-ace9-4c296968452e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>e9330e0d-f357-4c22-bfca-50c343324da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>1e1340af-b1c5-4988-ac43-ed192747df7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mectrl_OwaOpenTargetMailboxLink' and @href = 'javascript:void(0)' and (text() = 'Open another mailbox' or . = 'Open another mailbox')]</value>
      <webElementGuid>a12f5aaa-9c02-4fa8-81c9-826f65858170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
