<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>currentCateringRequest_textBox</name>
   <tag></tag>
   <elementGuidId>21d46d91-5e13-4b57-8128-337f85d1f765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='CateringOrderText'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-1-leg-909596 > #catering-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-5 > #CateringOrderText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a75145db-ef01-48a2-b7f1-3be4987569d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CateringOrderText</value>
      <webElementGuid>9556c547-17a2-4003-b9f9-e2ea492433e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CateringOrderText</value>
      <webElementGuid>62c91893-c4a4-4cda-bfa2-02cc2118ce0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909596&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-5&quot;]/textarea[@id=&quot;CateringOrderText&quot;]</value>
      <webElementGuid>8ca906cd-5f33-4ef2-b7ea-b318e4d01ddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='CateringOrderText'])[2]</value>
      <webElementGuid>6653706d-0310-405a-a0ec-7ac85a7b4261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='catering-quote-0']/div/div/div[2]/textarea)[3]</value>
      <webElementGuid>3fd25e6e-4fd4-4bef-82f7-6cc14f2710b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div[2]/div[3]/div[3]/div/div/div[2]/textarea</value>
      <webElementGuid>1afee4f7-904f-4d43-9ed9-959dc78202c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'CateringOrderText' and @name = 'CateringOrderText']</value>
      <webElementGuid>ca2e8276-9dc6-47cf-a291-0218838401e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
