<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>new_button</name>
   <tag></tag>
   <elementGuidId>3e077599-eeaf-441b-a6e1-f7f5e6e10f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passengercontainer-leg-1-number-2 > div.clearfix.baj-results-pax-grid-box > div.row > div.col-sm-12.col-md-4 > a.target-new-passenger-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0ede9e7-e77a-43c0-a0e1-b663c0caa1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-new-passenger-button</value>
      <webElementGuid>5cdcac7a-0761-4baa-a3ff-d6db3d3797e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9b55b5cb-87cd-41a6-aecb-0df8a78c3653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f3294d30-c682-4258-b026-4c53001a6162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-id</name>
      <type>Main</type>
      <value>1861470</value>
      <webElementGuid>cfd5ed1c-db43-4942-874f-5bbcf863ef9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-class</name>
      <type>Main</type>
      <value>l1p2</value>
      <webElementGuid>04b6d660-9285-4217-8011-0d2aad4d00fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-number-of-legs</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>cffae604-f2fe-4b85-ac4c-4fc3a81f2881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                New
                            </value>
      <webElementGuid>82b5770a-4398-4894-a2c3-480029beff62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengercontainer-leg-1-number-2&quot;)/div[@class=&quot;clearfix baj-results-pax-grid-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4&quot;]/a[@class=&quot;target-new-passenger-button&quot;]</value>
      <webElementGuid>f74475d2-dd94-46b9-b99d-db73f58f2bce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div/div[2]/a</value>
      <webElementGuid>781ce7db-1c61-409d-aaf5-8e974283fed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New')])[2]</value>
      <webElementGuid>ff437372-156c-4a8a-aecd-fbd69f373122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save to My Passengers'])[1]/following::a[1]</value>
      <webElementGuid>3a08b7b6-6755-4cb0-8ed2-2bb46d002afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::a[1]</value>
      <webElementGuid>d8e63358-46e1-45b8-9f19-5bcbdac109ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Information'])[2]/preceding::a[2]</value>
      <webElementGuid>84392344-fcba-4b18-b329-d8ee7cd0adde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/a</value>
      <webElementGuid>d506454b-3237-46f1-814e-e5a7a2b70cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                                New
                            ' or . = '
                                New
                            ')]</value>
      <webElementGuid>f4ce13d3-7c51-427f-9ca2-69e205528ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
