<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>suv_textBox</name>
   <tag></tag>
   <elementGuidId>a296e986-8d22-462e-89ef-623659a706c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-3-leg-909637 > #new-executive-quote-noorder > #dropoff-quote-0 > div.panel-body > div.row > div.col-xs-7 > div.row > div.col-xs-4.flex-start > #ConciergeQuoteXExecutiveVehicles_0__Quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ConciergeQuoteXExecutiveVehicles_0__Quantity'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8763839-10be-4a60-aa75-179b538a7b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7f5a08b8-c916-4e90-b5cc-b1e64f27bf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-vehicle-quantities</value>
      <webElementGuid>9299ac56-29e4-44fd-89af-4c1ca2f30284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>70e1a284-1e16-451d-be98-00c72522a8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf75c491-695b-4b4b-b3ea-4f41967c94d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>467e04b3-d090-4cf9-b558-666980211065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vehicletype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7329c433-516b-4222-b348-b1363bebd13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48</value>
      <webElementGuid>2ae1a6d6-dab0-4ab7-b63a-caa2aff652d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConciergeQuoteXExecutiveVehicles_0__Quantity</value>
      <webElementGuid>2a5c1fa6-e8b1-4d64-8984-7cfab73a9a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConciergeQuoteXExecutiveVehicles[0].Quantity</value>
      <webElementGuid>81017ffa-4f61-4e32-9c04-5ff8bef24436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>04d66979-bda2-431b-bd13-1474c2d88158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-3&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-3&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909637&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909637&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909637&quot;]/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 flex-start&quot;]/input[@id=&quot;ConciergeQuoteXExecutiveVehicles_0__Quantity&quot;]</value>
      <webElementGuid>8d407f33-db82-4d37-b9a7-cc6cd048fc75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ConciergeQuoteXExecutiveVehicles_0__Quantity'])[8]</value>
      <webElementGuid>b616d7cd-5bbf-4e33-86ee-df8b6c0a5416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dropoff-quote-0']/div/div/div[3]/div/div[4]/input)[5]</value>
      <webElementGuid>4161da7a-251e-4450-8200-f72c5a52cbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>4366f683-4d9d-4498-a984-426b3bee392b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ConciergeQuoteXExecutiveVehicles_0__Quantity' and @name = 'ConciergeQuoteXExecutiveVehicles[0].Quantity']</value>
      <webElementGuid>a66c5530-7994-4057-bbbe-ab7c479f9201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
