<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>description_textBox</name>
   <tag></tag>
   <elementGuidId>d9dab676-fce5-4dda-bd03-594530ecb2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanPostConfirmEditLogInput_BillItem_Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanPostConfirmEditLogInput_BillItem_Description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca3d31e5-f2d3-479e-b42a-12de3534ae58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-select padding-left-5</value>
      <webElementGuid>62589cfe-f26f-4d23-994c-cbfa183dedb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanPostConfirmEditLogInput_BillItem_Description</value>
      <webElementGuid>5e54ebe0-6a41-4372-9aa9-2acc7b7dfa50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanPostConfirmEditLogInput.BillItem.Description</value>
      <webElementGuid>7ff2a4b3-c64d-44c9-a344-17d5567705e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter a description</value>
      <webElementGuid>c1cddf3d-412c-4362-a912-ca0a8bace27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22e20f28-939b-431a-90a5-df378b78ed13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanPostConfirmEditLogInput_BillItem_Description&quot;)</value>
      <webElementGuid>a492e7c8-a8dd-44bd-b808-145507ff602c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanPostConfirmEditLogInput_BillItem_Description']</value>
      <webElementGuid>cf34b311-2876-4dab-958f-16721e265f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-edit-confirmed-flight-form']/div/div/div/div/div[2]/input</value>
      <webElementGuid>1f243615-21c5-4ee0-98ea-96acffbb6909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/input</value>
      <webElementGuid>05030f21-22fa-482a-a000-e8b1459ec232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanPostConfirmEditLogInput_BillItem_Description' and @name = 'FlightPlanPostConfirmEditLogInput.BillItem.Description' and @placeholder = 'Enter a description' and @type = 'text']</value>
      <webElementGuid>2dea1dfe-5993-4e20-a492-106b9bcf0231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
