<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pancakesRequest_button</name>
   <tag></tag>
   <elementGuidId>bdbcec01-4408-4933-b304-f961cd9daf4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='Pancakes']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pancakes > button.catering-select-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>504087b5-c40d-4d63-ae53-4ad588bc6c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-select-button</value>
      <webElementGuid>c25395e0-b844-431a-8b6b-41e9c518b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Pancakes</value>
      <webElementGuid>2c4a1960-7cfd-4811-a6d3-2385e4b23126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909204</value>
      <webElementGuid>f57f27e4-8916-4701-b7a6-1b4ea7027241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>739496f6-aaa5-40c2-96f2-a1f48664e1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>a054652e-5378-446d-b25c-09e83c716b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request for Leg 1</value>
      <webElementGuid>99d6f501-7fbe-48f9-b002-fbd10cdb4441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pancakes&quot;)/button[@class=&quot;catering-select-button&quot;]</value>
      <webElementGuid>0161dc9f-f52d-4e96-b84f-e61ef467eea1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='Pancakes']/button</value>
      <webElementGuid>78f339fb-81d7-4aa7-9a1b-3a9a1add0f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[3]/following::button[1]</value>
      <webElementGuid>a1808be9-c53d-4e6f-b9d5-5e367e97e3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[5]/preceding::button[1]</value>
      <webElementGuid>44152770-aae7-4c12-ab67-83083ec23994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[4]/button</value>
      <webElementGuid>0a9e879a-73ba-49ad-8d8f-ed2bf2ceda0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request for Leg 1' or . = 'Request for Leg 1')]</value>
      <webElementGuid>e2d32b9c-8b2c-44d9-84ff-c55d55772dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
