<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addressLine2_textBox</name>
   <tag></tag>
   <elementGuidId>36f1c45f-b9a3-40d3-83fc-aca928da2852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Street2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Street2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7bc8d20-22dc-4edd-bf69-3bb1a407cf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tighter-input</value>
      <webElementGuid>aee78735-0d2b-40b8-8c18-95b5137be19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Street2</value>
      <webElementGuid>640b7821-961b-4c22-9211-b200b34644d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street2</value>
      <webElementGuid>04d59e7a-f856-46f7-a5fd-8db856764062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>feaec876-07e3-47d6-95a5-fefd6704e2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Street2&quot;)</value>
      <webElementGuid>ce54d784-1d88-45f3-ba0d-3fe723964107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Street2']</value>
      <webElementGuid>c868210c-66c5-404f-8e94-04fdd6bc71e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[4]/tbody/tr[4]/td/input</value>
      <webElementGuid>6810b384-bb71-43d8-a60a-7dff47c3f633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr[4]/td/input</value>
      <webElementGuid>c0e65716-d5c1-494f-a047-8fe85d649db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Street2' and @name = 'Street2' and @type = 'text']</value>
      <webElementGuid>fe2b42df-73c1-4535-ad15-59a826927a43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
