<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phoneType_dropDown</name>
   <tag></tag>
   <elementGuidId>28babddc-e7c3-489b-a0d9-123ca0879e05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhoneTypeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PhoneTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3defcaaf-8f8c-4512-8abd-91e160868ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tighter-select</value>
      <webElementGuid>fa15378d-65c4-41d9-831b-9729adc12c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneTypeId</value>
      <webElementGuid>b901b9b9-35f7-4b0a-8e9c-8191124bfbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneTypeId</value>
      <webElementGuid>f9a8cb53-b8eb-4ef8-8e4e-2ea745adae61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select
Cell
Home
Work
Business
Contact
Other
</value>
      <webElementGuid>906df4c3-ef2c-437f-9224-2000b5cf0c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhoneTypeId&quot;)</value>
      <webElementGuid>88630231-962d-4bb2-84a1-b02996836f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PhoneTypeId']</value>
      <webElementGuid>455b1d62-9590-45ba-8f63-abe894827926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[2]/tbody/tr[2]/td/div/div[2]/select</value>
      <webElementGuid>b946f99e-3176-4e72-b04e-0ee2051d2cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Type'])[1]/following::select[1]</value>
      <webElementGuid>2175d79c-eaeb-411a-9381-9d756fe6400a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::select[1]</value>
      <webElementGuid>d1fb3467-15d1-424a-ba4a-b185108e11dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/preceding::select[1]</value>
      <webElementGuid>d5eb417e-3015-4714-be78-9255af5e83ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Type'])[1]/preceding::select[1]</value>
      <webElementGuid>8275c3fb-7265-4df8-9378-d2816f4ec145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/select</value>
      <webElementGuid>f2eea038-e7ec-4320-8c49-e7c349a2d2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PhoneTypeId' and @name = 'PhoneTypeId' and (text() = 'Select
Cell
Home
Work
Business
Contact
Other
' or . = 'Select
Cell
Home
Work
Business
Contact
Other
')]</value>
      <webElementGuid>ed7e2736-2ea3-4c97-9a04-f9cf3d6e60aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
