<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ONELOOP</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a68786aa-b219-4ba2-8a20-26f60eeb376c</testSuiteGuid>
   <testCaseLink>
      <guid>6b640986-fac6-4d27-9f18-2439694d3606</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BAJit/logInAsMemberClient</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>916d47dc-6e3c-4e4a-85da-7fdfecd264b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BAJit/forOneLoop/bookingOneWay</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>af2801be-fd97-457e-b845-4a7ad50e2cd1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/oneloop/oneWayBooking</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>af2801be-fd97-457e-b845-4a7ad50e2cd1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>departureAirport</value>
         <variableId>541fa4a3-d334-461d-83c1-552a3edebfff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af2801be-fd97-457e-b845-4a7ad50e2cd1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>destinationAirport</value>
         <variableId>ce1ec345-3365-42cf-aebe-80c80a20077d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af2801be-fd97-457e-b845-4a7ad50e2cd1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>ff5eb124-7e15-49e8-ae71-0db893385748</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af2801be-fd97-457e-b845-4a7ad50e2cd1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pax</value>
         <variableId>cead3491-11d3-4df0-a399-360e9525756c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af2801be-fd97-457e-b845-4a7ad50e2cd1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>account</value>
         <variableId>2a4278e6-4177-4c36-bb1f-3db2bd704dc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e1c6baa-f447-4182-be48-79ba8b39a466</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/closeBrowser</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3e7a7325-d985-47f3-998b-9acc34f43860</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/logInAsSuperAdmin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4d741891-6bb8-432b-ba39-d0f925d08fc0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/oneLoop/searchLegs</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>798bd5f7-d404-4047-be79-af7e8ae0ad4e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/oneloop/searchLegs</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>798bd5f7-d404-4047-be79-af7e8ae0ad4e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>departFrom</value>
         <variableId>46292583-d738-46a0-ba41-1bead6900ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>798bd5f7-d404-4047-be79-af7e8ae0ad4e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>departTo</value>
         <variableId>cc0f1d31-7381-4d4d-9ac5-69a0f69e44a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>798bd5f7-d404-4047-be79-af7e8ae0ad4e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>departureAirport</value>
         <variableId>378d9b19-8639-4bf7-90f2-47a0ceef9207</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>798bd5f7-d404-4047-be79-af7e8ae0ad4e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>departureDate</value>
         <variableId>4667863c-3b3e-4885-b32d-cf75570c9d29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>798bd5f7-d404-4047-be79-af7e8ae0ad4e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>operator</value>
         <variableId>24a59888-9b12-49d1-8e56-3df9ab332122</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>798bd5f7-d404-4047-be79-af7e8ae0ad4e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>aircraft</value>
         <variableId>1de2d2f3-b218-42bd-81f0-1a4368ef64d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98aad391-5429-4e74-9406-9a8d737662e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/oneLoop/addLegsAndSave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>59824303-794c-4b24-9b11-83a462057abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/oneLoop/savedLoopSearchFields</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a87ae95e-a1c9-46eb-9937-ed7d9b34aa7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>584e471a-a2ae-41eb-bb91-527409abf9a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27256690-288f-43b6-95cb-27993f4ca1eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17eb5ca9-fd75-419e-aeac-523e5fa5454b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6c91e6c-1561-4d8a-acbc-f36bd531c856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a8ca248-3b1f-413c-838d-4a990cf1de46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e55375f4-e603-4cd2-9810-7b4c1cd22c9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/oneLoop/savedLoopActivate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f67d82b6-e610-44a2-82a5-31aaebf23388</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/oneLoop/savedLoopEditDeactivateDelete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f43c89f5-015f-4eb6-b2da-3920c6ce2aad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AMS/deletingFlights/deletingLastsFlight</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
