<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bajHealth_checkBox</name>
   <tag></tag>
   <elementGuidId>0f710e06-5c35-4266-bdf1-1cad520aaaeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SafetyRatingsPanel']/div/div/div/div[7]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c8a3f67f-a974-4c07-8519-af163f29551f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom-label form-check-label</value>
      <webElementGuid>abf8cbe0-5c46-43ac-8d14-76959eba00c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Filter_SafetyBAJHealth</value>
      <webElementGuid>fca883c3-644e-4081-b84a-4959b3b891e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BAJ Health</value>
      <webElementGuid>68bc2ab3-4fc1-4c8f-8a44-a91d33012ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SafetyRatingsPanel&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;check-box-list&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-check col-sm-12 medium-padding&quot;]/label[@class=&quot;checkbox-custom-label form-check-label&quot;]</value>
      <webElementGuid>4d8672a4-872c-49d1-a930-132894005f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SafetyRatingsPanel']/div/div/div/div[7]/label</value>
      <webElementGuid>2195640f-77a7-4a11-b9b7-e117180486a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJ Safety'])[1]/following::label[1]</value>
      <webElementGuid>c95f0f6f-50ff-4207-9407-152727c6d9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IS-BAO'])[1]/following::label[2]</value>
      <webElementGuid>504a274c-84c2-4e5f-88dd-c0d086e2d2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trip Itinerary - Oneway'])[1]/preceding::label[1]</value>
      <webElementGuid>59475333-c043-4a71-8008-2225dc762b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEG'])[1]/preceding::label[1]</value>
      <webElementGuid>0ec5fc24-aad6-4203-aacd-23da8d9dcc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BAJ Health']/parent::*</value>
      <webElementGuid>8efefd6b-babc-435a-98b6-045ecc45918e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label</value>
      <webElementGuid>91ec3275-00fa-48d2-994f-6fe49fe23d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'BAJ Health' or . = 'BAJ Health')]</value>
      <webElementGuid>495ae7c9-9492-495d-a895-74b07d65a45b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
