<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectFirstAircraftLightJet_button</name>
   <tag></tag>
   <elementGuidId>0e55211d-9ac9-4e31-a8a3-cd6ee195ed73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BAJ_Aircraft']/div/div/div/div/div[3]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.aircraft-select-button.target-baj-button-aircraft-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7ea351b-8de0-41c3-9cd0-6627818c75f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e85b7577-1dab-4c25-a7ad-a12cd1fe32cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn aircraft-select-button target-baj-button-aircraft-select</value>
      <webElementGuid>2c033615-d702-40fa-bbf7-383c1d2c5f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aircraft-id</name>
      <type>Main</type>
      <value>4239</value>
      <webElementGuid>0f872808-9952-4b1c-9fbf-38dfa5fa7ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Select 
                                </value>
      <webElementGuid>3490a209-2603-4684-8559-eab449069904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAJ_Aircraft&quot;)/div[@class=&quot;col-xs-12 baj-results-aircraft clearfix colNoSideMargins&quot;]/div[@class=&quot;col-xs-12 colNoSideMargins&quot;]/div[@class=&quot;media aircraftList&quot;]/div[@class=&quot;aircraftList-top&quot;]/div[@class=&quot;media-body&quot;]/div[@class=&quot;aircraft-results-right&quot;]/div[@class=&quot;bookingDetails&quot;]/a[@class=&quot;btn aircraft-select-button target-baj-button-aircraft-select&quot;]</value>
      <webElementGuid>601290fb-4e10-4c68-b4b7-f196bb22e343</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAJ_Aircraft']/div/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>963b6458-d414-47ac-ba63-62cf9a1f679d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Select')]</value>
      <webElementGuid>8b8e90cd-3f32-4b06-a95f-b8c87d7ff58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$15,847'])[1]/following::a[1]</value>
      <webElementGuid>77300dd0-2dad-45d5-940c-665bc968409f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY RATING'])[1]/following::a[1]</value>
      <webElementGuid>d99d505f-42aa-42a4-8091-cc8998d56b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer'])[1]/preceding::a[4]</value>
      <webElementGuid>76f28b12-87be-4d48-a9c8-bfae208f5ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEECH'])[1]/preceding::a[4]</value>
      <webElementGuid>fb2f4835-3e46-406e-ad4a-b694d10b2da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>82a8c507-59d8-4d2e-a428-d1d21c9c55c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[6]</value>
      <webElementGuid>94b10575-b28a-485a-9ab6-7d0c4f444944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>7c9ebcd4-ed5f-4831-905d-81161f29cf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                    Select 
                                ' or . = '
                                    Select 
                                ')]</value>
      <webElementGuid>9787f3f4-3d3e-4fb0-b3d6-e6aff999ec40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
