<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addEmail_button</name>
   <tag></tag>
   <elementGuidId>e99158ef-7467-4880-84a1-58f192657206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > input.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Add Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a4a2b2f-bc35-4a42-abbc-ae7d4673eb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>916718fe-66a0-403d-b314-a42b159810fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>735d2b4a-0f36-4973-bfae-31f9cc22b6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Operator.ContactEmailSave();</value>
      <webElementGuid>9a13dd17-5ecd-4333-960f-d7ef8242133d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Email</value>
      <webElementGuid>72140121-25b7-47b2-a83e-a1619b3cd1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operator-contact-form&quot;)/table[3]/tbody[1]/tr[1]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>bafe225f-940f-4ea5-9ec0-2f481ae04b1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Add Email']</value>
      <webElementGuid>88e20c29-2566-4b66-a7f6-bca3534cc78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[3]/tbody/tr/td/input</value>
      <webElementGuid>725219f3-170d-43f6-93d5-8c029d2dac0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/input</value>
      <webElementGuid>d87d260c-077f-4a82-b509-63411485a8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>1bd5a3c8-b802-4e16-a83e-96f1d07041bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
