<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addNewEmail_button</name>
   <tag></tag>
   <elementGuidId>19e3fac8-e68d-4783-8514-bd216d87ecb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(4) > div.float-right > a.of-link-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='Operator.PopupContactEmail($(this));'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd9594e5-2464-42b4-ba63-12e10ee38b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>c751bb1a-1a0d-4688-9c76-a8dbc6fc2d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Operator.PopupContactEmail($(this));</value>
      <webElementGuid>546120ac-2efe-4c30-8c39-484c957649a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-id</name>
      <type>Main</type>
      <value>1037</value>
      <webElementGuid>3abdd46a-aef5-4d4b-ba1b-4184c3d6d8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-contact-id</name>
      <type>Main</type>
      <value>12229</value>
      <webElementGuid>886b8cf2-1bb0-4999-b200-2fb1f09efd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-email-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d32456e3-7797-4179-8056-1a9bf9e78e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>of-link-black</value>
      <webElementGuid>a16a4994-772a-4211-bc6f-54c63d846e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            New Email
                                        </value>
      <webElementGuid>bada0b66-9705-44d9-8aec-cd39a6b797b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Contacts&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;ContactsDynamic&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;ContactsDynamic&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table ams-table black&quot;]/tbody[1]/tr[4]/td[4]/div[@class=&quot;float-right&quot;]/a[@class=&quot;of-link-black&quot;]</value>
      <webElementGuid>e42dddf0-bc3c-4539-b8cb-370e71d9dfec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='Operator.PopupContactEmail($(this));'])[6]</value>
      <webElementGuid>8d30127c-5864-4aa9-8885-31032ba722b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactsDynamic']/div[3]/table/tbody/tr[4]/td[4]/div/a</value>
      <webElementGuid>4f349ad2-258f-4bb7-8e16-22d22da8b8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New Email')])[4]</value>
      <webElementGuid>80eb31a6-f1b5-44e7-a2f4-0543cd6b695a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Phone #'])[4]/following::a[3]</value>
      <webElementGuid>e0c1fe80-08ec-4646-8f8f-7931ee1712c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KatalonContact3@gmail.com (Business)'])[1]/preceding::a[1]</value>
      <webElementGuid>2b583938-6bca-49bd-a37a-8402b65cb914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[4]/preceding::a[2]</value>
      <webElementGuid>5f73ec7a-1ccb-4530-a4ba-9bdbb76679a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[27]</value>
      <webElementGuid>3dac1d39-4585-4666-b28d-123fe1ae765b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/div/a</value>
      <webElementGuid>d871716d-673d-46e3-8975-024bd3c0cf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                            New Email
                                        ' or . = '
                                            New Email
                                        ')]</value>
      <webElementGuid>6d0d2796-ec8f-41e7-adb2-e41e21e7dfee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
