<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailType_dropDown</name>
   <tag></tag>
   <elementGuidId>6813a25a-1c96-466e-9b14-b09e6702c0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailTypeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EmailTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>653559eb-ab99-43ac-8239-0171d8c8baa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tighter-select</value>
      <webElementGuid>5e2138f6-1916-4e54-b767-e01b63f5e6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailTypeId</value>
      <webElementGuid>564b70bb-7838-4b4f-b447-fa8d6a2deb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailTypeId</value>
      <webElementGuid>cd97383e-51d3-4728-8f80-a0226d61e72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select
Office
Personal
Other
Business
Business Contact
</value>
      <webElementGuid>edcdb1a0-6539-40cc-ac1b-ba0b7737fbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailTypeId&quot;)</value>
      <webElementGuid>c87bf7e5-1dbb-4533-9ee4-04756f44dffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EmailTypeId']</value>
      <webElementGuid>dea26cd1-6066-4e03-a245-8a508317c5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table/tbody/tr[2]/td/div/div[2]/select</value>
      <webElementGuid>1c9064ce-29ec-4789-b074-a1e605684103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Type'])[1]/following::select[1]</value>
      <webElementGuid>1f59ff37-0345-4750-8c22-4a5492778b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::select[1]</value>
      <webElementGuid>e23e1ad8-a62c-4385-b6e0-019185873b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/select</value>
      <webElementGuid>77d89584-3817-4b94-9c67-ae1d3a23036f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EmailTypeId' and @name = 'EmailTypeId' and (text() = 'Select
Office
Personal
Other
Business
Business Contact
' or . = 'Select
Office
Personal
Other
Business
Business Contact
')]</value>
      <webElementGuid>169467ae-2f31-4d49-b985-1c97db571349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
