<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropoffTIme_textBox</name>
   <tag></tag>
   <elementGuidId>a1803586-e633-4715-b3c1-e23bcb855ed6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4e6dc16-4eff-49b4-8b25-37da99e3dfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11:50 AM</value>
      <webElementGuid>c91e9133-e73c-4f5b-8278-a7fce73c4156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a48bc52f-9a03-4367-a465-69cdacba2ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d1d8b95-958f-4c4c-ba34-043d997bb925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-formfiled-dropdown target-executive-time</value>
      <webElementGuid>dc65ab36-251b-4718-bec0-421d5840796b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f7bfb87-f869-4c37-a44b-eafb3e1c85d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffTime</value>
      <webElementGuid>771ad2f6-85ee-46ab-8c8c-196f4d397ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffTime</value>
      <webElementGuid>dba729e4-3e2a-4b32-a0b8-802c5414af8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffTime&quot;)</value>
      <webElementGuid>03878f76-4aa3-4b4e-ae35-c841042da050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffTime']</value>
      <webElementGuid>07430b3a-8606-44ba-8591-8ea2151ebfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-dropoffform']/div/div/div[7]/input</value>
      <webElementGuid>d2585260-cfbd-4fef-bc78-9699d9dc5da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div[7]/input</value>
      <webElementGuid>9a17ac01-c2b3-4d0a-aff9-10a09d721921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffTime' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffTime']</value>
      <webElementGuid>3d771b48-5fd4-47ce-b4a5-fe413c4827cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
