<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>state_textBox</name>
   <tag></tag>
   <elementGuidId>f648847a-cd94-4b64-9bae-7ffe24739fa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38d9ca48-a1a2-4f3b-89f6-a1c86c27fd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1191507-e8c1-452d-b1fa-420630a00e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8fc71a3b-1bf6-4322-9779-fadb408a91bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address dropoff-address ui-autocomplete-input</value>
      <webElementGuid>233a6f18-9cfe-4e66-aa85-d88dcaf35ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4edb9da3-58ca-4c6b-b893-ebf9279eed83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a71534f0-9d95-4f75-80ea-09daa3285aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field State must be a string or array type with a maximum length of '2'.</value>
      <webElementGuid>8fc24240-6a72-435f-b9c1-757c28741d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8830b3c2-394a-458e-96ae-ce46281009e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The State field is required.</value>
      <webElementGuid>2cc5fc37-8ade-4a5f-816e-1a0b4add9a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode</value>
      <webElementGuid>1e61a0e4-f208-4a91-92cf-77496b4938e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a767f51a-a6ae-4a09-95e9-1f3a57e178eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.State.StateCode</value>
      <webElementGuid>133e0e35-7433-4476-a42e-38ac0079370d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode&quot;)</value>
      <webElementGuid>25ab9507-8001-4d4e-bfb6-b6a6ee4145f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode']</value>
      <webElementGuid>ef4f8d45-c55e-4e9c-af5f-4d64436c6f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-dropoffform']/div/div/div[4]/input</value>
      <webElementGuid>dddb77a6-3317-4a24-9915-60ad233bce90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div[4]/input</value>
      <webElementGuid>e4436dce-055c-4caf-b6ea-e9eab177eb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_State_StateCode' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.State.StateCode']</value>
      <webElementGuid>25449005-179d-4574-84a9-f91847f9a424</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
