<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>updateAssignment_button</name>
   <tag></tag>
   <elementGuidId>e2a5262a-6b89-4bd2-bb66-3389fb7702a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Update Assignment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-flight-plan.target-flight-plan-assigned-to-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1eaf2a9-c8b9-4dd4-8ce5-8409db561b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ae2fcff-4844-4458-8d0b-1362736d59aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update Assignment</value>
      <webElementGuid>0ccbad0d-e82f-47e8-9422-01be16c65f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-flight-plan-assigned-to-btn</value>
      <webElementGuid>bc39c908-9797-40e0-a580-4d61eec21632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-aircraft-list request-list&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/input[@class=&quot;btn btn-primary btn-flight-plan target-flight-plan-assigned-to-btn&quot;]</value>
      <webElementGuid>eb2b4a9c-5e4d-43fc-b082-064cf683257e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Update Assignment']</value>
      <webElementGuid>78d8bfc3-3f1f-49b8-9e89-f4443402650e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[2]/div/div[3]/input</value>
      <webElementGuid>6a8c95a7-0c5e-4484-8bc1-86c5d271959a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/input</value>
      <webElementGuid>2442e566-c5d9-461b-80d9-dd7330b1c338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>9724a5e5-a2be-4d20-88c7-7b5c04dbbdc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
