<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yes_checkBox</name>
   <tag></tag>
   <elementGuidId>a2e50548-4131-4976-ae1c-bd60543f3d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsDayOff']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IsDayOff</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a10e1a70-fcae-4ddb-8163-a9c1e4dd63b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bdbcbe38-4819-4f1b-a511-b2328efdaf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is-day-off day-off-yes</value>
      <webElementGuid>0752d628-f1e0-4610-b275-5ba51d3e8bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>914372c8-6fd0-40c9-88e1-39ae1e98aaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca2dc5bf-831b-4a7e-8180-3da355727fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Please answer First Question  - Is this your day off?</value>
      <webElementGuid>0d7287d2-c2c6-4711-9454-88111c4e642f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsDayOff</value>
      <webElementGuid>7328771b-088d-4f91-8001-50be8106a5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsDayOff</value>
      <webElementGuid>1bb4aba2-a4c6-4953-9fb6-934850ff8184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee-health-declaration-form-0&quot;)/div[4]/div[@class=&quot;row health-form-row ehf-day-off-row&quot;]/div[@class=&quot;col-xs-2 form-not-submited-0&quot;]/input[@id=&quot;IsDayOff&quot;]</value>
      <webElementGuid>ad3fa9fa-e02a-47c8-835f-c8f58e637ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsDayOff']</value>
      <webElementGuid>c8f97920-6015-4f17-8cad-beb91a861c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='employee-health-declaration-form-0']/div[4]/div/div[2]/input</value>
      <webElementGuid>af95a7d7-54e9-4d12-96d0-1f224e3c876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b1f44959-7ebd-4585-a5ba-9da7854b88ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'IsDayOff' and @name = 'IsDayOff']</value>
      <webElementGuid>a3ba07f7-c8c6-47fe-aa05-ea9aeefbadba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
