<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pickUpInstructions_textBox</name>
   <tag></tag>
   <elementGuidId>cbdd7229-05ba-4147-8b5f-e70c664d8d6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupInstructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupInstructions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>491a00db-1647-46c0-b8d0-ae339df086ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f4dc301-dcbb-42ea-bb0b-a0591a1a3440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c8bed5a-63d8-4c91-b9f4-c5bd680e2749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupInstructions</value>
      <webElementGuid>41eede2d-eb2c-421b-92a2-6a8a50806b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.ExecutivePickupInstructions</value>
      <webElementGuid>1450b349-eb26-4b25-b82e-5b1e19c12503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupInstructions&quot;)</value>
      <webElementGuid>86bcc085-2f32-497c-8ce1-27b3df4c2aeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupInstructions']</value>
      <webElementGuid>078fc95e-a55d-47ae-a413-0868e8858b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-pickupform']/div/textarea</value>
      <webElementGuid>6534d557-3134-48f2-8e1a-63c02fe6d36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/textarea</value>
      <webElementGuid>8e037e17-2315-4a71-ad68-4f574b2af097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'FlightPlan_Legs_0__ActiveConciergeOrder_ExecutivePickupInstructions' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.ExecutivePickupInstructions']</value>
      <webElementGuid>4ba304b1-02b6-4358-a013-095b1354f517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
