<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateLeg2_textBox</name>
   <tag></tag>
   <elementGuidId>96bf374e-0c16-4264-ae2e-9889843c8b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_OriginDate2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_OriginDate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b6bb70b-ec1c-4ce2-ac2e-d03fafa33ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-date-picker black-tighter-input target-flight-plan-input-origin-date hasDatepicker</value>
      <webElementGuid>f8a2c9ee-537e-415b-992b-a5a8c629feea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a1b9d7fe-c8c4-4796-b2c1-e9a8e7dd889f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_OriginDate2</value>
      <webElementGuid>28bf1e3d-cefe-456b-89c8-9ec9c26b64d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5b42490a-2996-458d-9c05-cae36c898940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_OriginDate2</value>
      <webElementGuid>6d59a39c-1c34-4fc3-893b-c7a446b8d7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>74f0a9d6-7511-4206-9225-96c678a70f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>921e4d22-7819-490f-a750-59f5eaaf7c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>05/02/2023</value>
      <webElementGuid>bdb7f5d9-fa25-4f0f-8d65-c0531b536cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_OriginDate2&quot;)</value>
      <webElementGuid>754b9ca0-0041-4361-b9e4-0af4bf5d17c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_OriginDate2']</value>
      <webElementGuid>b3302fcc-6c60-478b-b4c6-8d8c2dc70be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[3]/div[4]/input</value>
      <webElementGuid>4290a041-6a02-4aba-8aa5-0f1489b42f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div[3]/div[4]/input</value>
      <webElementGuid>b4033f1e-bea3-4452-b74f-05a1df6151bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leg_OriginDate2' and @name = 'leg_OriginDate2' and @type = 'text']</value>
      <webElementGuid>c41680b7-f663-41bf-93bf-7767d9f4af53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
