<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateLeg4_textBox</name>
   <tag></tag>
   <elementGuidId>49c34140-cd93-4599-ad84-af6aa23202ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_OriginDate4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_OriginDate4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41c17641-dc75-407f-b181-02a3c772d37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-date-picker black-tighter-input target-flight-plan-input-origin-date hasDatepicker</value>
      <webElementGuid>94c14d22-1d88-4881-ada0-51e4c47fcbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>431b6a64-643a-4014-941c-b21af6bdca38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_OriginDate4</value>
      <webElementGuid>566dfccf-3e3b-4d5b-a644-3d821ea3505f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e24e1798-9471-4470-a320-e1603b8e2db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_OriginDate4</value>
      <webElementGuid>6a0844f9-ba5a-4474-83fc-517d21ef6793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>83d69e1a-59ef-4c12-bc28-d1903164fa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fff564c8-c4e7-471a-bd48-2035dd59cd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>05/02/2023</value>
      <webElementGuid>92800d1a-fdb9-4a3a-9b1c-98cba7be6468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_OriginDate4&quot;)</value>
      <webElementGuid>d75474da-c870-4c55-a4cc-c1761b52ac8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_OriginDate4']</value>
      <webElementGuid>5ed847fb-9a92-4211-8ae5-cf64fffed6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[5]/div[4]/input</value>
      <webElementGuid>b1926bcd-5f9a-4da2-be17-80c0952f2bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div[5]/div[4]/input</value>
      <webElementGuid>7143bed8-5845-4fb1-ad0a-b3819225e430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leg_OriginDate4' and @name = 'leg_OriginDate4' and @type = 'text']</value>
      <webElementGuid>7ce52250-9ab8-4087-a618-c07e6082f666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
