<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paxLeg2_textBox</name>
   <tag></tag>
   <elementGuidId>9f7f49a1-c0c3-4516-84de-7a51f703a56c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_NumberOfPax2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_NumberOfPax2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33781649-fdca-4f90-9169-7e1be40b0519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tighter-input maskNumber target-flight-plan-input-number-pax</value>
      <webElementGuid>66a6b923-4bae-4418-aac8-4e63d3eb4be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d01fe556-61a3-4172-99dc-69ac7f71ab3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v-max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2e799dfa-a666-41e9-a1c3-2b04cdf92d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1bfde04-e82a-4b4b-b983-00157bc9d26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_NumberOfPax2</value>
      <webElementGuid>75b60a07-cc8f-4dec-a6ef-f291d57c841d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b03829a0-9a79-448a-ae62-24394e743e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_NumberOfPax2</value>
      <webElementGuid>57ffc917-4c3b-490d-a5a8-978da5164a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a7303668-8486-4f6e-9d1b-0780428ea965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0c04df6-b426-4a45-bfe3-4fd84141bae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>450218f0-b70c-4672-8145-f9d5afe635cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_NumberOfPax2&quot;)</value>
      <webElementGuid>19d6480a-7bcb-4ece-bafe-f3c4744964eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_NumberOfPax2']</value>
      <webElementGuid>3df67d09-95e3-41c7-b9de-88e9267736ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[3]/div[5]/input</value>
      <webElementGuid>63804093-b3b8-4775-8d1b-07c61de9e0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[5]/input</value>
      <webElementGuid>eaaeb156-9de0-4477-848e-c46758314f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leg_NumberOfPax2' and @name = 'leg_NumberOfPax2' and @type = 'text']</value>
      <webElementGuid>7c3a4ad6-a326-4cdc-b4f0-059c1f307844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
