<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paxLeg4_textBox</name>
   <tag></tag>
   <elementGuidId>18d2ca86-1ec0-4aab-872e-b0e9b53062e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_NumberOfPax4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_NumberOfPax4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a71eb36-0deb-4c53-9996-093a972714bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tighter-input maskNumber target-flight-plan-input-number-pax</value>
      <webElementGuid>db962742-8b19-44e9-a91a-ea9d2009102d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>26a205bb-19a5-448d-ab5e-5ab49c08c5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v-max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>30e35b58-264a-40f3-9506-5a5c0bc2f7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f51e9db3-57d6-4983-b24e-e05901835309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_NumberOfPax4</value>
      <webElementGuid>0b715604-c357-4725-b595-cbdcef24623a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>420eda32-804f-489a-a32c-eaa6c782e67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_NumberOfPax4</value>
      <webElementGuid>a6c6aa96-592a-4232-9b40-ccd7714dd03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b54562f9-4300-4e5e-9096-0af2bd934bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10d8fcd9-12bf-4528-9b29-47dae6d2f318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d810a69-2509-4036-83f6-a539b9a92e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_NumberOfPax4&quot;)</value>
      <webElementGuid>00625718-0172-4ea3-8eea-4403a762a61e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_NumberOfPax4']</value>
      <webElementGuid>a58b3ce7-7e97-48ca-9def-6eea1c997264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[5]/div[5]/input</value>
      <webElementGuid>9ecc16ac-db20-46fc-8ca0-ae9acf73af18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div[5]/input</value>
      <webElementGuid>de1c1b3f-ecbe-424c-9fa9-07f4c367dcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leg_NumberOfPax4' and @name = 'leg_NumberOfPax4' and @type = 'text']</value>
      <webElementGuid>60476a93-886c-462d-b138-a2214c709f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
