<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timeLeg2_textBox</name>
   <tag></tag>
   <elementGuidId>88ff33aa-db88-4c44-bd36-5611b16ca857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_OriginHour2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_OriginHour2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a3453ac-df4c-406c-a3e9-a8b2682f2c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-time-picker black-tighter-input target-flight-plan-input-origin-time</value>
      <webElementGuid>68fbe815-a634-4a69-86aa-6082c25ae8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>09b7c6b8-e0d1-416c-98a1-23f96ebcea25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_OriginHour2</value>
      <webElementGuid>a27ce579-3e02-4913-966e-7c8cc3a83d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f6208ace-34b4-4f95-9e75-bbcfc737115a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_OriginHour2</value>
      <webElementGuid>6c29477a-a63c-421d-87b7-5727b4372059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>474f6e9f-381f-4b87-8fc7-d25e6a751d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cdb02c9-e0f6-47ff-82fe-4af2d48c9fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>12:30</value>
      <webElementGuid>7cc546c6-b1bc-4e44-90fb-465a6db72501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_OriginHour2&quot;)</value>
      <webElementGuid>c13db735-173a-489c-8209-e265989694e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_OriginHour2']</value>
      <webElementGuid>80f8051d-e308-47fb-97b3-6c15b2aab5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[3]/div[4]/input[2]</value>
      <webElementGuid>6302c7a8-5844-46d5-a60d-3a224f38a941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/input[2]</value>
      <webElementGuid>5def40e1-7539-4b9e-9b2a-d956b1d56bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leg_OriginHour2' and @name = 'leg_OriginHour2' and @type = 'text']</value>
      <webElementGuid>21b1f5a1-25e5-49ed-b8b7-fdfa502e065d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
