<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toLeg2_textBox</name>
   <tag></tag>
   <elementGuidId>4cd7309e-e3ca-4797-8086-4c49afca4ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_AirportDestinationIdent2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_AirportDestinationIdent2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5e3d2b3-a8ee-4cca-8197-9cdb003765ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input target-flight-plan-input-destination-airport ui-autocomplete-input</value>
      <webElementGuid>fdd0593d-2a9a-4513-9f53-798af5e4841f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4b8e8027-0b8b-425f-a48b-3c9c90b7da46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_AirportDestinationIdent2</value>
      <webElementGuid>c079aec6-6587-4b29-9825-33e5b80487f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_AirportDestinationIdent2</value>
      <webElementGuid>9b344d13-0e6c-4511-abf7-27601db82f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>2e5e9005-96d5-4bc7-9762-a18665a772ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e36a522-7119-4b4a-a6d7-61124a6d873b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e20d40ce-e743-4b90-a166-680833f772ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_AirportDestinationIdent2&quot;)</value>
      <webElementGuid>00f1dbb4-8e70-4263-82be-e2a96a6239e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_AirportDestinationIdent2']</value>
      <webElementGuid>03f0ae09-d9dd-40f2-a4b3-4e1863c4cc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>fedafbc1-6c11-429c-94e4-f4aa0591a353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>d5cf6d60-5a1b-419d-a911-dbf67baa1958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'leg_AirportDestinationIdent2' and @name = 'leg_AirportDestinationIdent2' and @type = 'text']</value>
      <webElementGuid>20d8fa18-703b-48b3-979a-f2e839538c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
