<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>updateFlightPlan_button</name>
   <tag></tag>
   <elementGuidId>910e963e-273b-4ad7-be30-3a27a70882a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Update Flight Plan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.btn-flight-plan.target-flight-plan-update-button-cost-breakdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4edadb47-8135-48d7-902c-0f613d97895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3cccb1c1-64d8-4fbb-a17b-68f17a74ea86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-flight-plan-update-button-cost-breakdown</value>
      <webElementGuid>28ea3e00-99fa-4fca-9541-d79ba8f63852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update Flight Plan</value>
      <webElementGuid>5643dfc0-fcf9-4975-bfbe-b68023a95988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-input&quot;]/div[@class=&quot;row ams-itinerary-row&quot;]/div[@class=&quot;col-xs-3 text-right&quot;]/input[@class=&quot;btn btn-primary btn-flight-plan target-flight-plan-update-button-cost-breakdown&quot;]</value>
      <webElementGuid>9aa43df8-aac4-49c0-8592-716795c51178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Update Flight Plan']</value>
      <webElementGuid>8308613d-9d8e-477a-98d2-c7fec96765e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>fa666df9-8822-4b88-9fc4-e54df4aee2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>a3751e0e-817a-473d-8f15-a5bd0745d106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>3c8bb642-de81-4f97-ad5f-fb377cc2ec63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
