<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>argusGold_checkBox</name>
   <tag></tag>
   <elementGuidId>bdceaa0e-ba56-453c-918e-560eac42fa5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > #CheckASR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='CheckASR'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b774f19f-fd98-4f7b-ab90-9f54f5d805b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-safety-check</value>
      <webElementGuid>83c56553-6e8b-485e-a562-67ea0d9df88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-avg-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0a8d2bda-658a-4192-98d9-581dccf1ef14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-avs-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f7875dbf-f47e-4f3d-a324-74ff16b2dccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CheckASR</value>
      <webElementGuid>a1d759bc-323d-4df8-addc-da07e151bf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckASR</value>
      <webElementGuid>b92d2dfe-d072-4bdc-9dc3-277322472169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0cf8a501-39f9-41cb-a7cb-423a8d15e5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>df0b517a-04b5-4e4a-a126-91c14a5189da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Profile&quot;)/div[3]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-2&quot;]/div[3]/input[@id=&quot;CheckASR&quot;]</value>
      <webElementGuid>a4d9dff6-4992-485b-9cd5-d9b1eb9215b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='CheckASR'])[3]</value>
      <webElementGuid>666cfca0-c355-460c-9f74-37047b6bfead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div[3]/div[2]/div[2]/div/div[3]/input</value>
      <webElementGuid>01aaa0ec-0d83-4749-b4fb-b60202ea515a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d7a1b451-cba8-4724-8fe7-002e67866c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CheckASR' and @name = 'CheckASR' and @type = 'checkbox']</value>
      <webElementGuid>5d2c3a94-0030-47a1-a783-8563bf384ab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
