<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bajSafety_checkBox</name>
   <tag></tag>
   <elementGuidId>ea4d2d2d-4abc-41ea-8b91-49b7362a5db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='CheckASR'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b8fd3f5-6559-4e6d-8e33-a048c51a5371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-safety-check</value>
      <webElementGuid>6aeff7e8-09f4-456f-a493-d6dde14b29ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-avg-id</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>728c0552-f123-40cf-aee8-a3439a1f8ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-avs-id</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>dd05a828-fd89-49ff-aa5c-598e9df819e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CheckASR</value>
      <webElementGuid>5f734ebf-255f-4ec7-91c1-906afdc2361a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CheckASR</value>
      <webElementGuid>0cb9c6bc-3d52-4768-b7bd-815859cfb87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2f40d138-bd7e-477d-82df-dbd62e2fd5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03081674-f235-4ab5-ba40-48abe18a70ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Profile&quot;)/div[3]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-2&quot;]/div[1]/input[@id=&quot;CheckASR&quot;]</value>
      <webElementGuid>aa3f56ed-6053-4417-a8bd-47b1200b08c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='CheckASR'])[10]</value>
      <webElementGuid>47767848-4cff-4799-a0b5-32f991549049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div[3]/div[2]/div[2]/div[5]/div/input</value>
      <webElementGuid>e59f7519-3fed-4130-96f8-d7b9a509756f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>500f5247-c07a-4758-98cd-dbbbaf163e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CheckASR' and @name = 'CheckASR' and @type = 'checkbox']</value>
      <webElementGuid>2b468319-0915-4134-9836-feca8df234dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
