<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dba_textBox</name>
   <tag></tag>
   <elementGuidId>4770db9e-855e-4491-9723-ebb4e7f4271f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operator_DBA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Operator_DBA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>914e038a-b2e8-4857-b8c0-f3f6f83de185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input</value>
      <webElementGuid>255f3270-33e7-430f-8d36-3f9a326d4039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56a190fc-4dda-46da-9b67-fd9e2a140dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Operator_DBA</value>
      <webElementGuid>65254c4e-02a0-43e3-8db2-e30252c9cb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Operator.DBA</value>
      <webElementGuid>6ef75b3d-46f8-43a4-b90b-f10db596cf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operator_DBA&quot;)</value>
      <webElementGuid>14ec53bd-363e-4961-a36c-52746d13d6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Operator_DBA']</value>
      <webElementGuid>0d071532-a57b-43fd-8607-b8e8d3092de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Profile']/div/div[2]/div/div[4]/input</value>
      <webElementGuid>2d88cb1e-e01c-425f-8b51-64be0c880516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>0c4481ff-1fe1-416e-8f45-4dcbb7315740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Operator_DBA' and @name = 'Operator.DBA']</value>
      <webElementGuid>af4daf28-4c90-4269-81bf-9f4b1ee146f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
