<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_checkBox</name>
   <tag></tag>
   <elementGuidId>17b45603-0042-40a5-b05f-30eeb0d67db2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__FirearmsDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__FirearmsDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f0e9535-611a-4ab7-b74b-a161d3592cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-firearms-nonecheckbox</value>
      <webElementGuid>7d3a4444-10e2-4dca-9a67-4b75c9542485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b6dc857-6704-42f2-8293-71a83c93df6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FirearmsDescriptionNone field is required.</value>
      <webElementGuid>6e69f06a-bc43-4550-b001-f8a68a232f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__FirearmsDescriptionNone</value>
      <webElementGuid>7679f8dc-8fa6-464e-9098-8bb4174866a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].FirearmsDescriptionNone</value>
      <webElementGuid>3b19044e-21d0-4333-abe7-9356bdfe28cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cce9ff04-2418-4c9c-babc-bdf196577dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>feefd189-2083-4e91-8473-da440ed786bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__FirearmsDescriptionNone&quot;)</value>
      <webElementGuid>2da05136-4821-4b82-866c-c789e21303d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__FirearmsDescriptionNone']</value>
      <webElementGuid>7d644cdc-4d71-47c7-b990-2a2a06c29ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[3]/div/div/input)[2]</value>
      <webElementGuid>356fbbfc-774b-4288-9463-6dfc7a182638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>8e72eae0-0e85-400e-8437-197af7eca9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__FirearmsDescriptionNone' and @name = 'Legs[1].FirearmsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>bfee7b83-f3e1-45be-a637-831d3f98e0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
