<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_textArea</name>
   <tag></tag>
   <elementGuidId>f50a458b-245f-4625-84a4-b1201df82a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_1__FirearmsDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__FirearmsDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f1b15c26-3eff-4310-bfd6-e10cb60d308b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-firearms-description</value>
      <webElementGuid>1d6e67a7-23bb-4c88-a34b-5b263a366b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e2a9d8d7-656c-4c04-bed2-76c0528a6f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__FirearmsDescription</value>
      <webElementGuid>178f0a66-1467-4288-9cb6-484d943d4633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].FirearmsDescription</value>
      <webElementGuid>5e3ef4d2-98c4-4a13-b267-c4e21d8f6715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0af2f51c-0b80-422f-a950-bb958103fe24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__FirearmsDescription&quot;)</value>
      <webElementGuid>40e1e867-efab-4730-b76d-b249690e5666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_1__FirearmsDescription']</value>
      <webElementGuid>0392dae8-1492-4309-889b-4676748cfa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[5]/textarea)[2]</value>
      <webElementGuid>76b2c740-36cd-45d5-8d33-0fd6714e4f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div[2]/div[5]/textarea</value>
      <webElementGuid>78aac515-b5df-427e-a083-92c81a3a9c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_1__FirearmsDescription' and @name = 'Legs[1].FirearmsDescription']</value>
      <webElementGuid>1e6bd2ab-83a8-45c7-b9ca-ba356b7e2fe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
