<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pets_textArea</name>
   <tag></tag>
   <elementGuidId>ce063a6b-f231-470b-a05c-7832b7fb3a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_1__PetsDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__PetsDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9d59f307-06c2-4d3d-9a47-c92c3206c4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-pets-description</value>
      <webElementGuid>4bf17dbe-3b93-4c81-bddb-d155970e5e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>a566f9ff-a7ff-4369-8ec2-e75470c054b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__PetsDescription</value>
      <webElementGuid>f5bb7d7f-c6da-4b07-b603-00e55e5d48a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].PetsDescription</value>
      <webElementGuid>1a1605b0-f499-4e29-bad4-b11fe6119f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>54a29e04-a9e9-4eaa-ba15-54b39f4f658c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__PetsDescription&quot;)</value>
      <webElementGuid>e9fd7dfc-5c8e-4eec-8094-95119c9f7840</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_1__PetsDescription']</value>
      <webElementGuid>1d8cdf02-ce4d-4656-a2a1-a38c2c7a7ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[3]/div[5]/textarea)[2]</value>
      <webElementGuid>db55a925-8360-4ae3-94c9-f2ec5546a46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/div/div/div[3]/div[5]/textarea</value>
      <webElementGuid>53f5f80f-789a-41dc-892d-e8368277df08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_1__PetsDescription' and @name = 'Legs[1].PetsDescription']</value>
      <webElementGuid>4b156349-07a6-4d11-82d0-f0a3b3496078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
