<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>anniversaryDate_textBox</name>
   <tag></tag>
   <elementGuidId>e8a78905-2d77-4aa3-a63e-194942c130a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnniversaryDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AnniversaryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f366502-38b4-4b94-a6b0-8d358a7d81ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-label tight-input-margin black-tight-input target-date-picker target-client-account-save-form target-client-account-save-form-anniversary-date hasDatepicker</value>
      <webElementGuid>4e11bf19-416d-48cc-a72a-f1b6c3a828b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnniversaryDate</value>
      <webElementGuid>de988155-f376-4beb-b21b-356c0748888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnniversaryDate</value>
      <webElementGuid>177e6289-4ded-47d1-81b0-856c6b842dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c26b6f8-9591-46ab-9ae5-67335af69956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnniversaryDate&quot;)</value>
      <webElementGuid>e280c5e5-405c-4cc6-84a7-e8bf0efc6d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AnniversaryDate']</value>
      <webElementGuid>4b03bf57-9a04-4726-ab25-d241b46cc652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div/div/div/div[3]/div[5]/input</value>
      <webElementGuid>adaac9a8-f7af-41f9-a5b6-caa724769c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/input</value>
      <webElementGuid>a2382a22-b791-4fc4-83ed-2fcb42b339dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AnniversaryDate' and @name = 'AnniversaryDate' and @type = 'text']</value>
      <webElementGuid>4b0af102-19df-4d92-93be-7654cc5393e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
