<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_dropDown</name>
   <tag></tag>
   <elementGuidId>ad3da55e-af22-41e3-9ff1-7aae8d36b1d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.multiselect-selected-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccountInfo']/div/div/div/div/div[5]/div[2]/span/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c8ef1dc-7088-4db8-b2e9-9cb1202b9c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-selected-text</value>
      <webElementGuid>74c1af25-42d1-47be-92aa-1e0317f7f2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Email</value>
      <webElementGuid>cea6e790-ef60-4c93-8cd7-03aedbc1b7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfo&quot;)/div[@class=&quot;row target-account-detail&quot;]/div[@class=&quot;panel panel-default row-eq-height&quot;]/div[@class=&quot;panel-body target-habit&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-xs-12 row_margin_bottom&quot;]/div[@class=&quot;col-xs-4  target-ams-multi-select-container row_margin_bottom&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;multiselect dropdown-toggle btn btn-default&quot;]/span[@class=&quot;multiselect-selected-text&quot;]</value>
      <webElementGuid>c67cf573-b241-426b-856b-203fa7e8c0a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div/div/div/div[5]/div[2]/span/div/button/span</value>
      <webElementGuid>14dec62a-1be0-4ebc-bdc5-71ad44a4f841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::span[2]</value>
      <webElementGuid>698cc3cd-5182-4c45-b3ab-216ef1282f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone:'])[1]/following::span[3]</value>
      <webElementGuid>9092f475-c998-4be2-be25-5a1ee8a0818d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test+8@gmail.com'])[2]/preceding::span[1]</value>
      <webElementGuid>dc31f906-9e49-4539-8582-1c9f61545b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promotion:'])[1]/preceding::span[1]</value>
      <webElementGuid>80d0bdeb-2b97-43a6-8d4f-a83cc6612c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select Email']/parent::*</value>
      <webElementGuid>f4e23e71-abe8-4943-a3ba-902ed118f807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>4076ed50-5e8b-4c4b-8d73-bc96208a6b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select Email' or . = 'Select Email')]</value>
      <webElementGuid>60c4e232-6192-45de-86d6-af4fad3cc20a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
