<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_textBox</name>
   <tag></tag>
   <elementGuidId>40c317e4-c352-4929-84b0-0a7b8d1728df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BusinessTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BusinessTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>246bb231-a1a9-4c23-8978-103828728ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input tight-input-margin target-client-account-save-form</value>
      <webElementGuid>f6107b53-57ce-4ec9-86d0-ba69ed4bec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f7cf5a2-fa77-48c0-bff9-856b291688f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Business title is required</value>
      <webElementGuid>48aa355f-92e2-4a18-b596-22848de58b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BusinessTitle</value>
      <webElementGuid>6921f3fd-4b6b-477b-acab-131abe4fe674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BusinessTitle</value>
      <webElementGuid>bab241e0-6d71-49ab-b40b-c8e4b46d141d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6979f5ee-bb1f-4ee5-a155-0e037d44b1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BusinessTitle&quot;)</value>
      <webElementGuid>1691d3f9-6192-4458-9687-12b27afa9137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BusinessTitle']</value>
      <webElementGuid>12268340-1755-48aa-b401-db83a8ade92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div/div/div/div[3]/div[2]/input</value>
      <webElementGuid>ec29cb2a-4436-4906-bd28-d352ea416879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>44f9b4a6-a4f8-41f4-a99d-96b987d35064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BusinessTitle' and @name = 'BusinessTitle' and @type = 'text']</value>
      <webElementGuid>64224067-cafc-4b20-acd4-7edb7c5ffc88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
