<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>isPrivate_checkBox</name>
   <tag></tag>
   <elementGuidId>d4f69318-ce56-41eb-8ed6-c653c383ebbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsPrivate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsPrivate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e19ce7d-48b3-4ffc-a429-9fb3aa436637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ee61da8-1d9e-4b11-90e9-12ef2c240729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The IsPrivate field is required.</value>
      <webElementGuid>da0130a4-3af5-4f4b-86d0-436a573f60fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsPrivate</value>
      <webElementGuid>d3d456c6-07bb-40b5-a19b-4f0facd0b7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsPrivate</value>
      <webElementGuid>6625f54b-f66f-42e0-b4c8-d28e09030b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44885c81-8c5f-4f27-ab5c-a2d28b96f817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e01bc09-5449-4fbc-81ac-766247220cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsPrivate&quot;)</value>
      <webElementGuid>07c618a2-c413-49a8-b7e1-b75f476c1735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsPrivate']</value>
      <webElementGuid>bae04682-b96d-4b03-b5c8-fdc79d6fb021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table/tbody/tr[4]/td/input</value>
      <webElementGuid>6a5350fa-4c4c-41a5-a810-4e7f19889f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/input</value>
      <webElementGuid>8d09c89f-506f-4577-a971-bdf0e864ea90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsPrivate' and @name = 'IsPrivate' and @type = 'checkbox']</value>
      <webElementGuid>45a31ea6-ade5-451a-9fbb-c05212b39e0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
