<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lemonade_checkBox</name>
   <tag></tag>
   <elementGuidId>eeee6f7b-9a14-40a1-8a6e-90a39c10b4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Juices-options']/li[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>daca662f-dc11-49ec-be49-ffc40f571de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>JuicesLemonade</value>
      <webElementGuid>d92cb6e6-ab02-46c1-8f69-6bcf2bb65a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lemonade</value>
      <webElementGuid>4121621c-26f3-42f6-82ec-2001421ed919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Juices-options&quot;)/li[5]/label[1]</value>
      <webElementGuid>0ef8eae5-f5ab-4368-99a2-a2d127c22021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Juices-options']/li[5]/label</value>
      <webElementGuid>994fc839-f79c-42ff-b8ce-87716d8fe894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berry Juice'])[1]/following::label[1]</value>
      <webElementGuid>d481908a-87b6-4798-a6f0-3aca8d1123d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple Juice'])[1]/following::label[2]</value>
      <webElementGuid>cbcd258b-0de4-4290-b2ec-4008eca1345a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[8]/preceding::label[1]</value>
      <webElementGuid>c56b5919-bb47-4aa3-9070-db237e34a9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lemonade']/parent::*</value>
      <webElementGuid>58678f72-2505-4714-bde2-ac8ec6541617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[3]/ul/li[5]/label</value>
      <webElementGuid>54049b62-ccbf-46ba-9e71-bc97d7802796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Lemonade' or . = 'Lemonade')]</value>
      <webElementGuid>8e99813c-6c21-44ac-8814-f1e38001bdac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
