<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>orangeJuice_checkBox</name>
   <tag></tag>
   <elementGuidId>26331551-633b-45fb-a698-664add151c20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Juices-options']/li[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a3c34ed7-a149-45e1-878d-637adfe44d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>JuicesOrange Juice</value>
      <webElementGuid>4551727e-f6e3-4248-8eed-8f67cae6910c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Orange Juice</value>
      <webElementGuid>827610c6-51a8-42fa-88bf-85e1b4046837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Juices-options&quot;)/li[2]/label[1]</value>
      <webElementGuid>31f1c9ab-4578-4f06-8bc0-47369822ee01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Juices-options']/li[2]/label</value>
      <webElementGuid>2b2c5bdb-a07b-48fd-99c3-58c8fee70757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[20]/following::label[1]</value>
      <webElementGuid>25b41d4b-af28-49d4-ae03-37debda7ed0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[21]/following::label[1]</value>
      <webElementGuid>fe3e3acd-2572-43da-a912-352f2cff2b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apple Juice'])[1]/preceding::label[1]</value>
      <webElementGuid>1a152b4c-81eb-4c83-baab-e0c5923f6ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berry Juice'])[1]/preceding::label[2]</value>
      <webElementGuid>d22c8ed5-2379-4c10-a795-e413f358906a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Orange Juice']/parent::*</value>
      <webElementGuid>a171f5bc-5427-4fb0-8dc9-b6ff4e207685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4[3]/ul/li[2]/label</value>
      <webElementGuid>d1cd1f45-e5fd-4b4d-b94a-91c55f3a9ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Orange Juice' or . = 'Orange Juice')]</value>
      <webElementGuid>0bcbd068-6e29-44d0-92fd-0da11a910fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
