<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>note_textBox</name>
   <tag></tag>
   <elementGuidId>592a80aa-51ba-47ed-95cc-57dc1f023ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='FlightPlan_Note']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Note</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>504a23df-5859-436b-8349-09dc9eb6e4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input </value>
      <webElementGuid>95afb01c-c3cf-4415-9476-99f3bc289862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Note</value>
      <webElementGuid>7d7ac51c-1e30-4b5c-8e3d-bedea70d8492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Note</value>
      <webElementGuid>f6a52596-6a20-43d5-b192-b1b77d82f3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Note&quot;)</value>
      <webElementGuid>eb6658b7-fa88-4be4-b236-ccf173e6237d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='FlightPlan_Note']</value>
      <webElementGuid>437e8383-5dc4-4b69-86c1-787757d7c14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[3]/textarea</value>
      <webElementGuid>c9f38712-7a77-4c1d-90dd-0dd13198f903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>20a1e0b0-ef89-4a3c-8133-ea40b30b2a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'FlightPlan_Note' and @name = 'FlightPlan.Note']</value>
      <webElementGuid>5d699d8d-ba31-4d85-b207-ef10173a27e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
