<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departureDateLeg5_textBox</name>
   <tag></tag>
   <elementGuidId>8ad6274d-e120-485d-a83b-f46a99b1cda7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_OriginDate5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_OriginDate5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>639266cb-e241-4925-aef6-9dd16d6b0c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>69ab0d10-334d-4902-bc45-99dc08f883bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_OriginDate5</value>
      <webElementGuid>6d01d1c1-bfd1-4d56-8c12-f27c8081cf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_OriginDate5</value>
      <webElementGuid>7b1a2123-bef9-4537-b1d3-b0855f66ee2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7fe1dd86-e82f-4f2b-ae74-2231f0010c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg timepickerControl baj-input-depart-date target-date-picker target-baj-action-draw-trip target-baj-action-update-expanded-info</value>
      <webElementGuid>fbf8abc9-632b-4eba-940f-b61d62d801fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b9c5ce7b-0ef0-453a-9f72-a92968fc5016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b5866e8b-e33c-480f-bd7f-1250e26bdc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Depart Date</value>
      <webElementGuid>4782aa15-08c7-4ee3-8f83-aa1d3b09fe26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/30/2023</value>
      <webElementGuid>aad0d8e1-7c40-499b-a5a5-ae52b548b752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a34adcb7-dc02-4b6c-aa92-fc1386e63f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_OriginDate5&quot;)</value>
      <webElementGuid>ea62c328-cc24-4c7d-9343-afafe985e514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_OriginDate5']</value>
      <webElementGuid>8bdf2620-26ad-4c55-b713-1ddb7ee1d0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_5']/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>6e292b56-e1d5-4514-87e7-b5da074d4783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>4d0a8421-a68f-4a7b-a375-6c2b2889346b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_OriginDate5' and @name = 'leg_OriginDate5' and @placeholder = 'Depart Date']</value>
      <webElementGuid>680feb07-28ea-4e04-ab00-cdd57d2a1d87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
