<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departureDateLeg2_textBox</name>
   <tag></tag>
   <elementGuidId>0d1342ef-00ec-4644-8099-990542d154e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_OriginDate2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_OriginDate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92e0c43c-654b-41c0-ac3c-92765dab24f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d1d9409-c132-4240-b42b-523d108c00ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_OriginDate2</value>
      <webElementGuid>82318dbd-9c79-4b84-865d-1724adb038c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_OriginDate2</value>
      <webElementGuid>fda02325-67c3-4374-a319-660488e339e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>43a9399a-e9af-4b4e-b154-fc9496610feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg timepickerControl baj-input-depart-date target-date-picker target-baj-action-draw-trip target-baj-action-update-expanded-info</value>
      <webElementGuid>a1586bb1-1e68-40ea-a470-0757fbdc2e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9c8392e8-2fc5-472c-bb3d-ca0ddbd98447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>2480ad80-fc83-4607-bc12-5f9e28a4b4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Depart Date</value>
      <webElementGuid>331ca628-3462-453e-9175-e0f9497d93a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03/20/2023</value>
      <webElementGuid>2826800e-c619-4bbe-88ef-a9ab4bac5d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fe77a726-d9cd-4a16-8264-66c671483eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_OriginDate2&quot;)</value>
      <webElementGuid>b3c16721-0776-4c54-8f89-0074cb0dbc0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_OriginDate2']</value>
      <webElementGuid>bfd11dc5-ec7d-477b-9922-3ddf2b758d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_2']/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>4638bdf2-ef7c-4986-a80b-eee4c670e4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>8c9af8c9-902b-4fb9-b126-bc83340b7e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_OriginDate2' and @name = 'leg_OriginDate2' and @placeholder = 'Depart Date']</value>
      <webElementGuid>8db68578-130e-4762-b6d8-0c5348227825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
