<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>departureAirportLeg1_textBox</name>
   <tag></tag>
   <elementGuidId>2b61c24b-6aa5-4f0a-a88b-96459ad33829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_AirportOriginIdent1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_AirportOriginIdent1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b251b723-d173-442a-95ae-84e191f02c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f58528a-ca71-4a65-8c58-8c96a054d8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_AirportOriginIdent1</value>
      <webElementGuid>aa0508ee-eecd-4685-98f3-893351283c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_AirportOriginIdent1</value>
      <webElementGuid>20e78537-aad9-4194-a535-4c2a25c30086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>From</value>
      <webElementGuid>94fc7f86-1e01-4ab7-8fc5-291636c8ef30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg target-airport-entry airport-entry-style target-baj-origin-airport target-baj-action-update-expanded-info flight-search-airport-field baj-airport-input-hl ui-autocomplete-input</value>
      <webElementGuid>edf64ee9-7325-4749-bca5-d7e18c4a57c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ed1aff3b-de2f-47d7-a22a-78019e744dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>672ea883-9b9f-461a-ace0-6f639906a418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_AirportOriginIdent1&quot;)</value>
      <webElementGuid>3879893b-0dde-434e-99e6-38815608ea53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_AirportOriginIdent1']</value>
      <webElementGuid>49e887ed-73d5-458d-b722-5edf995b3ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_1']/div[2]/div/div/input[3]</value>
      <webElementGuid>8dd1c28d-8d83-407f-af6d-05ec44faa3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>0f720752-67c6-45c1-8036-109e1fccbd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_AirportOriginIdent1' and @name = 'leg_AirportOriginIdent1' and @placeholder = 'From']</value>
      <webElementGuid>cdf84ed1-f584-42e3-a037-08a16d48aab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
