<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numberOfPaxLeg4_textBox</name>
   <tag></tag>
   <elementGuidId>9bfbefe9-ba19-48e8-97f5-9773369bde44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_NumberOfPax4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_NumberOfPax4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6d726ca-f41b-48da-a40b-d8c09057e589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f07bf0d-d7c6-4708-9f3b-cf7f9c5bee6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_NumberOfPax4</value>
      <webElementGuid>f5266584-ff6c-4b07-9ceb-0b06e189ea08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_NumberOfPax4</value>
      <webElementGuid>f454b17f-21ad-4646-aea2-15331239d897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg target-number-pax maskNumber target-baj-action-draw-trip target-baj-action-update-expanded-info</value>
      <webElementGuid>63edbfb6-76f8-43ba-b6d6-17a34432b401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>51407a86-9b2c-4245-be0a-c23e286a77be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>87e61f89-2775-490c-93b7-4243274ce29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_v_max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>93f55af8-1e75-4c25-8817-4affd12988aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_v_min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ebc988b2-f88d-441c-b68b-837e4b67ba54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PAX</value>
      <webElementGuid>7480da30-cbc0-41e5-a884-54d9cddced89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f7524a7d-742e-4e8f-86f2-ded955df4240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>470c18db-e69f-4938-a61c-0739fbeac5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_NumberOfPax4&quot;)</value>
      <webElementGuid>3cbec57f-55a8-4b07-a4a5-daebbe5403cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_NumberOfPax4']</value>
      <webElementGuid>d7041ce7-f90d-4c97-b745-27a72f5dd01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_4']/div[3]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>0fcc97ff-907b-4298-8785-04b95e059130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>5827ccb4-49e4-4250-b43f-28228f1dca3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_NumberOfPax4' and @name = 'leg_NumberOfPax4' and @placeholder = 'PAX']</value>
      <webElementGuid>6f6d08b5-8e5f-4815-a4be-781c38b154b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
