<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>numberOfPaxLeg1_textBox</name>
   <tag></tag>
   <elementGuidId>486acd25-6ec5-45bb-a5f3-ee1aab9b1e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='leg_NumberOfPax1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#leg_NumberOfPax1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90fcf195-a7ca-4be9-8537-3328ad8fbb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdadab5e-08b3-4308-ae62-ccdb6545b45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leg_NumberOfPax1</value>
      <webElementGuid>2a41d68b-a666-4172-b773-bb9a76980131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>leg_NumberOfPax1</value>
      <webElementGuid>4a891312-3d37-4ec4-8ca8-8c02152d11b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control transparrentbg target-number-pax maskNumber target-baj-action-draw-trip target-baj-action-update-expanded-info</value>
      <webElementGuid>5dc5029f-e2d3-417c-a017-e1d6c2005b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2652ac30-357e-4bda-96ce-1538598d3a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>fb65d34e-1405-4e72-9158-d87d28ed003a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_v_max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>29b1aeda-f168-4b6d-b202-c3c30356b44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data_v_min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47824875-ff3a-4f25-959c-c8b192bda7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PAX</value>
      <webElementGuid>3380fa5a-bf89-4368-a4b6-cf52c43c115a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d1594fb3-a7ee-446c-83c4-9eee84362dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9d6550ce-e413-49bf-a3ff-da18284d9c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leg_NumberOfPax1&quot;)</value>
      <webElementGuid>413df6ef-899a-4c09-9fcd-337f3919aac1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='leg_NumberOfPax1']</value>
      <webElementGuid>6e4ed02d-b7b8-4689-8118-364ca5f866fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flightSearchFormRow_1']/div[3]/div[3]/div/div/div[2]/input</value>
      <webElementGuid>8529e01b-ae14-404b-bfc1-6f355364c916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/input</value>
      <webElementGuid>2a4dc005-45dd-4995-bb2e-618714eb252f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'leg_NumberOfPax1' and @name = 'leg_NumberOfPax1' and @placeholder = 'PAX']</value>
      <webElementGuid>88b372bd-78f3-4bd3-9840-1637899794a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
