<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchTrip_button</name>
   <tag></tag>
   <elementGuidId>32b2f04d-587b-4e27-b459-0d268bf3eead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.target-baj-find-planes.search-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3df2ff3c-7004-4848-b79e-e6a56575afe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7aa9f86-b15f-4f99-a391-ef030070ce25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aircraft-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb3d4734-b691-49cd-a8f6-3876efaae5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-baj-find-planes search-button</value>
      <webElementGuid>f5aaea4d-34f3-4c90-a828-411061a50ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;row no-padding&quot;]/div[@class=&quot;col-xs-12 text-center&quot;]/div[1]/div[@class=&quot;search-button-background-middle&quot;]/div[@class=&quot;search-button-container&quot;]/input[@class=&quot;target-baj-find-planes search-button&quot;]</value>
      <webElementGuid>9f1fcd5e-027b-4660-90a7-bdcef3c93da0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>5e418396-a7f7-4152-932a-3ab95dfba8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='FlightPlan']/div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>1ba246e8-c709-480f-a939-a124f980324b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/input</value>
      <webElementGuid>af160b40-4597-4d38-b0aa-da193acd93a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>c542076b-22ea-4c99-92b2-a7c7a79b4285</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
