<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savingGuestCancel_button</name>
   <tag></tag>
   <elementGuidId>906f750e-2f27-47dc-ae5b-85ba7167deda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Cancel'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propagatepassengermodal-leg-1-passenger-3 > div.modal-dialog > div.modal-content > div.modal-body > div.row > div.col-xs-4 > #Cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5501f44-8643-4607-a2dc-3505e549c81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn-small</value>
      <webElementGuid>a660a243-1e97-4778-a112-1dbd2868556e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61baeb25-06fc-466e-891b-60f71ea026fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>b9b99590-f8fc-4db4-b219-b77f1be2b632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>71f21202-b575-4b5c-98e4-1a5a9e84171d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propagatepassengermodal-leg-1-passenger-3&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/input[@id=&quot;Cancel&quot;]</value>
      <webElementGuid>aa758f6a-8d4c-4070-b076-961ff21f6a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Cancel'])[3]</value>
      <webElementGuid>79c0ba49-7103-465f-b173-b0ae9e10c670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propagatepassengermodal-leg-1-passenger-3']/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>478ceebb-cf28-4380-9357-73780d7a11ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>8cbcff10-0500-49f7-a4f6-e8a773c9050b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Cancel']</value>
      <webElementGuid>10e08eb7-239b-486b-8c6e-32b3e3ca3a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
