<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_textBox</name>
   <tag></tag>
   <elementGuidId>b165136e-a65e-4c12-9d00-652e6c82a915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_1__FirearmsDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__FirearmsDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>171977d3-2edd-4267-8737-f396829e117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-firearms-description</value>
      <webElementGuid>086fd98b-5c92-4f51-9779-45c0913950af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0d881df3-fc9b-4cf5-be75-2b5c92432f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__FirearmsDescription</value>
      <webElementGuid>ee316ccb-2d87-432a-83f8-2663944894d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].FirearmsDescription</value>
      <webElementGuid>224ea09e-151f-47c2-9f81-d41b102c7a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>dd92f957-b1fd-48eb-bff2-29df7b308a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__FirearmsDescription&quot;)</value>
      <webElementGuid>63f4fb2b-8cb5-484a-9066-4a7bb77090e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_1__FirearmsDescription']</value>
      <webElementGuid>5b84deaf-6ab5-46ab-92a9-48b7d6603734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[5]/textarea)[2]</value>
      <webElementGuid>f54d5ce0-fcf7-4763-b12c-762e926ded43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/div[2]/div[5]/textarea</value>
      <webElementGuid>780e6535-fb8f-4daa-99f6-cb6e7e1681b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_1__FirearmsDescription' and @name = 'Legs[1].FirearmsDescription']</value>
      <webElementGuid>4555b7f6-ba11-4729-ae21-da5383806e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
