<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_checkBox</name>
   <tag></tag>
   <elementGuidId>d8101f4e-f97a-49d7-941b-4a9797f2b251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__FirearmsDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__FirearmsDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5865fb9f-16c8-4ca1-b972-c3b73a8f8973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-firearms-nonecheckbox</value>
      <webElementGuid>0d2a0b44-5604-433d-b639-ce0382905731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ec5aca5-2443-4e1e-aeaf-f9825bb3f03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FirearmsDescriptionNone field is required.</value>
      <webElementGuid>101ac59e-9936-4fe6-b684-c1a3de1458f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__FirearmsDescriptionNone</value>
      <webElementGuid>8d2f1bca-7530-4929-9dd7-1aa3e823656e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].FirearmsDescriptionNone</value>
      <webElementGuid>4a27b78c-58d7-4043-851a-f51411927795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8fa6f796-0ce3-41ce-b0b1-85838738084e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25ae3b79-010d-4191-b1b5-28488ade704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__FirearmsDescriptionNone&quot;)</value>
      <webElementGuid>e2cd2654-8419-452f-be8c-cd70edc887f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__FirearmsDescriptionNone']</value>
      <webElementGuid>d9477aab-bbd5-40ca-a8e4-82d1f2ada582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[3]/div/div/input)[2]</value>
      <webElementGuid>80206a12-0736-455f-b83b-1fd09463b17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>a105dd09-5992-4b92-bbf7-d654585db5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__FirearmsDescriptionNone' and @name = 'Legs[1].FirearmsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>b9f411ea-6e17-4d01-a653-c5a1d8025b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
