<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateFilterColumn_closeButton</name>
   <tag></tag>
   <elementGuidId>46ec0d73-7bbf-44c5-b77c-5c3ef8aa4b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='one-loop-search']/fieldset/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>fieldset > div.loop-plan-filter > div.target-clear-loop-search.clear-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94c87994-ed19-4973-bd2a-8232c82ba583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-clear-loop-search  clear-icon</value>
      <webElementGuid>031883c9-38e8-4405-ae50-32431f027086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-search&quot;)/fieldset[1]/div[@class=&quot;loop-plan-filter&quot;]/div[@class=&quot;target-clear-loop-search  clear-icon&quot;]</value>
      <webElementGuid>92d18075-3dd0-4c14-b037-a67ab0d02e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-search']/fieldset/div/div</value>
      <webElementGuid>4852ff82-a8e0-480d-ae0c-8e0ca0a37f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div</value>
      <webElementGuid>78d70b35-1403-40c2-9168-4f060da44530</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
