<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dateTo_field</name>
   <tag></tag>
   <elementGuidId>c45050ec-faa9-4146-8f4a-fc62c681d80d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='DateTo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;DateTo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cda6da64-a727-453a-9b18-1796f179e5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73bff334-6a6b-45d3-9ff4-8d214656e9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-date date-picker target-filter-element target-one-loop-filter-to input-with-clear-button</value>
      <webElementGuid>989e6b53-25b2-472b-b8ff-7412d334802f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DateTo</value>
      <webElementGuid>7df9efc4-7902-4d30-a70b-1e95935ecd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>56959622-fa34-463f-acee-81ddf8502ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Date</value>
      <webElementGuid>d38a5e1b-0891-483f-9afd-1ec0ff64a244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-search&quot;)/fieldset[1]/div[@class=&quot;loop-plan-filter&quot;]/input[@class=&quot;input-date date-picker target-filter-element target-one-loop-filter-to input-with-clear-button&quot;]</value>
      <webElementGuid>0610284a-cba0-40a3-acba-0c0b7c75c4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='DateTo']</value>
      <webElementGuid>8730d02a-0e05-468f-ad79-602e99acd813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-search']/fieldset/div[3]/input</value>
      <webElementGuid>f77b1007-637f-4c69-ad55-878905299ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e692ec53-8e41-44ac-aefb-1616530ed998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DateTo' and @placeholder = 'Select Date']</value>
      <webElementGuid>390dc8d3-666d-4ac1-9499-88050e0af726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
