<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addPhone_button</name>
   <tag></tag>
   <elementGuidId>effef4b4-86c0-4e7c-9318-1933f05cc064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > input.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Add Phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c743123-acf9-40f4-9b34-840fb3a3bf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8207671-a97d-4175-880c-ef65d5a70f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08560c51-bdc1-4a4a-bff5-30a9b322e842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Operator.ContactPhoneSave();</value>
      <webElementGuid>4fe2fd51-f24b-4a58-9980-ee4bcd2acd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add Phone</value>
      <webElementGuid>20f38df0-149e-4b93-b60e-fa44206c7d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;b-ajax-wrapper&quot;]/table[3]/tbody[1]/tr[1]/td[1]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>6d6ec1a3-bd4a-4c58-b6a0-ba3bca48d34c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Add Phone']</value>
      <webElementGuid>d8c8dc9b-352e-4cb3-93c3-cb9da6a3d3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup']/div/div/table[3]/tbody/tr/td/input</value>
      <webElementGuid>34163c3b-b1bf-4a38-962f-e9b7430ce080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/input</value>
      <webElementGuid>55d3c997-9303-41c9-9feb-8e3ed69fee25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>a8a56258-437c-4b2b-9d08-9846a5e78d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
