<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newPhone_button</name>
   <tag></tag>
   <elementGuidId>2465625d-2d37-49cf-8040-d4e634a0158f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(3) > div.float-right > a.of-link-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='Operator.PopupContactPhone($(this));'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9a7d53b7-3fe8-4909-b041-a80780327145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>8751194a-dbc3-416c-9d37-6638d23b49e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Operator.PopupContactPhone($(this));</value>
      <webElementGuid>c20b3244-c2ac-4a87-be8d-049879e9668b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-id</name>
      <type>Main</type>
      <value>1037</value>
      <webElementGuid>4f61d5d9-7882-47b5-bf2a-388715163f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-contact-id</name>
      <type>Main</type>
      <value>12229</value>
      <webElementGuid>41f6c73f-b11a-40c9-8dd4-bfafd8737612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-phone-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e967278a-4f9f-4f50-86e1-42a51dd0bad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>of-link-black</value>
      <webElementGuid>654d53b0-fab0-461a-ad99-6b196af303a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            New Phone #
                                        </value>
      <webElementGuid>9a21d8fa-1ee8-466b-bfcd-2d6c0818341f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Contacts&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;ContactsDynamic&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;ContactsDynamic&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table ams-table black&quot;]/tbody[1]/tr[4]/td[3]/div[@class=&quot;float-right&quot;]/a[@class=&quot;of-link-black&quot;]</value>
      <webElementGuid>e357e620-6a39-4d48-8918-db3e13c85fa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='Operator.PopupContactPhone($(this));'])[6]</value>
      <webElementGuid>d98ac1d5-e542-4be6-b3f8-54059ebd3f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactsDynamic']/div[3]/table/tbody/tr[4]/td[3]/div/a</value>
      <webElementGuid>5367ac7c-0277-4089-9363-71a9491a5efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New Phone #')])[4]</value>
      <webElementGuid>6d7301d5-f2e5-4e74-94ce-a9d3395e66fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Address'])[4]/following::a[3]</value>
      <webElementGuid>93138a4c-99c7-4c53-ba54-4f2c01fe6a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Email'])[4]/preceding::a[2]</value>
      <webElementGuid>8844bb52-1711-44b4-b25d-7cbe7305206c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KatalonContact3@gmail.com (Business)'])[1]/preceding::a[3]</value>
      <webElementGuid>146d8ba9-dd38-4e02-bb0f-f887541e5db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[24]</value>
      <webElementGuid>486e8979-5434-4101-b30f-07a9eb2c4f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div/a</value>
      <webElementGuid>22c2b8c1-939d-4320-af49-2dc86c19afb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                            New Phone #
                                        ' or . = '
                                            New Phone #
                                        ')]</value>
      <webElementGuid>9e579ba2-15a2-4bc8-8082-5a70ca727a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
