<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu2</name>
   <tag></tag>
   <elementGuidId>fa5aebfe-604c-4680-9e74-e0ff6427661d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Leg_1 > div.panel-body.no-padding > div.col-xs-12.no-padding.no-margin > div.col-xs-12.col-md-4.catering-formfiled > label > span > button.target-menu-link.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e33e686-f0f8-4793-91e4-1b511d1320b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-menu-link menu-link</value>
      <webElementGuid>b193e5ec-ab7d-4ccf-9a7c-8a33bf2bbfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b5a8d502-1dca-4671-9884-eb7f5d752291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7784509-8377-43e4-8d60-3d934480aa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>a6a02ff5-1e51-40ce-b902-f55daef93558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Leg_1&quot;)/div[@class=&quot;panel-body no-padding&quot;]/div[@class=&quot;col-xs-12 no-padding no-margin&quot;]/div[@class=&quot;col-xs-12 col-md-4 catering-formfiled&quot;]/label[1]/span[1]/button[@class=&quot;target-menu-link menu-link&quot;]</value>
      <webElementGuid>0751877f-035b-4c49-8ddc-63450662309f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>531b2128-9b38-41e7-b866-f50a22f98cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg_1']/div/div/div/label/span/button</value>
      <webElementGuid>83624389-0061-40c9-8f05-960d8e4ac1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leg 2'])[2]/following::button[1]</value>
      <webElementGuid>dbb85921-5561-4348-9006-212a7c2580d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KLAX Pick Up Details'])[1]/preceding::button[1]</value>
      <webElementGuid>9e9e632b-e0bb-441d-a1fa-cc5f388d0fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[5]/preceding::button[1]</value>
      <webElementGuid>aeea12ed-ff84-416f-97e7-e6163b5a8485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/label/span/button</value>
      <webElementGuid>0b047651-e3be-417f-b698-501ef2b4aec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>4fd5bb63-f9c1-4a8a-a275-a454f97b4e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
