<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu1</name>
   <tag></tag>
   <elementGuidId>b1ee455e-85a0-423f-a2a7-cd8d55457128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.target-menu-link.menu-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e5da529f-6db8-40cf-b495-c814b3b067bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-menu-link menu-link</value>
      <webElementGuid>a8f1eb2e-c8f9-4dfb-94cc-4e745f1077d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>59776a45-3b75-489f-acc9-097c64d0e530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db27572a-5c5b-486d-994e-d5359ebdca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>5809756d-1347-468e-9946-9249c60303b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Leg_0&quot;)/div[@class=&quot;panel-body no-padding&quot;]/div[@class=&quot;col-xs-12 no-padding no-margin&quot;]/div[@class=&quot;col-xs-12 col-md-4 catering-formfiled&quot;]/label[1]/span[1]/button[@class=&quot;target-menu-link menu-link&quot;]</value>
      <webElementGuid>a5290766-7487-4440-9221-52bea170b894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>7670d88f-cc68-43f2-9e66-cbc22432f69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg_0']/div/div/div/label/span/button</value>
      <webElementGuid>1c59e2f2-32e0-4a63-8f28-62f036b24bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leg 1'])[2]/following::button[1]</value>
      <webElementGuid>0cafe399-3b0b-4da2-ad10-195c7f24b7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAPA Pick Up Details'])[1]/preceding::button[1]</value>
      <webElementGuid>063beb05-a7bb-45e3-a37a-1e05922070e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::button[1]</value>
      <webElementGuid>57e8980d-32fd-4fc2-83ad-d5de9ceb46bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>330824aa-f124-4e66-8f36-7d9ca3a66dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>50b5d91c-2bd2-4f6f-9c66-17d1453e5b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>59961458-006a-48c1-abe6-876f88d1d349</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
