<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CreateFlightPlan_button</name>
   <tag></tag>
   <elementGuidId>32a24a5b-dffa-4d7f-a6c3-b4c5924b45b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Create Flight Plan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.button-one-loop-small.target-create-flight-plan-from-loop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b928daa9-891d-41e6-993c-89f4848d8100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc7f23f5-89e2-4b2a-b2c5-6272b78ec9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-one-loop-small target-create-flight-plan-from-loop</value>
      <webElementGuid>7e79a3d3-337e-4eee-a9b8-3e8a0d7707d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Create Flight Plan</value>
      <webElementGuid>9d10fe8b-2802-4fc2-8e3e-368367563ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loop-id</name>
      <type>Main</type>
      <value>129</value>
      <webElementGuid>498921cc-9a64-4af0-b290-36262bda72d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loop-name</name>
      <type>Main</type>
      <value>(RVS) 11/24 - 11/27 - Due to sick pilot</value>
      <webElementGuid>c72f72bb-37a5-4eac-ae61-51862cc2dbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-loop-activated</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>373f6d0e-7455-48e8-bf1f-0fa83b2c862c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-detail&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[2]/div[2]/input[@class=&quot;button-one-loop-small target-create-flight-plan-from-loop&quot;]</value>
      <webElementGuid>87d865ae-22d3-49d2-9ab4-aa3d0e33a086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Create Flight Plan']</value>
      <webElementGuid>0a1c69ec-2035-4cb2-b140-4d30da33f6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-detail']/div/div/div[2]/div[2]/input[4]</value>
      <webElementGuid>60358dd3-6eb4-4607-a5c5-76df670b3515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[4]</value>
      <webElementGuid>410b62a3-09f0-4f9d-88f4-f713c6be29e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>aaa7131e-c5cf-4558-bdc7-7fe12b67ff77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
