<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropOffInstructions_textBox</name>
   <tag></tag>
   <elementGuidId>95fc7357-a4ab-44d7-aa93-f0ecf95f29a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffInstructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffInstructions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>09560f52-2b14-4a46-90be-5faef4d5f824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54820aec-0b3c-4c2b-b4ca-2393d7be1e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>986d1363-e9e8-45ef-b314-52119c5ce334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffInstructions</value>
      <webElementGuid>b465e28d-d258-48c0-9562-9d5f584ec595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[0].ActiveConciergeOrder.ExecutiveDropoffInstructions</value>
      <webElementGuid>84eca2f7-99bc-4af5-8af5-a04d95a72155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffInstructions&quot;)</value>
      <webElementGuid>5014fe21-84a6-444d-9599-2682ab4f20e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffInstructions']</value>
      <webElementGuid>4c8bf8c3-ba18-445e-bdd2-69525c2bb6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-0-dropoffform']/div/textarea</value>
      <webElementGuid>0d89f31d-d500-48e0-848d-a2ba57831b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/textarea</value>
      <webElementGuid>c4712e1e-c4ca-45c3-884a-a533b21bdd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'FlightPlan_Legs_0__ActiveConciergeOrder_ExecutiveDropoffInstructions' and @name = 'FlightPlan.Legs[0].ActiveConciergeOrder.ExecutiveDropoffInstructions']</value>
      <webElementGuid>155170a9-150f-4cf7-b493-4bf37cc830e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
