<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deskPhones_dropDownTab</name>
   <tag></tag>
   <elementGuidId>61e897fd-881f-43cf-a160-875677579baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[2]/nav/ul/li[8]/ul/li[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Desk Phones List&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ebd4b22-f251-4097-8189-ac3144f499e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/DeskPhoneList</value>
      <webElementGuid>6994e026-1537-4a1a-9c58-af53b8c7be3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Desk Phones List</value>
      <webElementGuid>aa443c00-4154-4fee-a063-02dd1a5f7f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desk Phones</value>
      <webElementGuid>b53eb610-95bf-4944-aa19-e8be03bbf537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;top_wrapper&quot;]/header[@id=&quot;header&quot;]/header[@id=&quot;header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row header flex-bottom&quot;]/div[@class=&quot;col-md-12&quot;]/nav[1]/ul[@class=&quot;navigation&quot;]/li[8]/ul[@class=&quot;show-sub-menu&quot;]/li[13]/a[1]</value>
      <webElementGuid>423f08a7-715e-4e96-a5f8-9be18a4aaaa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[2]/nav/ul/li[8]/ul/li[13]/a</value>
      <webElementGuid>bd65d7f4-30e4-44ca-9c2d-e7e4b0ca45a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Desk Phones')]</value>
      <webElementGuid>e2b2bdd7-bcc4-4fe5-a63a-96b022061048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Images'])[1]/following::a[1]</value>
      <webElementGuid>338ef701-845f-4804-b3d1-0fe364700897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peak Schedule'])[1]/following::a[2]</value>
      <webElementGuid>3f2a4d16-6154-49e5-b38f-80d88e880075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airport Manager'])[1]/preceding::a[1]</value>
      <webElementGuid>91635bb9-51de-416f-a481-a1b3f505b7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration Settings'])[1]/preceding::a[2]</value>
      <webElementGuid>133fe534-877d-4e14-8679-91b9a85391df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Desk Phones']/parent::*</value>
      <webElementGuid>29538718-6005-430c-b5f7-6e6d7ed4d4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/DeskPhoneList')]</value>
      <webElementGuid>596fea01-4dcc-415f-8d3f-72ee6442124f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/a</value>
      <webElementGuid>741a5763-190e-4320-9e18-7a2476c0a6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/DeskPhoneList' and @title = 'Desk Phones List' and (text() = 'Desk Phones' or . = 'Desk Phones')]</value>
      <webElementGuid>990e66a9-86fb-42b4-a34e-14bfd419c3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
