<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPageNumber_textBox</name>
   <tag></tag>
   <elementGuidId>d446bf95-6146-40dd-97b5-6b26ee58ed7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='1'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.target-current-page-new.target-pager-input.pager-page-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93503f96-93ac-412a-b93b-5ef2e8661309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-current-page-new target-pager-input pager-page-number</value>
      <webElementGuid>9eca65aa-d536-4359-bd1c-c0105cb4581b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>58372fa5-a4ff-4c91-94d2-07baa8860fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4d0c209-a6a5-469f-a4c7-812d4908466c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops&quot;)/div[2]/div[@class=&quot;float-right&quot;]/input[@class=&quot;target-current-page-new target-pager-input pager-page-number&quot;]</value>
      <webElementGuid>1ab6a77e-619c-43be-b347-6e834123e750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1'])[2]</value>
      <webElementGuid>536f2478-ada0-4af1-8f4a-0922c55ad18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='one-loop-saved-loops']/div[2]/div[2]/input[2]</value>
      <webElementGuid>74e40e4f-a118-4305-a8b0-3b5e09548d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>70cc3036-7ac9-4668-974d-031bd0bc4359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
