<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pdf_icon</name>
   <tag></tag>
   <elementGuidId>4500832d-a4dd-496a-80b6-3f3ca736bd1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-file-pdf.target-tripsheet-download.target-preview-pdf.cursor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6693d2d5-a758-4bbd-a853-55a36c277862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-file-pdf target-tripsheet-download target-preview-pdf cursor</value>
      <webElementGuid>4ad57e7d-1bd7-47ce-a1b8-9c80303822f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>2a4dfc6c-377b-48c4-a5a9-6b49c0fd414f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Preview Trip Sheet Pdf</value>
      <webElementGuid>0aeae20b-9848-464a-a158-0da6f084c2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flightplanid</name>
      <type>Main</type>
      <value>580423</value>
      <webElementGuid>2c31e2f6-9f12-47f0-934f-a7336652bbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan&quot;)/div[@class=&quot;content target-flight-plan-main&quot;]/div[@class=&quot;row ams-workflow-container&quot;]/div[@class=&quot;col-xs-8 target-flight-plan-trip-request-main&quot;]/div[@class=&quot;content target-flight-plan-trip-request-aircraft-list request-list&quot;]/div[@class=&quot;col-xs-12 download-ts-pdf-button&quot;]/i[@class=&quot;fa fa-file-pdf target-tripsheet-download target-preview-pdf cursor&quot;]</value>
      <webElementGuid>4fe86bcf-b800-40a8-ac32-f725262c2a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FlightPlan']/div/div/div[2]/div[2]/div[3]/i</value>
      <webElementGuid>bf607d80-7955-4956-ada9-49a574bf8c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>f51c2cbf-7626-4cf6-a301-241de316b517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Preview Trip Sheet Pdf']</value>
      <webElementGuid>f289490c-d515-4175-9735-310f5e313125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
