<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addFStop_icon</name>
   <tag></tag>
   <elementGuidId>02848748-b30a-4976-8120-f77d7644fc8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-leg_909766-fuel-stops-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2c546f4b-492b-45bc-821c-b3539a722391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus-circle target-expand-leg-fuel-stops cursor</value>
      <webElementGuid>0c2cf213-d883-406c-a145-024a71ec6acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>909766</value>
      <webElementGuid>6dd843ed-0871-4ebf-b638-758c2c57db34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-leg_909766-fuel-stops-info</value>
      <webElementGuid>52a49c44-a7a4-4631-bfdf-05b0c52ddd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-leg_909766-fuel-stops-info&quot;)</value>
      <webElementGuid>d05d39af-74e9-4ee1-b21f-8c335825d434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='target-leg_909766-fuel-stops-info']</value>
      <webElementGuid>fedaaf80-aba9-4392-b623-b2ced659ad63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909766']/div[5]/span/i</value>
      <webElementGuid>11b4deb6-fc5d-47af-929e-c374a2fa5f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>68752888-a10f-4d2b-bc73-4b3f07132095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'target-leg_909766-fuel-stops-info']</value>
      <webElementGuid>550fc043-5538-467a-8768-0a870cb96a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
