<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copy_icon</name>
   <tag></tag>
   <elementGuidId>cd420794-c156-4bbe-bb61-7abdc53a5f1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='target-flight-leg-id-909766']/div[8]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-copy.target-copy-this-leg.cursor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c8c5c7ef-62c7-4b91-b628-98d2648713b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-copy target-copy-this-leg cursor</value>
      <webElementGuid>eb19be70-10dc-4bb9-9158-98ddfa207ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Copy Leg</value>
      <webElementGuid>927f238b-de99-4adb-bbcf-77a5845c9b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-flightplan-id</name>
      <type>Main</type>
      <value>580511</value>
      <webElementGuid>8ae5dffd-8836-493f-9127-ddc5e65f89de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>909766</value>
      <webElementGuid>7f59bcfc-89de-495f-ac23-e7c22bea8c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-flight-leg-id-909766&quot;)/div[@class=&quot;col-xs-1&quot;]/i[@class=&quot;fa fa-copy target-copy-this-leg cursor&quot;]</value>
      <webElementGuid>3a582b8d-384e-49e8-af75-87baa7dacb04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909766']/div[8]/i</value>
      <webElementGuid>ddef671f-49cd-41bf-bab5-bfa798197e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/i</value>
      <webElementGuid>0cbf3a9a-09b1-425e-a0fc-9bfd6d016c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Copy Leg']</value>
      <webElementGuid>ab82fae4-3343-4219-90c4-82b41d213e65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
