<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>identFuelStopLeg1_textBox</name>
   <tag></tag>
   <elementGuidId>2d3cbec2-542d-44c4-bfa9-c7f20870a420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='target-stop-airport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-stop-airport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c4432979-8e7c-4517-aecd-b2844778ca5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6df13d69-92b2-42df-9a68-4f08cc54e220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-stop-airport</value>
      <webElementGuid>ce52918b-1acc-4c39-9e76-4d1bb4ab6eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry target-stop-airport-ident target-content-editable-stop ui-autocomplete-input</value>
      <webElementGuid>cd17febf-5cd4-4616-8f0e-273537515e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d175b207-f2cf-40b0-8458-94c991d5e046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-stop-airport&quot;)</value>
      <webElementGuid>475f250b-4972-4717-a9da-428dd56910e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='target-stop-airport']</value>
      <webElementGuid>e03d2848-cfb8-4426-9d09-99c76d9c6a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-leg-910154-fuel-stops-div']/table/tbody/tr/td[2]</value>
      <webElementGuid>0be0d6ae-350a-4a0f-9c54-1a84a724c519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]</value>
      <webElementGuid>af9b6082-32d3-41a7-a8d4-496c2ce82b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'target-stop-airport']</value>
      <webElementGuid>05fa281f-65a1-4a3b-bbf9-7606d84b4140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
