<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>time_textBox</name>
   <tag></tag>
   <elementGuidId>cdac6e02-19ec-4952-9c65-d2c50986b94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__OriginHour']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__OriginHour</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb671bcb-243c-4e48-9841-52cad55526e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-time-picker black-tighter-input target-flight-plan-input-origin-time form-control</value>
      <webElementGuid>83618397-7fab-41b5-9c86-c15a76457e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f48b5796-32d7-436b-a60a-95184587b750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Time field is required.</value>
      <webElementGuid>87dbe99c-38a2-489c-b8c5-abb6624be52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__OriginHour</value>
      <webElementGuid>269f7506-896c-4b56-b538-ed640660e0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].OriginHour</value>
      <webElementGuid>f46e1ae3-cc25-4567-9340-a1ef91f7eedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7883b010-58b9-4fcb-bc69-403135532bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>09:00</value>
      <webElementGuid>49f1727c-dc92-4127-94cc-f26b69237aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__OriginHour&quot;)</value>
      <webElementGuid>01777e7a-d04e-4c9d-a0d8-bd0b8981b2e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__OriginHour']</value>
      <webElementGuid>39e7cf8d-8844-4aea-a2ee-158856428730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909766']/div[7]/input</value>
      <webElementGuid>45c2d932-f321-49eb-a1dd-e7b627e57245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[7]/input</value>
      <webElementGuid>02425bd4-e78f-4436-8d41-528250424dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__OriginHour' and @name = 'Legs[0].OriginHour' and @type = 'text']</value>
      <webElementGuid>ee49db63-4e31-4f46-a0a2-0e11d411603e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
