<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>quotedAmount_textBox</name>
   <tag></tag>
   <elementGuidId>2ef2afe7-55c3-4cc2-bffa-9e81981c04d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='QuotedAmount'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909636 > #new-executive-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-7 > div.row > div.target-enter-quoted-amount > div.col-xs-12.target-div-overage-reason > div.target-quoted-amount-div > #QuotedAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3f654f1-e2e1-4c11-b713-baf00d927d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c18cc758-3002-4839-b662-3fd058014aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-budget</name>
      <type>Main</type>
      <value>150.0000</value>
      <webElementGuid>8cb74312-224e-4208-8efd-46bd4a31d5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>bf5e0565-2879-4d1a-90aa-0853cca1cd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>55a8fa35-6a41-4b9c-806b-54f56fc84e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-concierge-quoted-amount</value>
      <webElementGuid>85cbdb53-c9f1-4d65-b72a-6c533538d83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QuotedAmount</value>
      <webElementGuid>bb6dfba2-dc5b-4bdb-9a90-be29cba0f9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>QuotedAmount</value>
      <webElementGuid>9e7aaf2d-8cd9-4ccb-9245-9fd89db7fdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909636&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;target-enter-quoted-amount&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/input[@id=&quot;QuotedAmount&quot;]</value>
      <webElementGuid>10c4c84f-7cc8-47e8-a555-8543d77c4db3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='QuotedAmount'])[10]</value>
      <webElementGuid>1eac3a2f-7c05-4d70-8292-83c18057927a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[3]/div/div[10]/div/div/input)[2]</value>
      <webElementGuid>8771fc56-957d-4aee-bc2d-8472f82a12e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[10]/div/div/input</value>
      <webElementGuid>c6444a48-d8e2-493c-b39a-c637fcb1877c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'QuotedAmount' and @name = 'QuotedAmount']</value>
      <webElementGuid>d85f5098-121f-4491-b131-08281d02f94c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
