<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>month_dropDown</name>
   <tag></tag>
   <elementGuidId>de675cd9-06d8-400b-9eee-9a5ef3107add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_1__BirthDate_Month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__BirthDate_Month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d85258c7-9ea8-40e0-adec-f377eb44dabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control float-left target-birthdate-el target-pax-birthmonth</value>
      <webElementGuid>016dd9f2-7fea-4cac-9260-dd5de64bbf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d89afa2-da82-4b70-9ba9-44f37b4f5fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The BirthDate_Month field is required.</value>
      <webElementGuid>a60dbd5f-8978-4ff0-9b24-babd167531c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__BirthDate_Month</value>
      <webElementGuid>de5924ef-755a-40c6-8298-924ace804061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].BirthDate_Month</value>
      <webElementGuid>22cd67ab-4a50-4bdf-b4b1-d6701eea6d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            </value>
      <webElementGuid>2bfed89c-375d-4c7d-88c5-11f80694ce59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__BirthDate_Month&quot;)</value>
      <webElementGuid>f4bed6db-f27c-42c1-9d6b-0eaec82a073d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_1__BirthDate_Month']</value>
      <webElementGuid>f44a5ad2-2998-4e1c-aac9-8a263db384fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>5105cd38-0a39-42fa-8085-b0e9e9d83c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birth Date'])[2]/following::select[1]</value>
      <webElementGuid>6c94367c-4ca0-4674-8d3a-0df86a43fa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[2]/preceding::select[2]</value>
      <webElementGuid>62434860-296a-4575-870d-a007dbe0ef2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/select</value>
      <webElementGuid>61ed6d70-0832-41e3-83fb-389878d98c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_1__BirthDate_Month' and @name = 'Legs[0].Passengers[1].BirthDate_Month' and (text() = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ' or . = '
                                Month
                                        Jan
                                        Feb
                                        Mar
                                        Apr
                                        May
                                        Jun
                                        Jul
                                        Aug
                                        Sep
                                        Oct
                                        Nov
                                        Dec
                            ')]</value>
      <webElementGuid>b66e45e8-0014-4dea-aa39-39aad3535e60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
