<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savePassenger_button</name>
   <tag></tag>
   <elementGuidId>35dc9b54-9a96-465a-be90-870f300f2fdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Passenger'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.baj-btn.target-baj-results-button-save-passenger.l1p2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c323cbb9-1a9d-4b25-b341-3bf43c19802d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn target-baj-results-button-save-passenger l1p2</value>
      <webElementGuid>b4b9a363-bed8-4067-8041-387953b03826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-number</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>71b65fab-07b7-4d32-ace2-2545cae98def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-number</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>13f6d4da-6a23-4ada-9ba9-fce27d159de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-id</name>
      <type>Main</type>
      <value>1861836</value>
      <webElementGuid>4c8401ae-6765-41c4-9354-8648072a7403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-passenger-class</name>
      <type>Main</type>
      <value>l1p2</value>
      <webElementGuid>61570f7f-acc4-474d-b4fc-281f2972a8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-number-of-legs</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fafc1468-a90f-4fd9-9c50-ec9cc1762f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af28a0d8-662b-4edd-a6e2-8db208eea27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Passenger</value>
      <webElementGuid>4f359411-b5f4-4afb-b55a-dc694e9d7380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passengercontainer-leg-1-number-2&quot;)/div[@class=&quot;clearfix baj-results-pax-grid-box&quot;]/div[@class=&quot;save-passenger-container   no-margin&quot;]/div[@class=&quot;row clearfix&quot;]/div[@class=&quot;col-xs-12 text-center&quot;]/input[@class=&quot;baj-btn target-baj-results-button-save-passenger l1p2&quot;]</value>
      <webElementGuid>1a596609-7efa-4893-a95a-f9cce1614135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Passenger'])[2]</value>
      <webElementGuid>6e1cb2ea-2d28-4b5a-a621-200fd35752ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>efb6906f-9ad2-43ff-88b7-b9b7a1325b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>7be8417f-7dfc-4ea9-a448-667f29ee88a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>1a316067-0198-4e1f-9651-bddf866de03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
