<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>year_textBox</name>
   <tag></tag>
   <elementGuidId>9d787d71-bb56-4b79-8ddc-45a349e023de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_1__BirthDate_Year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_1__BirthDate_Year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ba41d6c-5e78-4777-ac28-9da5d87724eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>915fbd08-d253-4ad2-97db-abc6f039bdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maskYear baj-results-inp form-control target-birthdate-el target-pax-birthyear</value>
      <webElementGuid>ad1fd93c-e644-4207-9e6a-3a6ecf90f790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Year</value>
      <webElementGuid>e2a8d044-e687-4821-b737-9c279e64ee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b25880ca-5069-4e83-938b-5d4bac268028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>510180ae-1436-4582-b6a2-0eeb8439e8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The BirthDate_Year field is required.</value>
      <webElementGuid>565db1c8-a882-47a2-bf16-312b03ac7bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_1__BirthDate_Year</value>
      <webElementGuid>bb38d5bc-5356-43f7-8727-b8e3f89f4b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[1].BirthDate_Year</value>
      <webElementGuid>c94ecd57-28a2-4c7d-98d9-bd446452b75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_1__BirthDate_Year&quot;)</value>
      <webElementGuid>a14bf125-fecc-4cd1-a47c-fc8fdb1751d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_1__BirthDate_Year']</value>
      <webElementGuid>019d8778-b553-4bf8-a286-019927ad9bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-2']/div[3]/div[2]/div/div[2]/div/div/div[4]/input</value>
      <webElementGuid>c74aabf5-610c-48c8-86ea-552e5cbe7c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[4]/input</value>
      <webElementGuid>be9d74d5-959e-471a-871b-169d81c44f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Year' and @type = 'number' and @id = 'Legs_0__Passengers_1__BirthDate_Year' and @name = 'Legs[0].Passengers[1].BirthDate_Year']</value>
      <webElementGuid>38688534-38ef-4c02-8404-f0eec80a1698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
