<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstLegDepartureDate_filter</name>
   <tag></tag>
   <elementGuidId>5cbba23a-79e0-41db-a378-1ed760f207e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='one-loop-saved-loops-table']/thead/tr/td[7]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td[name=&quot;FirstLegDeparture&quot;] > div.thead-arrow-div > a.target-new-sort-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d7e4224-bf00-4257-9191-10b40cb18289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>560b60c0-a5e8-4af6-8b11-4c53e9c114e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-new-sort-header</value>
      <webElementGuid>e41da417-d42c-479a-8e36-d0eae7dce51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sort</name>
      <type>Main</type>
      <value>FirstLegDeparture</value>
      <webElementGuid>c68b4b89-84c1-4ad8-b7ec-95a2bb6bddf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            First Leg Departure Date
                        </value>
      <webElementGuid>bffd2f77-0464-4db3-a8f1-f9caa9c418c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;one-loop-saved-loops-table&quot;)/thead[1]/tr[1]/td[7]/div[@class=&quot;thead-arrow-div&quot;]/a[@class=&quot;target-new-sort-header&quot;]</value>
      <webElementGuid>f1a0a929-d22d-41ae-a0b3-deba9939275a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='one-loop-saved-loops-table']/thead/tr/td[7]/div/a</value>
      <webElementGuid>6899c898-b913-417d-9e88-d375ff4a0111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'First Leg Departure Date')]</value>
      <webElementGuid>cba4b4e3-c5e1-48e1-8a06-03f023ae1eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward >'])[1]/following::a[7]</value>
      <webElementGuid>4ca80dd7-8ea3-46e7-93e2-b8df3be18ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of 4'])[1]/following::a[7]</value>
      <webElementGuid>03741592-0f8a-4634-958f-bc523142fb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(SLC) 11/28 - 11/30'])[1]/preceding::a[5]</value>
      <webElementGuid>1b9c636a-4b43-4d4c-9a0b-fb83a42bb71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eugene Trujillo'])[2]/preceding::a[5]</value>
      <webElementGuid>ae7c95bb-c64e-418d-ae0b-e5481619c65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>8f5572b9-4b88-45a3-99c5-528708c7959c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/a</value>
      <webElementGuid>fdd8a558-8427-48d8-a027-7e33774c0d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '
                            First Leg Departure Date
                        ' or . = '
                            First Leg Departure Date
                        ')]</value>
      <webElementGuid>049a16ed-69d1-4643-bea3-0c3cb014af5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
