<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>americanExpress_checkBox</name>
   <tag></tag>
   <elementGuidId>92f3338c-8cea-441f-8817-4cf18cda05ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlanOriginal_UserAgreement_AmericanExpress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlanOriginal_UserAgreement_AmericanExpress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6842a2f-c8e8-45e7-9c73-fabc29cb32d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-absolute</value>
      <webElementGuid>ffe5df70-070c-4299-855a-7aa4b55b2b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62f61865-3bc5-478e-aad3-67265e2916eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Must Agree to American Express Authorization</value>
      <webElementGuid>32387ad0-380f-4896-89c3-95ac0e2fc4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>962c0a44-3e55-4077-9e8f-d51111644fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>03f2dff6-5f51-4db3-a7b0-e28e760dceb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The American Express Authorization field is required.</value>
      <webElementGuid>eecc5701-9b01-4878-aeb6-62d3bd9ed8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlanOriginal_UserAgreement_AmericanExpress</value>
      <webElementGuid>dcfc0758-a00c-4d4e-ae52-567780930378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlanOriginal.UserAgreement_AmericanExpress</value>
      <webElementGuid>82d8b8eb-57d5-4195-98e9-8a8135cd31c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7ca103d8-5021-49bf-a903-07058a4fcb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e4886c9-aae9-47e0-960e-418eb841a151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlanOriginal_UserAgreement_AmericanExpress&quot;)</value>
      <webElementGuid>ea3d4ab7-db1f-428b-8cc7-430eeb154b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlanOriginal_UserAgreement_AmericanExpress']</value>
      <webElementGuid>689d8fa8-d2f8-4638-a882-392f3573dc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ItineraryPaymentForm']/div[3]/div/div[3]/div/div[3]/input</value>
      <webElementGuid>69cdfd71-fb3e-452d-8807-2ee926c97c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7e5a6b0d-8792-43e8-bcbc-812dc37a9cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FlightPlanOriginal_UserAgreement_AmericanExpress' and @name = 'FlightPlanOriginal.UserAgreement_AmericanExpress' and @type = 'checkbox']</value>
      <webElementGuid>a69ce8b3-9d7c-4e59-ab28-bc14c827b710</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
