<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_textBox</name>
   <tag></tag>
   <elementGuidId>85ab951d-4f03-4c4d-995e-bc58f859d503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_billing_address_city']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_billing_address_city</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e3f8187-c4e9-4bf1-b74c-4d64772a72a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0c7b516-d176-4a0f-aa75-43bc0398def6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control font-weight-normal</value>
      <webElementGuid>64a80e87-f94c-421c-88a6-cb3e931dc5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>970c2a76-edb4-4c74-a7a9-02ff88c323ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cefab38a-33ca-4741-a07c-c058a3513933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The City field is required.</value>
      <webElementGuid>49233af4-997e-4717-9403-f23a79f3ecaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_billing_address_city</value>
      <webElementGuid>307a99df-4e51-4d18-8773-27a64140c38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.billing.address.city</value>
      <webElementGuid>0c27526c-c820-43bd-8aec-b8bb45949e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_billing_address_city&quot;)</value>
      <webElementGuid>3e839677-214a-4737-bc4b-ef7dc2609f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_billing_address_city']</value>
      <webElementGuid>c5ad5122-a0f4-4eaf-911f-7c7950ff6353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-itinerary-amex-data']/div[2]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>2c68bbec-05da-40c3-99f4-9fadfc69bb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/input</value>
      <webElementGuid>9ad0aa10-649b-42b0-a8f3-d6cb428efb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'City' and @id = 'AmericanExpressRequest_billing_address_city' and @name = 'AmericanExpressRequest.billing.address.city']</value>
      <webElementGuid>b5e55128-b2d6-4abf-84e0-fdb15b38ac87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
