<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zip_textBox</name>
   <tag></tag>
   <elementGuidId>ddd70514-ffff-450a-bc80-0a47a8b665e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_billing_address_postCodeZip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_billing_address_postCodeZip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>273f62f2-7cbd-45bc-9e9a-82637eab4da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83a2ac6c-801a-4f5d-b892-aaeea1b28eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control font-weight-normal</value>
      <webElementGuid>35b8bc08-08d8-4d7a-a8af-f45427901901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip Code</value>
      <webElementGuid>c9da1106-2bbd-474f-b463-ab8c54ed3ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>123896bd-7ff7-4731-9446-58ee47a58005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Zip Code field is required.</value>
      <webElementGuid>8ae0958b-ba49-4777-9c9a-8d9041fafed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_billing_address_postCodeZip</value>
      <webElementGuid>ea0ea69d-fdbd-4578-ac92-dd2431e9ec3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.billing.address.postCodeZip</value>
      <webElementGuid>4c8a446e-fbc9-4595-b8f0-d7d3974d9e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_billing_address_postCodeZip&quot;)</value>
      <webElementGuid>05a5e101-4e1f-4fa1-9013-5db22e69c2d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_billing_address_postCodeZip']</value>
      <webElementGuid>4347c647-7b9c-4a57-846c-962aa7625b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-itinerary-amex-data']/div[2]/div[2]/div[3]/div[3]/div/input</value>
      <webElementGuid>c7d36a5f-a143-4cb3-b232-cc59db4f83e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[3]/div/input</value>
      <webElementGuid>7df46385-a2f4-4d5c-af53-d25095c36596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Zip Code' and @id = 'AmericanExpressRequest_billing_address_postCodeZip' and @name = 'AmericanExpressRequest.billing.address.postCodeZip']</value>
      <webElementGuid>17ffebcd-11a3-4e0a-8634-3f6209dc393f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
