<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addNewContact_button</name>
   <tag></tag>
   <elementGuidId>d3c8cf23-f60f-4ff5-ad4a-d976091ace81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.of-red.target-contact-new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContactsDynamic']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94c83348-31c8-4b2b-a517-a917b71a6f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>6b1737d6-095b-4cd5-a2d4-7223d71805d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-id</name>
      <type>Main</type>
      <value>1035</value>
      <webElementGuid>56de8949-ccd6-4641-982b-451338a88aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>of-red target-contact-new</value>
      <webElementGuid>9bc1ee52-e843-4a48-9ef7-65a71156a0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add New Contact</value>
      <webElementGuid>647a2099-f4ab-469f-a060-dfcc251dfd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactsDynamic&quot;)/div[@class=&quot;float-right&quot;]/a[@class=&quot;of-red target-contact-new&quot;]</value>
      <webElementGuid>fcc64dc8-01e2-4e32-ae03-84e567454b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactsDynamic']/div/a</value>
      <webElementGuid>515f656c-9217-4029-ada2-29fa9dfc7624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'+Add New Contact')]</value>
      <webElementGuid>9d24a44b-14ef-4eb7-a16b-5ef0f4af0651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[2]/following::a[1]</value>
      <webElementGuid>c49b1f3c-ced2-47de-80ba-dd8298183ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAJ Safety'])[2]/following::a[1]</value>
      <webElementGuid>05d04eac-d455-4d59-a81d-58da07ea06c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator Contacts'])[1]/preceding::a[1]</value>
      <webElementGuid>65c774a9-ce2f-4661-bd6c-384a0257545d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::a[1]</value>
      <webElementGuid>87c1edc0-1098-47a4-94cc-cbd03a03f228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+Add New Contact']/parent::*</value>
      <webElementGuid>dba64b9f-9f8f-4ec5-a342-a5e3a570be5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>8dba1df7-f5b1-494d-8e5a-e304ebea6b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>62706660-96cc-4542-a683-956d8e8d66d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '+Add New Contact' or . = '+Add New Contact')]</value>
      <webElementGuid>29609991-a50c-4706-80c4-8abdfed0c4e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
