<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addressType_dropDown</name>
   <tag></tag>
   <elementGuidId>2f831ca6-43ce-40ff-ad72-e3b1d6716b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressTypeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AddressTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27a5df7e-6e7a-4431-8978-fd114191ed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tighter-select</value>
      <webElementGuid>766f2ffe-1cc8-4517-9401-731f59ead01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressTypeId</value>
      <webElementGuid>a64020d5-01bd-4d09-b1c9-d91843438e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressTypeId</value>
      <webElementGuid>a67e2956-ce0c-4809-a6f5-260081051245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select
Office
Personal
Other
Business
Business Contact
Unknown
</value>
      <webElementGuid>388ec1ce-dd35-4ee2-9ee4-8d0e852dfac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressTypeId&quot;)</value>
      <webElementGuid>6b707043-4013-46b9-b601-acd292b0b048</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AddressTypeId']</value>
      <webElementGuid>7de38775-1c8b-4756-a1d8-52ace06baa7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[4]/tbody/tr[12]/td/select</value>
      <webElementGuid>8776262f-6bb1-4e1e-ba74-cfbd00b6e85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Type'])[1]/following::select[1]</value>
      <webElementGuid>0fa74c25-045c-41ed-8b9e-520d9d36fda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>3d98a400-1366-441e-acd8-a3fe6a31e40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/select</value>
      <webElementGuid>dfed95db-72fd-4b86-a65b-e188b3da43ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AddressTypeId' and @name = 'AddressTypeId' and (text() = 'Select
Office
Personal
Other
Business
Business Contact
Unknown
' or . = 'Select
Office
Personal
Other
Business
Business Contact
Unknown
')]</value>
      <webElementGuid>4c4245a1-fd52-4153-ae38-5d020dd0f328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
