<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_textBox</name>
   <tag></tag>
   <elementGuidId>ab8d88cf-573a-4583-ab06-92467a89bbc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#City</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f0b849e-e2b9-4c5c-aa5e-ad1bf0d3f6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tighter-input</value>
      <webElementGuid>109ac635-69df-499e-b4a9-9d32302f5de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>71f1bf8b-e24b-4196-8b0a-e598b5fa83da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>c8deba80-26ba-45d2-a286-f46a5fbcb52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c65e6626-5e53-44e4-8cfe-478e069cab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;City&quot;)</value>
      <webElementGuid>b68dfd31-f2b6-469d-99ac-fce1d2e11cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='City']</value>
      <webElementGuid>a9b0700d-a3b5-4086-bbec-4350a3ca64af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[4]/tbody/tr[6]/td/input</value>
      <webElementGuid>af99edec-0396-4a37-a1c6-a4061c6bf944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>0504bb0b-cc0e-48d0-8ce4-2ef8c58b270f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'City' and @name = 'City' and @type = 'text']</value>
      <webElementGuid>4e993ead-a321-4739-b6c5-1b3a370ab141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
