<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailAddress_textBox</name>
   <tag></tag>
   <elementGuidId>8e6e93bd-2cb1-454a-86e0-b78456fe07b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fad45e39-2e0b-4835-9328-acf498eeac7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tighter-input</value>
      <webElementGuid>f22c2ad4-3874-4a58-8e13-ca407f124cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01368393-c917-4453-89af-c776cbb14363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>The Email Address field is not a valid e-mail address.</value>
      <webElementGuid>56e57606-60ff-4c44-bce2-262e41470047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailAddress</value>
      <webElementGuid>c49bedf0-7ba6-42f2-855a-6b60ea47eb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailAddress</value>
      <webElementGuid>fc2aea71-cd1c-4265-a8ec-cb282ccc0960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16bea581-b68f-4de5-9074-39bc9fb6778f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailAddress&quot;)</value>
      <webElementGuid>c31c0ee1-c265-4b91-8c5e-272f49c4905c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailAddress']</value>
      <webElementGuid>9f9baa77-2200-4585-919b-ca86be021b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[3]/tbody/tr[2]/td/div/div/input</value>
      <webElementGuid>4807c7c0-aeed-4222-9fcf-585d4164b064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr[2]/td/div/div/input</value>
      <webElementGuid>fce4c151-e4b7-4aa7-9d4f-64b320662f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailAddress' and @name = 'EmailAddress' and @type = 'text']</value>
      <webElementGuid>e0eddd09-e5c5-4024-9d2a-da8ff3bdf072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
