<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phoneType_dropDown</name>
   <tag></tag>
   <elementGuidId>078ae230-8472-4d8f-a6bf-961c9f71c3f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhoneTypeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PhoneTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ccde7b1-9fb1-4ed0-a9b4-7f7e31a32909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-tighter-select</value>
      <webElementGuid>04f9d1a5-b227-4a97-932f-770cf6705831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneTypeId</value>
      <webElementGuid>ea42a200-c5d9-499a-a403-722f0c6838e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneTypeId</value>
      <webElementGuid>dafec4f5-133b-42f5-b9ac-e2e34ca20da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select
Cell
Home
Work
Business
Contact
Other
</value>
      <webElementGuid>464e5aae-99d0-4678-9429-f02b6a1ac768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhoneTypeId&quot;)</value>
      <webElementGuid>93dca019-0e22-4e8b-bee0-242c359979de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PhoneTypeId']</value>
      <webElementGuid>23981c5f-be5d-45ef-844f-9c0329c8ca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[2]/tbody/tr[2]/td/div/div[2]/select</value>
      <webElementGuid>be3ce29a-023c-45b9-93f2-cc6cc71ebd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Type'])[1]/following::select[1]</value>
      <webElementGuid>f1d8eb44-eb2d-49dc-9f90-b3fe60cee82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::select[1]</value>
      <webElementGuid>45483240-78a9-4496-b85a-438865263032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/preceding::select[1]</value>
      <webElementGuid>94dcbd5c-8dac-4cba-98a0-9779da7f04cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Type'])[1]/preceding::select[1]</value>
      <webElementGuid>7953e7f4-92ae-47f2-b879-e75e2e5ac932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/select</value>
      <webElementGuid>bfb9e270-9133-48f5-a3ac-e07fc1eb9035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PhoneTypeId' and @name = 'PhoneTypeId' and (text() = 'Select
Cell
Home
Work
Business
Contact
Other
' or . = 'Select
Cell
Home
Work
Business
Contact
Other
')]</value>
      <webElementGuid>e27b5829-ead1-43e9-b10f-13c7a421859d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
