<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>zipcode_textBox</name>
   <tag></tag>
   <elementGuidId>a07df9e2-ac2f-490a-a8cd-65369686393c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Zipcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Zipcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eac9279f-eb34-48af-bac2-c122b8bdf2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tighter-input</value>
      <webElementGuid>cb2568db-fb24-47f9-9ef4-cfc87056ae37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Zipcode</value>
      <webElementGuid>6d6a744c-4435-48c4-b244-903690699453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zipcode</value>
      <webElementGuid>8420bbef-4190-41c9-bfdc-8bd40eeb00e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da45b57c-8c7a-4fdb-a411-915c0e769ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Zipcode&quot;)</value>
      <webElementGuid>a8d3197b-2699-4723-8cdf-36768d9e46dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Zipcode']</value>
      <webElementGuid>a00272f0-f2f6-4def-a293-1003e1f0480c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[4]/tbody/tr[8]/td/div/div[2]/input</value>
      <webElementGuid>7aae1a6a-61ab-449d-a736-7bf7c56348a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/input</value>
      <webElementGuid>0bb46c54-fa3a-4c19-a8ee-45c9ae78e0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Zipcode' and @name = 'Zipcode' and @type = 'text']</value>
      <webElementGuid>98811f90-c0a4-4e33-901f-0f37fa0084f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
