<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firearms_checkBox</name>
   <tag></tag>
   <elementGuidId>428ce0f7-76dc-4a96-9fa6-2b17dcd8d6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__FirearmsDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__FirearmsDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5cbd60a-c16f-483d-996b-f1b919a304b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-firearms-nonecheckbox</value>
      <webElementGuid>f56643a9-30fd-451a-9109-b2056416e31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad736f21-9036-45e7-956f-ce19233482fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FirearmsDescriptionNone field is required.</value>
      <webElementGuid>c562c5a2-3532-4186-936e-d609ebfaa939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__FirearmsDescriptionNone</value>
      <webElementGuid>182bb627-b5d6-450c-800f-55c202e8c45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].FirearmsDescriptionNone</value>
      <webElementGuid>b56b53db-a0b6-40a3-9124-9542138e618e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8d9eca95-3d05-4a38-9000-6549be1e67d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3b9dad9-7105-4b6a-8d71-aaa06ffb4d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__FirearmsDescriptionNone&quot;)</value>
      <webElementGuid>376e9f8f-f41b-4e43-b5d3-3e2c5f6c9fda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__FirearmsDescriptionNone']</value>
      <webElementGuid>35d4a93c-7ae1-470d-80db-44fcb1fe36ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>6d36cbe8-6445-45b1-b875-2a347e0af16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>7723ed11-2d4a-4d74-a194-859d4cf95a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__FirearmsDescriptionNone' and @name = 'Legs[0].FirearmsDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>c8fce38c-323c-4a1b-9660-a576c4a28402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
