<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_checkBox</name>
   <tag></tag>
   <elementGuidId>daed1106-c573-46dc-90f0-5cad2c1c59f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__LuggageDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__LuggageDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c23af71-26f4-4176-8843-e9a349d3045a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-luggage-nonecheckbox</value>
      <webElementGuid>7402aa7c-c8a1-46bc-9f39-8974887fe1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>502d14ec-b186-4971-b46e-0ed0b7a6e117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LuggageDescriptionNone field is required.</value>
      <webElementGuid>858b4d01-9f49-4731-889f-9b833eb803f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__LuggageDescriptionNone</value>
      <webElementGuid>59d9464e-bcec-4dd0-8be1-d1702232f085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].LuggageDescriptionNone</value>
      <webElementGuid>75b47d55-f354-43fb-8236-2ac5a289cda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cc7e50b3-3525-4f9a-a2e2-7049026add65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d72535a8-3c72-45fb-a1be-a7d376de8f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__LuggageDescriptionNone&quot;)</value>
      <webElementGuid>19431754-5f35-4d98-9c67-2e9d31ca5f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__LuggageDescriptionNone']</value>
      <webElementGuid>60751246-c909-4859-b42d-83f757336cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div/div[3]/div/div/input</value>
      <webElementGuid>2edeab93-b1b5-4820-869c-63d4189e3c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>1f2cda5e-5d53-4f8b-b1a3-557a4a03149b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__LuggageDescriptionNone' and @name = 'Legs[0].LuggageDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>460c7ce0-6e98-4497-9357-6b17b72def55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
