<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_textBox</name>
   <tag></tag>
   <elementGuidId>e57b1b29-cd76-41c8-a4e3-a588ecdd2bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Legs_0__LuggageDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__LuggageDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dfb7c43e-a111-4a56-bcba-f0f2d8ecf9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-textarea form-control target-luggage-description</value>
      <webElementGuid>84c0899f-fd09-431c-8c39-64155b88ebd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>754fb47b-27c9-416e-8b30-536de6b11f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__LuggageDescription</value>
      <webElementGuid>ed3b57e4-c376-47a6-b29e-22e19523dd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].LuggageDescription</value>
      <webElementGuid>93080908-5c6e-49ae-996e-08fab34100e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1eb6030d-a3b7-4a3b-82b4-6e41376b010d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__LuggageDescription&quot;)</value>
      <webElementGuid>3601dc30-ee13-4e19-8e41-e37fb1856083</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Legs_0__LuggageDescription']</value>
      <webElementGuid>3970368d-9bd1-487c-8df5-78ced5e832e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div/div[5]/textarea</value>
      <webElementGuid>d2cd84ba-96b5-4247-81e6-7cbd5666fe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/textarea</value>
      <webElementGuid>9ad2bf24-7524-468b-a408-d289b6b7624a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Legs_0__LuggageDescription' and @name = 'Legs[0].LuggageDescription']</value>
      <webElementGuid>82efec61-8f0f-4f4a-8d59-4270c08e545f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
