<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>done_button</name>
   <tag></tag>
   <elementGuidId>7d680a20-759e-4121-a3b0-cd99c8cd7f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Pizza-optionsclose']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Pizza-optionsclose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86520881-4316-42ab-a182-3640b02c76ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>finished-catering-selectons-button</value>
      <webElementGuid>3bd8eac0-4cfa-46af-b40e-1f9b457463f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>e45e2225-b9de-4968-b01e-d8d136b4c2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Pizza-optionsclose</value>
      <webElementGuid>2fcc29c0-95d0-47a5-85cb-5dd56c5fa936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>85bddf05-5749-46b8-9d85-969faf584288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Pizza</value>
      <webElementGuid>79dbc868-5791-4e23-96f4-a4e7cb378e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>87db4c53-82ae-45fe-a7c1-10be727c287c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Done
                                                                    </value>
      <webElementGuid>acb8c2fa-b7ef-496b-9bdd-70e6000837b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pizza-optionsclose&quot;)</value>
      <webElementGuid>71e81d7d-7233-4e02-a354-f6433921de79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Pizza-optionsclose']</value>
      <webElementGuid>20e6a357-745e-409f-978c-94cc00666390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pizza-options']/li[5]/button</value>
      <webElementGuid>9826da89-a3a5-4198-b012-8c72c5d37610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheese'])[1]/following::button[1]</value>
      <webElementGuid>dad504a3-259e-45ad-853b-bd754c3cb77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pepperoni'])[1]/following::button[1]</value>
      <webElementGuid>8cc99e3e-27cd-4a14-a3b9-347dace3ea12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[13]/preceding::button[1]</value>
      <webElementGuid>0fe3e93d-5bbd-4677-9dc3-ac95a2ff9f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[3]/ul/li[5]/button</value>
      <webElementGuid>8c41c79e-e1ad-4c93-b3ed-d694e864aac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Pizza-optionsclose' and (text() = '
                                                                        Done
                                                                    ' or . = '
                                                                        Done
                                                                    ')]</value>
      <webElementGuid>948d23b7-433a-43fc-b411-45d6ef84772a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
