<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pepperoni_checkBox</name>
   <tag></tag>
   <elementGuidId>f748df33-8a94-4ff0-8b8c-38432569f001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Pizza-options']/li[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5a25f0dd-653b-4412-8e25-9d8cc5c9c959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>PizzaPepperoni</value>
      <webElementGuid>dd6c430d-4c94-4f03-8155-ae27d8d47f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pepperoni</value>
      <webElementGuid>07bc8df9-612b-46ae-992b-33e98e79c73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pizza-options&quot;)/li[3]/label[1]</value>
      <webElementGuid>1e444ed1-7c66-46cf-9bbb-9b7b7252113b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pizza-options']/li[3]/label</value>
      <webElementGuid>b079d018-545d-43f2-bf1b-8cb61aa6d95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sausage'])[2]/following::label[1]</value>
      <webElementGuid>8d9a1b2a-e6e3-41c3-ae6e-33cd61dec57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[16]/following::label[2]</value>
      <webElementGuid>363b66f8-bef2-41a0-a570-63c10603916b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheese'])[1]/preceding::label[1]</value>
      <webElementGuid>3000cdbc-c983-4ede-bf39-ac82e7fcb056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[4]/preceding::label[2]</value>
      <webElementGuid>570b2d52-52a2-47d4-a9d7-073ad044e9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pepperoni']/parent::*</value>
      <webElementGuid>01c52c7d-67dc-44f2-a947-fe9000ffe31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[3]/ul/li[3]/label</value>
      <webElementGuid>204215e7-aafb-4373-9e61-414c6c73210c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pepperoni' or . = 'Pepperoni')]</value>
      <webElementGuid>b074593d-11e8-402b-8af3-17b73d5f3c51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
