<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sausage_checkBox</name>
   <tag></tag>
   <elementGuidId>c2ba1e27-ec9e-4b31-8773-3b153bd11686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Pizza-options']/li[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b8904e63-479c-4a94-ab01-23eeeda6b122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>PizzaSausage</value>
      <webElementGuid>5efd180e-014d-44e9-9196-420a59035717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sausage</value>
      <webElementGuid>8b7840e6-3a8d-44cb-9471-b85d023354c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pizza-options&quot;)/li[2]/label[1]</value>
      <webElementGuid>f51a9d61-19a5-4074-a57b-9c6bf4b8a3c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pizza-options']/li[2]/label</value>
      <webElementGuid>d899dc53-05a4-4d4c-91f0-91bafbedf1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[16]/following::label[1]</value>
      <webElementGuid>2572f896-0700-4949-bdcf-2ed8d8f1a1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[12]/following::label[1]</value>
      <webElementGuid>f2e1e8fe-5839-4ee1-9f06-014f23ac0de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pepperoni'])[1]/preceding::label[1]</value>
      <webElementGuid>0f81eadb-edc8-4d69-b8d8-5eccf8ec009c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cheese'])[1]/preceding::label[2]</value>
      <webElementGuid>1c7f0214-9977-49a7-a9da-63ee7f98eb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[3]/ul/li[2]/label</value>
      <webElementGuid>c6dd2917-7572-42be-9749-a11fcda8b187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Sausage' or . = 'Sausage')]</value>
      <webElementGuid>ea81a0d8-4439-4fe9-8eb8-f0e6529225b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
