<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>primaryAddress_checkBox</name>
   <tag></tag>
   <elementGuidId>d9df7602-ab23-492f-a999-129fc1f28e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cbIsPrimaryAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cbIsPrimaryAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e91e527-1663-465c-b4df-b7130a419551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>204cf3e2-fce4-4fdc-9345-47675adc661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cbIsPrimaryAddress</value>
      <webElementGuid>b6343716-1a19-4b3d-bf09-175bb86065b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cbIsPrimaryAddress</value>
      <webElementGuid>fc6646e4-9dc0-4745-b909-aeaf3b8c4d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cbIsPrimaryAddress</value>
      <webElementGuid>739ce9a1-f483-46c9-8d0f-0c4cb12ed5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-isprimary target-popup-field</value>
      <webElementGuid>09dd43ee-c799-4283-8ea7-b22f77e52566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cbIsPrimaryAddress&quot;)</value>
      <webElementGuid>2153c294-38ad-4cde-8886-3b34d754994d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cbIsPrimaryAddress']</value>
      <webElementGuid>44376480-86a2-4a8e-a11c-ffeef50abde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='NewAddress']/div/div[7]/label/input</value>
      <webElementGuid>8f0e275b-f7f8-4e72-8b9e-27e0f138d804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/label/input</value>
      <webElementGuid>3a160bc1-a22c-4306-b556-012a87fab2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'cbIsPrimaryAddress' and @name = 'cbIsPrimaryAddress']</value>
      <webElementGuid>65f026c9-fcb9-4591-92cf-3bfd643664da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
