<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street2_textBox</name>
   <tag></tag>
   <elementGuidId>7b7f05d2-00fe-4308-a14b-8e5f93ca4a89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Street2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Street2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9144db9-7516-45ca-819b-a99c3e792cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control black-tight-input target-popup-field</value>
      <webElementGuid>fbd9d5ae-9fed-4ef1-bf96-e859b10ffb22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5615128d-7183-4ca6-a5a5-d68e05216675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Street2 must be a string or array type with a maximum length of '50'.</value>
      <webElementGuid>0ebf1743-40d2-4d17-8e83-217f4f1a98af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>35648a3d-2974-440b-a6c1-8e9d9bc6f7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Street2</value>
      <webElementGuid>6022bfd1-cad6-41ce-80ba-782f1f4c0e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4b019d76-7b33-4727-bd91-317a3116b8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street2</value>
      <webElementGuid>1d9d55a9-53b2-42e4-b66d-e545cd0fdd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f07d28b0-66ae-4618-bf5c-62b5ec0a0a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Street2&quot;)</value>
      <webElementGuid>7caa42e4-9700-4ceb-a896-e4db3bbd6cb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Street2']</value>
      <webElementGuid>5260f8c5-76e6-454c-b48c-2333a5b9d3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='NewAddress']/div/div[3]/input</value>
      <webElementGuid>1ba10854-5af1-43a8-8ec0-24bbb8e04c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/input</value>
      <webElementGuid>0cf59a3f-fb5d-4456-839b-c66d72e1cc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Street2' and @name = 'Street2' and @type = 'text']</value>
      <webElementGuid>e5705af2-4ff3-4388-8da8-eb4a611620dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
