<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>internalNote_textBox</name>
   <tag></tag>
   <elementGuidId>9b6a5bc8-53ef-4a14-afe7-2d490d73f7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='LatestNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LatestNote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>775acf22-e33e-4142-b56f-05f6c046fa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea-small</value>
      <webElementGuid>47a530c9-8a1d-4adf-9640-54deb9d1538c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LatestNote</value>
      <webElementGuid>4376fcc7-0d53-45fc-a948-827caa68bc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909595&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-5&quot;]/textarea[@id=&quot;LatestNote&quot;]</value>
      <webElementGuid>4090ab69-0776-4688-bd90-807688fcba93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='LatestNote']</value>
      <webElementGuid>137df56c-589a-4092-b9e5-ecce5dc26e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='catering-quote-0']/div/div/div[2]/textarea[2]</value>
      <webElementGuid>19916d8c-f590-4062-8dde-def9bf811650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea[2]</value>
      <webElementGuid>8a24a249-8e33-4ef7-bda5-f82cbe50dd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'LatestNote']</value>
      <webElementGuid>1969f41a-5515-4951-988c-8c97599e2e15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
