<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>member Information_textBox</name>
   <tag></tag>
   <elementGuidId>4ea3c8ea-39e0-4f72-8b61-f1ef51964f0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_OriginGroundTransportationMembershipInfo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_OriginGroundTransportationMembershipInfo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47a1d914-f9c7-4dfe-a9f9-10a2f00b73b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12f6cda1-a141-4600-803a-7853f929bd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2165da75-9ab0-4397-9fc2-54c2250a5224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83c296f4-f275-4a16-907e-8579a4ee4589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_OriginGroundTransportationMembershipInfo</value>
      <webElementGuid>de417277-74d4-4dea-a975-8b01fd9b36fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.OriginGroundTransportationMembershipInfo</value>
      <webElementGuid>c8d8073c-6b63-409d-af2e-5ca4b5a16228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_OriginGroundTransportationMembershipInfo&quot;)</value>
      <webElementGuid>c36d4f99-8960-498e-9066-2bdec403a8af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_OriginGroundTransportationMembershipInfo']</value>
      <webElementGuid>f90b14bc-142a-4b8e-b68c-4fd5d7612a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-pickupform']/div[2]/input</value>
      <webElementGuid>f811e9c2-cb92-49b5-956d-51fbf66a365f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>738dc281-2037-458a-8c5d-a9449a055c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_1__ActiveConciergeOrder_OriginGroundTransportationMembershipInfo' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.OriginGroundTransportationMembershipInfo']</value>
      <webElementGuid>4fa50237-a2ff-4375-8c8f-9bbd86e5ce7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
