<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save_button</name>
   <tag></tag>
   <elementGuidId>39b37a2f-c6f2-4791-b5aa-50d564013da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.target-save-operator-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12c7132a-c604-4d5a-b037-fd2085fd5d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>208edecf-4f39-470f-85df-0040388fc27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>4ec4e6f2-38d4-4d2e-bc73-19f380adcb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>6ffc5d61-348b-43c3-8783-558014a29032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary target-save-operator-quote</value>
      <webElementGuid>51312411-8981-4985-9b99-c2266970ccda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-op-quote-form&quot;)/div[@class=&quot;row text-center&quot;]/input[@class=&quot;btn btn-primary target-save-operator-quote&quot;]</value>
      <webElementGuid>8e86c5c6-f7da-49fd-adbe-2004626759a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save'])[2]</value>
      <webElementGuid>46ca0d3a-7247-4ce2-a0f5-a4d66a519751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-op-quote-form']/div[2]/input</value>
      <webElementGuid>e4d0586e-6efc-49d7-a30d-10854efb36ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>3440e60c-89f3-47d4-9ecb-f2520736ed9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>f51adf93-3ba9-4f03-97fa-71365a4b97f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
