<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>suv_textBox</name>
   <tag></tag>
   <elementGuidId>3d2f517b-dc8a-4208-a5bb-4053c46f9257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909637 > #new-executive-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-7 > div.row > div.col-xs-4.flex-start > #ConciergeQuoteXExecutiveVehicles_0__Quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='ConciergeQuoteXExecutiveVehicles_0__Quantity'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c5fc1f2-a15b-4f4a-99c9-5ada77d40ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0e5d287b-3202-4253-93b1-658a8626eeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-vehicle-quantities</value>
      <webElementGuid>5744cceb-1192-46dd-9447-81302dbe1ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>440336df-8ecc-43d1-a3e8-b756230ca6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7562b82-2b2c-489c-8109-2ee6ad70f32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0413d3da-374c-464b-96a8-5041fb372eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vehicletype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a95c04ea-7c8a-41b4-95a8-29852ba9eae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48</value>
      <webElementGuid>4d6063e0-a26e-4d9d-a822-3455264a95f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConciergeQuoteXExecutiveVehicles_0__Quantity</value>
      <webElementGuid>ee7a66de-55e3-42f8-b8be-b74cf5faa22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConciergeQuoteXExecutiveVehicles[0].Quantity</value>
      <webElementGuid>3fe22c19-bd5c-475c-9927-8693e62cf455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dd7be922-e0d1-4d6a-bbb8-4f4ffc977c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909637&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 flex-start&quot;]/input[@id=&quot;ConciergeQuoteXExecutiveVehicles_0__Quantity&quot;]</value>
      <webElementGuid>1d71d3d1-2d84-4991-90c5-e7079e932b71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='ConciergeQuoteXExecutiveVehicles_0__Quantity'])[7]</value>
      <webElementGuid>abdb82e4-ffb8-4268-a7a5-24d3fdb0f5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[3]/div/div[4]/input)[3]</value>
      <webElementGuid>ffdc7963-f10f-4466-8c97-1bd757ba9a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div[2]/div[2]/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>b367ed34-59f9-4ba3-908b-2f1346dc3eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ConciergeQuoteXExecutiveVehicles_0__Quantity' and @name = 'ConciergeQuoteXExecutiveVehicles[0].Quantity']</value>
      <webElementGuid>deb5a97a-3fb8-4265-9e33-ee3b8baf7141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
