<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>street2_textBox</name>
   <tag></tag>
   <elementGuidId>05997f16-7d73-4e87-af6b-877607081c18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmericanExpressRequest_billing_address_street2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_billing_address_street2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6d48f5a-c622-474c-afad-a8a29f9c520f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de0acc4c-ac07-49eb-802c-f35b0588604b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_billing_address_street2</value>
      <webElementGuid>49cb5877-bb07-49a3-840b-99e8514ccb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.billing.address.street2</value>
      <webElementGuid>25a1ec81-ec26-45e3-99cf-44a4ff90abde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5513c1c-9a03-4ce5-ac1e-5f7cbd8f539a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_billing_address_street2&quot;)</value>
      <webElementGuid>842ec0b6-7477-4b61-ad59-c07b619188a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmericanExpressRequest_billing_address_street2']</value>
      <webElementGuid>9f3e1607-955a-4af4-a95e-94453bf0f1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tabContent']/div[4]/div[2]/div/input</value>
      <webElementGuid>8a07bd82-c7ac-461f-a302-b7e22e202c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>b06b17c1-66a3-4ac4-859f-b8a85309b7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AmericanExpressRequest_billing_address_street2' and @name = 'AmericanExpressRequest.billing.address.street2' and @type = 'text']</value>
      <webElementGuid>f624cc17-ed50-4973-b30e-c31e16d4d8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
