<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>year_dropDown</name>
   <tag></tag>
   <elementGuidId>58a07de2-444a-413f-a754-aeca123f3214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5b720c81-1874-4d88-97e8-701bcf85c242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control</value>
      <webElementGuid>930a7fa5-ec17-44cb-90ed-3934ce135578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9dee0a6c-e45e-4243-a11a-864ba6c26a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Year field is required.</value>
      <webElementGuid>272f31ae-fb7f-49a7-8aee-f9331b4996c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year</value>
      <webElementGuid>c1f66161-5521-42f7-a123-4f2f56424140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmericanExpressRequest.sourceOfFunds.provided.card.expiry.year</value>
      <webElementGuid>4a3d35a7-79c6-4adb-a773-3c49a2f2366f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
</value>
      <webElementGuid>5461a2ff-80ad-4554-9882-7b7137dd3d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year&quot;)</value>
      <webElementGuid>e425bbf0-3eee-45e8-b4df-521a9ccaf83c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year']</value>
      <webElementGuid>c9694124-7e85-4557-a4fe-e01f792b8218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tabContent']/div[2]/div[4]/div/select</value>
      <webElementGuid>a410fa96-a883-4ec7-86b0-07422371e618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::select[1]</value>
      <webElementGuid>8b0bcffb-67d1-48ca-b5d7-2af2237b3b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expire Month'])[1]/following::select[2]</value>
      <webElementGuid>76e3e870-e010-4498-ab98-d8094d58ae46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Code'])[1]/preceding::select[1]</value>
      <webElementGuid>8a73f2e6-3a70-4652-886b-7b612d8c7670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Address'])[1]/preceding::select[1]</value>
      <webElementGuid>ac4fdd70-7fc8-4f39-8c24-4ee7c3fd3345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[4]/div/select</value>
      <webElementGuid>272a826e-80d0-4afc-b0b9-74c908242c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AmericanExpressRequest_sourceOfFunds_provided_card_expiry_year' and @name = 'AmericanExpressRequest.sourceOfFunds.provided.card.expiry.year' and (text() = 'Year
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
' or . = 'Year
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
')]</value>
      <webElementGuid>a2b89622-94d3-4cf5-b711-caf59133caa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
