<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>membershipNumber_textBox</name>
   <tag></tag>
   <elementGuidId>a1d91e4c-7da8-455c-b139-ddbbf118cb65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='CustomerNumber'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909636 > #new-carrental-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-6 > #CustomerNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39cd41c8-a2be-4b3d-b64a-7fe5929852e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ffb55a0-c91a-4c02-b1f3-93f4c58c816d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>33fd0a96-b2ee-4f38-a4d8-101a93cd0787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerNumber</value>
      <webElementGuid>eafd7364-4908-4aa3-ac3f-f2f449c1e0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CustomerNumber</value>
      <webElementGuid>06a3cfba-8ce7-40e7-a73e-6945617647a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909636&quot;)/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6&quot;]/input[@id=&quot;CustomerNumber&quot;]</value>
      <webElementGuid>49cb03d4-a84b-4689-ae73-a0e79d047f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='CustomerNumber'])[4]</value>
      <webElementGuid>206e1eda-e034-475e-880c-207307c94ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[2]/input[2])[2]</value>
      <webElementGuid>a6abdd3f-5502-47cb-84ec-86ed65c4d53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[2]/input[2]</value>
      <webElementGuid>c655dd85-3e5a-4e07-b26d-eb8b7071b359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CustomerNumber' and @name = 'CustomerNumber']</value>
      <webElementGuid>c1426930-e69b-4a67-8a0b-5ef8174b6511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
