<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveRequest_button</name>
   <tag></tag>
   <elementGuidId>0378296a-c0b6-4b97-b822-9a5cb1e642bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Request'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-2-leg-909636 > #new-carrental-quote-noorder > #pickup-quote-0 > div.panel-body > div.row > div.col-xs-12.top-margin-15 > div > input.btn.btn-primary.btn-flight-plan.target-save-vendor-quote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37cf5519-b2e2-46b1-9688-0c7d50258d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f9835e9-3827-4eec-8474-7ecc0560008a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Request</value>
      <webElementGuid>09a26bf7-fe4e-4556-b31a-65bd9f249c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-save-vendor-quote</value>
      <webElementGuid>6d6de993-847c-44e0-8284-dee6ee5caacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-transportationtype</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8643f3e9-183d-4d66-8ab0-8507a26ab159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909636</value>
      <webElementGuid>ee02bdb8-5d89-42c5-ba95-dcebcd0aff24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quotetypeid</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>45c0472d-7a5f-45e4-8a8a-08d24b8faad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quoteid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fec0689b-a7c2-413f-9d55-51f6e3873f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-send</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8c07cc27-53c9-41bc-9d86-0783a16288f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909636&quot;)/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 top-margin-15&quot;]/div[1]/input[@class=&quot;btn btn-primary btn-flight-plan target-save-vendor-quote&quot;]</value>
      <webElementGuid>c080ce8c-4d03-4c4a-8beb-dae3fe524172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Request'])[9]</value>
      <webElementGuid>8ba4f936-b642-47ff-a2b8-40f9ccd78fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='pickup-quote-0']/div/div/div[4]/div/input)[4]</value>
      <webElementGuid>107090a1-5f24-4625-a49d-91a5a2022c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>f8ad8df2-afc3-4f47-90d0-b467c2225f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>8fd159e5-f319-470f-baf9-b5309ad71e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
