<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightsDashboard_dropDownTab</name>
   <tag></tag>
   <elementGuidId>95c841f9-2fe5-4773-b082-970a55e445ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div[2]/nav/ul/li[7]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Flights Dashboard&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18bc2846-2e34-417b-8677-366c60b4e3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Report/FlightsDashboard</value>
      <webElementGuid>efa9c8fe-00cd-4eaf-a1b7-ea2b01b40451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Flights Dashboard</value>
      <webElementGuid>7eec83bb-78ea-4742-b19f-cee44ade3fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flights Dashboard</value>
      <webElementGuid>25803a40-f2d6-449f-a65d-4735786ca8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;top_wrapper&quot;]/header[@id=&quot;header&quot;]/header[@id=&quot;header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row header flex-bottom&quot;]/div[@class=&quot;col-md-12&quot;]/nav[1]/ul[@class=&quot;navigation&quot;]/li[7]/ul[1]/li[3]/a[1]</value>
      <webElementGuid>64dcb91f-15c5-46fa-a403-25ad32dc241e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div[2]/nav/ul/li[7]/ul/li[3]/a</value>
      <webElementGuid>b2dbcb36-7362-449a-99e8-0121a5d6297c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Flights Dashboard')]</value>
      <webElementGuid>90561ab0-80a0-41c5-81e1-2806702681c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Declarations'])[1]/following::a[1]</value>
      <webElementGuid>15b7ff1c-268c-4b39-b80f-9896a079a1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Types'])[1]/following::a[2]</value>
      <webElementGuid>1baf4394-771a-4063-828e-24a22ca46d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead Report'])[1]/preceding::a[1]</value>
      <webElementGuid>6653d28c-3258-43e9-bc5e-a712cd964d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::a[2]</value>
      <webElementGuid>dd8b09b4-f2d7-4086-aa85-cba2c47f3b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Flights Dashboard']/parent::*</value>
      <webElementGuid>f23b9cab-3240-4d3a-9600-3f342ea96e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Report/FlightsDashboard')]</value>
      <webElementGuid>b47f8a8b-24ca-4420-a6dd-612f0ecd3365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[3]/a</value>
      <webElementGuid>f83ffa58-2e6a-4fcf-9006-d978425a4bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Report/FlightsDashboard' and @title = 'Flights Dashboard' and (text() = 'Flights Dashboard' or . = 'Flights Dashboard')]</value>
      <webElementGuid>999dbdf6-b4c9-4f73-af3c-1a297df41378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
