<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>approx.Wgt_textBox</name>
   <tag></tag>
   <elementGuidId>177eab87-6265-4590-b9f0-3ab5311d9e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_2__Weight']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__Weight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d1dbc25-9b85-4164-affb-ec71b190e339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>04fe5726-fd5b-4d25-b9a9-1585fd798541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>36b30325-bfed-42ec-be64-9f167f02f291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df620379-dcaf-404a-8a43-02b4bd5a17be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validity.valid||(value='');</value>
      <webElementGuid>5ea38be0-ca10-4177-9704-3e1fa7e4d962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-weight</value>
      <webElementGuid>fde29daf-08cd-4299-8a10-55e1412b59e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e02cba76-7b3e-4e84-9b93-24c97afcace6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Approx. Wgt. field is required.</value>
      <webElementGuid>51f98741-abdc-4a4f-8313-489f85bb301e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__Weight</value>
      <webElementGuid>94b47c2d-2485-49cb-b1e7-79c8c4accdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].Weight</value>
      <webElementGuid>6b109efd-b8c8-433f-bceb-b2460e955338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__Weight&quot;)</value>
      <webElementGuid>3784f57c-6cc6-4e5b-816e-b339bab5fb3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_2__Weight']</value>
      <webElementGuid>d0ef7d7a-a337-4d99-954c-0fd5b594a4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[2]/div[3]/div/input</value>
      <webElementGuid>074f4a8f-5047-4a34-8826-12449184e8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div[2]/div[3]/div/input</value>
      <webElementGuid>052d7f0f-5ad1-4102-aa1f-e71cfade2f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Legs_0__Passengers_2__Weight' and @name = 'Legs[0].Passengers[2].Weight']</value>
      <webElementGuid>5922c32e-0970-4787-88ea-b56ab1ae8905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
