<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gender_dropDown</name>
   <tag></tag>
   <elementGuidId>6e53bd32-7436-4b49-954d-9cbf5f4b976e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Legs_0__Passengers_2__Gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__Gender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1002a822-f0f1-4478-b64d-5c9c006beead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control target-pax-gender</value>
      <webElementGuid>aa85d18d-1dc0-4fcc-b602-54b9fca3783b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c616b79c-3bf6-4e31-8571-50d40ce1ee48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Gender field is required.</value>
      <webElementGuid>1725a213-5783-4743-a8f1-383320444fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__Gender</value>
      <webElementGuid>79cc286d-947a-4ab4-860a-f89ef9a2fe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].Gender</value>
      <webElementGuid>6e3f5cba-d7fb-4e2c-b490-bb4429b3471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Gender
                                    M
                                    F
                        </value>
      <webElementGuid>d7bfc30e-2845-4075-b62f-f1a51092ff52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__Gender&quot;)</value>
      <webElementGuid>9e59945e-26aa-456c-a2d7-7327c8c7373f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Legs_0__Passengers_2__Gender']</value>
      <webElementGuid>b069a376-67c9-466e-a8a6-99b73167ddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div[2]/div[4]/div/select</value>
      <webElementGuid>a2ed59f6-13c1-4214-8dd8-b6b4409eae39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[5]/following::select[1]</value>
      <webElementGuid>d41d22bb-ac95-4f95-9e12-50d83ec6e72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[3]/preceding::select[1]</value>
      <webElementGuid>12eef9d9-84b7-46e8-a31b-546f33bde61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div[2]/div[4]/div/select</value>
      <webElementGuid>ff2a0d46-b838-4858-84cf-83b5ac449beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Legs_0__Passengers_2__Gender' and @name = 'Legs[0].Passengers[2].Gender' and (text() = '
                            Gender
                                    M
                                    F
                        ' or . = '
                            Gender
                                    M
                                    F
                        ')]</value>
      <webElementGuid>8dea65ef-ca10-4a8a-beb8-3cb88b0ab75f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
