<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>last_textBox</name>
   <tag></tag>
   <elementGuidId>e9911f76-b527-4065-aa3e-4c59f9f76576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_2__LastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_2__LastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ea638f2-5ca8-40d6-81cb-c00bfd5eaf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>0bbea7b9-3105-49c9-a670-138499082fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control</value>
      <webElementGuid>9e843e13-9bb4-4c47-a8e7-1530099778fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>138bcc74-0cb5-4ff1-9d1e-901443958a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63ab8a19-1a31-4d7b-a743-51d4b70a12e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Last must be a string or array type with a maximum length of '64'.</value>
      <webElementGuid>32da6dd6-c376-47e1-bc1d-8477bda0a484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>d954135b-4d1c-44d2-92a9-24ca60592d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Last field is required.</value>
      <webElementGuid>0a42152b-9c79-4a72-88b5-81a55d46a936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_2__LastName</value>
      <webElementGuid>6235ae09-41bc-4c73-9a53-8518a156d750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>4aed9a6e-a14e-40ff-a453-7645393c8b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[2].LastName</value>
      <webElementGuid>0e44c299-9139-4394-848a-4fc57f75af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_2__LastName&quot;)</value>
      <webElementGuid>f2903fc1-5a1c-416c-8293-bad85d54140d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_2__LastName']</value>
      <webElementGuid>fa39918d-3f96-44b4-a461-f526ed4533d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-3']/div[3]/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>fd35bc93-deb3-4b35-aceb-7efbded4d2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>644cd586-574a-4c9a-ad72-e62bd45c7c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_2__LastName' and @name = 'Legs[0].Passengers[2].LastName']</value>
      <webElementGuid>6b5dc67b-6214-4456-b8a8-de8fe924d55f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
