<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>suffix_textBox</name>
   <tag></tag>
   <elementGuidId>07b8a177-d3c9-49a4-86b7-fdb0b471e183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__Passengers_0__NameSuffix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__Passengers_0__NameSuffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05d29c18-54df-42e2-ba85-8ad1732b008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>fa4093b2-5761-4137-8dd0-e983ac1f86f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-results-input form-control</value>
      <webElementGuid>2376f485-6792-4e1e-9d37-f447573295a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57b7e909-91b4-489b-aa54-5c3f2d08120b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4249b2b-ec0a-433e-b890-c62e2ff5029a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Suffix must be a string or array type with a maximum length of '16'.</value>
      <webElementGuid>4ef0bcf3-a8bc-4ea3-9183-0d28be3312df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>4bc576d7-0e22-4aee-9078-247cece6cadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__Passengers_0__NameSuffix</value>
      <webElementGuid>43ef6d3a-ddaa-4a54-9c5e-ee7e4ff8a85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>08d7f963-bbd8-4843-8303-b88f3cc4be5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].Passengers[0].NameSuffix</value>
      <webElementGuid>5186914d-7ee0-41bb-ba67-edc276cf7d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__Passengers_0__NameSuffix&quot;)</value>
      <webElementGuid>75014ab2-8712-4d6f-8cd9-41b390c79a53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__Passengers_0__NameSuffix']</value>
      <webElementGuid>f899063f-396a-4fdc-a573-f1514f254048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passengercontainer-leg-1-number-1']/div[3]/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>9fa1f34b-b5de-45e2-ba52-9997710f2182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>4f03911f-8755-44fe-a4a5-7efd55f3d75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Legs_0__Passengers_0__NameSuffix' and @name = 'Legs[0].Passengers[0].NameSuffix']</value>
      <webElementGuid>da1b8c34-d48a-436f-b454-c493b87ec946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
