<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>decline_button</name>
   <tag></tag>
   <elementGuidId>74863d61-f309-44c7-8ab6-c4bc4b93ee03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'DECLINE' or . = 'DECLINE')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.reject-button.itinerary-button.target-itinerary-review-decline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdc8726f-567c-4ce1-b6e3-3b349eb74aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>344c83fd-196d-488e-ac1b-83c700449566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn reject-button itinerary-button target-itinerary-review-decline</value>
      <webElementGuid>dae9b993-4574-48b9-84a2-26960e5d73d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>a391afb4-0714-4036-b255-3dd498afce6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>a065c5ab-99e5-4141-ab71-41fbb8f445f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DECLINE</value>
      <webElementGuid>9ff776f7-abaa-4124-80b3-8476fff4e6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itinerary-container&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 accept-changes-div&quot;]/div[1]/button[@class=&quot;btn reject-button itinerary-button target-itinerary-review-decline&quot;]</value>
      <webElementGuid>6c9fe11c-0449-4686-842d-aa9e0495f43e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>38245229-9430-4a6b-b7ea-f26a2cb76868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itinerary-container']/div[2]/div/div/button</value>
      <webElementGuid>c390ca06-d605-41e4-a389-bc81ae8d5cc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='changes'])[1]/following::button[1]</value>
      <webElementGuid>d49c61bf-c255-48b4-9576-8825d2cef683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$86,791.37'])[1]/following::button[1]</value>
      <webElementGuid>89f20b5a-73e2-4884-aec4-6dc9f5fb2375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCEPT'])[1]/preceding::button[1]</value>
      <webElementGuid>8b63fcff-0ed2-4e9c-acf7-7ec20d424e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to decline these changes? This action cannot be undone.'])[1]/preceding::button[2]</value>
      <webElementGuid>922368fc-345b-4b5d-a26a-4cb7e3f1efd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DECLINE']/parent::*</value>
      <webElementGuid>bb900ce5-f25f-4b17-82bf-a76a88580bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>980b3ce6-ec24-48b5-abf9-02ea0c9d7566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'DECLINE' or . = 'DECLINE')]</value>
      <webElementGuid>87831659-dd98-4938-8e2c-c1ec7bfc8da1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
