<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_textBox</name>
   <tag></tag>
   <elementGuidId>314edbed-38bf-482c-b56c-c620410c49a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmsFilterViewModel_FilterEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AmsFilterViewModel_FilterEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4e22629-eee9-4afc-b4c9-26cc1646b7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-filter-element</value>
      <webElementGuid>df12f731-25e5-4d2e-888c-816010d537e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>27103537-97cc-4d37-8f3c-2cc5cd7ed5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4d3a0994-bab4-4db2-a798-86a7f77ffc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-email</name>
      <type>Main</type>
      <value>The Email field is not a valid e-mail address.</value>
      <webElementGuid>34947ff4-48b2-4ae8-8d61-fccb6b821fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmsFilterViewModel_FilterEmail</value>
      <webElementGuid>02c571ec-8605-469b-859d-eac239b58dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmsFilterViewModel.FilterEmail</value>
      <webElementGuid>266f8241-87a1-4b3f-aef1-5c8b60c5a681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmsFilterViewModel_FilterEmail&quot;)</value>
      <webElementGuid>348a6d18-3cbe-4d7d-99b0-6046c1d28cee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmsFilterViewModel_FilterEmail']</value>
      <webElementGuid>f5e912eb-2c38-4681-8b04-beae86b2b0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>a93b3cdd-ec61-4c60-95f1-b62c9e6734da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>c2a6e366-ef9f-4c07-9e2d-42bf31303129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'AmsFilterViewModel_FilterEmail' and @name = 'AmsFilterViewModel.FilterEmail']</value>
      <webElementGuid>37ae96a1-d842-4858-9598-4ab30cce769d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
