<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>email_object</name>
   <tag></tag>
   <elementGuidId>585a5461-b5d0-40fd-b9e3-e0fbe2607f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='Operator.PopupContactEmail($(this));'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2b50f88-dbef-42a9-aa4b-f5d768d31245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>fa7ca5aa-ee53-4b22-8b54-ec14d46a07ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Operator.PopupContactEmail($(this));</value>
      <webElementGuid>0c3fb7c6-e50c-4887-8780-f08b36f197f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-id</name>
      <type>Main</type>
      <value>1037</value>
      <webElementGuid>bb717937-f312-444b-b7aa-6b62290391d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-contact-id</name>
      <type>Main</type>
      <value>12229</value>
      <webElementGuid>2c2ad724-a77c-4dae-9b09-0ed61e6ebcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-email-id</name>
      <type>Main</type>
      <value>128452</value>
      <webElementGuid>45054ae6-8126-44ad-a91a-e611866a7ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>of-link-black</value>
      <webElementGuid>07eb9d4d-6a2f-435b-ad50-155e45737f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                sdfas@gmail.com (Personal)
                                            </value>
      <webElementGuid>1ca505f6-3530-4418-a4bf-966031fb6dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Contacts&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;ContactsDynamic&quot;]/div[@class=&quot;row&quot;]/div[@id=&quot;ContactsDynamic&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table ams-table black&quot;]/tbody[1]/tr[4]/td[4]/a[@class=&quot;of-link-black&quot;]</value>
      <webElementGuid>9b045db9-c6f5-4583-888b-5ac320072e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='Operator.PopupContactEmail($(this));'])[8]</value>
      <webElementGuid>bcdc33ee-130d-4404-aed3-96c4092ee7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContactsDynamic']/div[3]/table/tbody/tr[4]/td[4]/a[2]</value>
      <webElementGuid>121075d4-4295-4c12-a8e0-eb8700630178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'sdfas@gmail.com (Personal)')]</value>
      <webElementGuid>2a7ccd26-fec4-45bd-b1e5-31286075d723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KatalonContact3@gmail.com (Business)'])[1]/following::a[1]</value>
      <webElementGuid>76c70481-0a4e-4d1b-a550-c1801b40a48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Email'])[4]/following::a[2]</value>
      <webElementGuid>b1465973-5393-4d31-9d8a-1f9dae1cc693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[4]/preceding::a[1]</value>
      <webElementGuid>d2f96041-ad47-4cc2-b4a6-979f53d2290c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[3]/preceding::a[2]</value>
      <webElementGuid>a6141bac-2886-473f-a350-52fa39cb0c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sdfas@gmail.com (Personal)']/parent::*</value>
      <webElementGuid>e2260613-0847-4610-9792-c1d2c5b33529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[27]</value>
      <webElementGuid>f57422ba-758a-4e7d-8b68-b5266f7bf718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>6aa5637a-e9a2-40d6-8e1e-5230bd7bd0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                                sdfas@gmail.com (Personal)
                                            ' or . = '
                                                sdfas@gmail.com (Personal)
                                            ')]</value>
      <webElementGuid>8b8cff1e-34ae-40d0-ad54-02b3443e14e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
