<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>removeEmail_button</name>
   <tag></tag>
   <elementGuidId>aba66879-aa23-46f0-bcb8-825f0e96f6f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Remove Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.float-right > input.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a55f5879-aa84-49d3-855a-cdf463c3737c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>808f2157-353b-4239-8429-0b0707b8ffdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3f35db7-6e5b-4e5e-90a9-c8ee099fbac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Operator.ContactEmailRemove();</value>
      <webElementGuid>fd76d0e5-a171-43a0-b6e4-2390550e990c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remove Email</value>
      <webElementGuid>c730bc95-ee07-4a9c-8756-c76b4387532f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operator-contact-form&quot;)/table[3]/tbody[1]/tr[1]/td[1]/div[@class=&quot;float-right&quot;]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>7604eeb2-fa30-4440-bb41-0ff2f9ff531e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Remove Email']</value>
      <webElementGuid>30b66b61-530f-41a5-88c5-ac5562674ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='operator-contact-form']/table[3]/tbody/tr/td/div/input</value>
      <webElementGuid>89724258-86c4-435f-b8c4-768b2b2e8dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/div/input</value>
      <webElementGuid>066c7685-86ce-4bb6-918b-86efacf9c100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>02e14405-0b59-49dd-b668-cffa0946acb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
