<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>removePhone_button</name>
   <tag></tag>
   <elementGuidId>9452d51a-0cf1-4fa4-8b65-beebb006f0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Remove Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.float-right > input.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afdb2129-41d7-426c-9133-206af46ad0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5240f644-815a-4fa9-8665-4e9822ea8dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cc06995-5096-4120-95f0-ac17948b2426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Operator.ContactPhoneRemove();</value>
      <webElementGuid>c269254c-cdbc-4a17-b309-4edddd4901c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Remove Phone</value>
      <webElementGuid>1c6d17d3-8c22-445e-94c5-2d627128cf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;b-ajax-wrapper&quot;]/table[3]/tbody[1]/tr[1]/td[1]/div[@class=&quot;float-right&quot;]/input[@class=&quot;button&quot;]</value>
      <webElementGuid>3fb68c58-8cd5-4c28-b43e-d518b26a90e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Remove Phone']</value>
      <webElementGuid>3b1230ba-5aa6-4e43-91d8-1fba2cc7c292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup']/div/div/table[3]/tbody/tr/td/div/input</value>
      <webElementGuid>cacf0362-42b2-4cfd-b317-5531dbb68ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/div/input</value>
      <webElementGuid>98b7240e-c039-4683-b323-eb97c155e65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>12e1e1d6-c4a0-4038-a452-97d0b116a1a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
