<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Select</name>
   <tag></tag>
   <elementGuidId>ca377bf2-681e-4219-b1fe-79dd336a4971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BAJ_Aircraft']/div[17]/div/div/div/div[3]/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>388235f0-f37d-46ce-99e4-0fab07442443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>837806da-a104-41ba-999f-1080fc5dbd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn aircraft-select-button target-baj-button-aircraft-select</value>
      <webElementGuid>83587d45-d4f5-4bbb-991a-679e904b92fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aircraft-id</name>
      <type>Main</type>
      <value>7118</value>
      <webElementGuid>3271b9da-1bf2-4400-a1e2-56af2d8bcc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Select 
                                </value>
      <webElementGuid>d842b1fc-e7c6-4c46-9058-9a11f61c95c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAJ_Aircraft&quot;)/div[@class=&quot;col-xs-12 baj-results-aircraft clearfix colNoSideMargins&quot;]/div[@class=&quot;col-xs-12 colNoSideMargins&quot;]/div[@class=&quot;media aircraftList&quot;]/div[@class=&quot;aircraftList-top&quot;]/div[@class=&quot;media-body&quot;]/div[@class=&quot;aircraft-results-right&quot;]/div[@class=&quot;bookingDetails&quot;]/a[@class=&quot;btn aircraft-select-button target-baj-button-aircraft-select&quot;]</value>
      <webElementGuid>0a122ce0-ac46-43f6-a829-c1779320fb7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAJ_Aircraft']/div[17]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>1da04972-acca-45e1-9cf6-eab6a32ccb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Select')])[17]</value>
      <webElementGuid>54cdf66e-66e7-478c-bf51-48658fa64950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16,355'])[8]/following::a[1]</value>
      <webElementGuid>9cd13ddd-d5d9-474e-9e5f-99497b6b2996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFETY RATING'])[17]/following::a[1]</value>
      <webElementGuid>7a48059a-e319-419c-87d3-293b1c50bd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer'])[17]/preceding::a[4]</value>
      <webElementGuid>a54eea43-61f2-48c3-9722-69d6bf91cbfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CESSNA'])[10]/preceding::a[4]</value>
      <webElementGuid>e0bd57cf-8a96-4d9e-be3a-7c19069f36d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[86]</value>
      <webElementGuid>88eddb8c-5e5d-4e98-bb31-cf20826ccac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div/div[3]/div[2]/div/a</value>
      <webElementGuid>a3b39a54-f745-4b83-8ef3-0eeb1088cb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = '
                                    Select 
                                ' or . = '
                                    Select 
                                ')]</value>
      <webElementGuid>ec4834ca-96cd-43ff-b877-0b03bf0a08da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
