<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>budgetOverageR_textBox</name>
   <tag></tag>
   <elementGuidId>f190cd2f-b441-46e9-9642-068fb61cf47e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-1-leg-909597 > #catering-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-7 > div.row > div.target-enter-quoted-amount > div.col-xs-12.target-div-overage-reason > div.target-quoted-amount-div > #OverageReason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='OverageReason'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e8c0c0fc-bd53-46f2-ba08-865862c6affb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>8d56c68e-377e-44fe-8133-4428ab0d6b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OverageReason</value>
      <webElementGuid>08b35d86-d536-4744-ada8-a29c2bb400e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909597&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;target-enter-quoted-amount&quot;]/div[@class=&quot;col-xs-12 target-div-overage-reason&quot;]/div[@class=&quot;target-quoted-amount-div&quot;]/textarea[@id=&quot;OverageReason&quot;]</value>
      <webElementGuid>d304492a-0d7c-4fce-b69c-7f2dde1b3a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='OverageReason'])[15]</value>
      <webElementGuid>ef3571e9-77b0-475a-8a4a-8391e7406b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='catering-quote-0']/div/div/div[3]/div[3]/div[3]/div/div/textarea)[3]</value>
      <webElementGuid>880b853a-62b8-42c8-b2c2-89bcefe56e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[2]/div[2]/div[3]/div[3]/div/div/div[3]/div[3]/div[3]/div/div/textarea</value>
      <webElementGuid>39a0d6dd-b94b-4a91-ab1e-4a6384e0d7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'OverageReason' and @name = 'OverageReason']</value>
      <webElementGuid>19b0bfc9-bd6e-4208-a660-3b637f0a836a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
