<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skipEmail_button</name>
   <tag></tag>
   <elementGuidId>5f685680-ed42-438b-902c-29ce4de3124a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-1-leg-909597 > #catering-quote-0 > div.panel-body > div.row > div.col-xs-12.col-sm-7 > div.row > div.col-xs-6 > input.btn.btn-small.target-toggle-verbal-quote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Skip Email'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9160d21c-095c-4866-bcc3-0c7ba876c4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9fb624e-9d41-4038-ae2b-11359bd601a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Skip Email</value>
      <webElementGuid>5ab7680e-9468-4a07-aab0-f9c87eccbec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small target-toggle-verbal-quote</value>
      <webElementGuid>e21731fd-160c-4fd8-af08-390da6ab92b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Ams.ToggleVerbalQuote(this)</value>
      <webElementGuid>e9424f11-8b74-46fd-9645-a58f7ffc00fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-1-leg-909597&quot;)/div[@id=&quot;catering-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6&quot;]/input[@class=&quot;btn btn-small target-toggle-verbal-quote&quot;]</value>
      <webElementGuid>fb3ac8ed-4711-49be-bfb3-b0c93ea1daec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Skip Email'])[7]</value>
      <webElementGuid>c34445eb-de79-4725-a502-370e6826159c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='catering-quote-0']/div/div/div[3]/div[3]/div[2]/input)[3]</value>
      <webElementGuid>d17bbceb-4445-4202-8f6b-6b3fd100bdcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div[2]/div[2]/div[3]/div[3]/div/div/div[3]/div[3]/div[2]/input</value>
      <webElementGuid>d26d3130-fbec-41de-9065-f8454a09b6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>16913a63-d1b5-4246-95cb-c193e0c98173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
