<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>date_textBox</name>
   <tag></tag>
   <elementGuidId>75fa1574-6c99-4adf-8f5f-f0d0e734726f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__OriginDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__OriginDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e9d2516-14a3-4f6f-9a7d-6a7a1c313b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-date-picker black-tighter-input target-flight-plan-input-origin-date form-control hasDatepicker</value>
      <webElementGuid>d87d34dd-ac53-47dc-9f9a-4e808233d800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dfe5f5b2-c73f-49d3-924c-1fc638e2a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Date/Time field is required.</value>
      <webElementGuid>d8586a32-6862-48c9-a576-852644fc6804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__OriginDate</value>
      <webElementGuid>10456cbf-acfc-4037-a94f-de350a764a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].OriginDate</value>
      <webElementGuid>7a4a4a87-1c56-45e6-9417-a1afe9278020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91b4478b-9b51-464c-afc3-a0c7ccbc2e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>05/06/2023</value>
      <webElementGuid>e1096068-ae87-4081-93bd-0af54a4d26a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__OriginDate&quot;)</value>
      <webElementGuid>dbea24e6-7592-4cc4-ab18-e24298bed44f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__OriginDate']</value>
      <webElementGuid>5f5aee42-5b79-45e3-a16d-7e141950228e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909767']/div[6]/input</value>
      <webElementGuid>37b0faa0-b21a-4913-a434-b79665784dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[6]/input</value>
      <webElementGuid>7706a1f0-1317-4f83-8fb9-6642fde1bc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__OriginDate' and @name = 'Legs[1].OriginDate' and @type = 'text']</value>
      <webElementGuid>ed3ec7fc-2b01-4c12-ae1a-94a9325478bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
