<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>from_textBox</name>
   <tag></tag>
   <elementGuidId>d0c5f929-bf3a-4e50-937e-447353ab234c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_1__AirportOriginIdent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_1__AirportOriginIdent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b8085e5-b784-4770-926b-4c89e79b1b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-airport-entry black-tighter-input form-control ui-autocomplete-input</value>
      <webElementGuid>84298b41-aca1-4589-bf55-ab1fa441fc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_1__AirportOriginIdent</value>
      <webElementGuid>c2dc0be6-3b50-4297-ac83-680bad7179e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[1].AirportOriginIdent</value>
      <webElementGuid>c01d78f3-4d97-482e-88c3-0c864dd43cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56f0fc45-9b72-4d54-8379-1d50e02e0774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KATL</value>
      <webElementGuid>515423fc-e687-459f-9fc8-50c905b56347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>76648d01-fb80-4c82-8d99-362b2db4229b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_1__AirportOriginIdent&quot;)</value>
      <webElementGuid>b5387923-5ae8-4e19-a9a4-fedcb47601ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_1__AirportOriginIdent']</value>
      <webElementGuid>75fee997-5c05-4a44-ba83-bdbd2bc66cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-flight-leg-id-909767']/div[3]/input</value>
      <webElementGuid>254a0b0a-7aa2-4fce-853c-bd42cd080926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/div[2]/div[3]/input</value>
      <webElementGuid>b1749ccb-737a-4740-ba39-c1f41ba92ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_1__AirportOriginIdent' and @name = 'Legs[1].AirportOriginIdent' and @type = 'text']</value>
      <webElementGuid>c3a5d1c7-a41f-45ad-836e-e282a0f71e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
