<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dessertPlatterRequest_button</name>
   <tag></tag>
   <elementGuidId>4b749a5f-3a59-4774-be84-3e6e34e7f2e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='DessertPlatter']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DessertPlatter > button.catering-select-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8922af0b-4e6c-4be6-aa80-194c67d13896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-select-button</value>
      <webElementGuid>297f38c4-6279-423a-9033-08192208a72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Dessert Platter</value>
      <webElementGuid>195b39f5-0753-4492-aa75-8c0073bd80e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>fa969562-45ae-4417-a6a1-59342cf32bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>152ca92b-eca7-49a3-812c-5a38e51c5281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>8f0fcd9a-0a48-484a-959c-2f00847a3adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request for Leg 1</value>
      <webElementGuid>349442dc-9f34-40ae-b4f6-aabed6de5043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DessertPlatter&quot;)/button[@class=&quot;catering-select-button&quot;]</value>
      <webElementGuid>712d6a65-e857-44e9-8cb0-f16592dd5887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='DessertPlatter']/button</value>
      <webElementGuid>d7e79382-8d61-4e63-a6f3-2bb8f7735c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[16]/following::button[1]</value>
      <webElementGuid>aad29190-2a9a-4bf3-ba74-b37b05f68acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1)'])[17]/preceding::button[1]</value>
      <webElementGuid>e39a8865-7a65-4cdc-aff5-f560ca1475d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beverages'])[1]/preceding::button[1]</value>
      <webElementGuid>11876c1c-dc3d-47f0-9e70-16094c7c3863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/h4[5]/button</value>
      <webElementGuid>0d18c92c-7caf-4e62-9449-59d5544cafe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request for Leg 1' or . = 'Request for Leg 1')]</value>
      <webElementGuid>480ad80e-1796-43eb-82e1-b162ad719fc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
