<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saveRequest_button</name>
   <tag></tag>
   <elementGuidId>2843bae3-47c9-43af-a20b-ea34ff2469db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#target-new-quote-type-3-leg-909637 > #new-carrental-quote-noorder > #dropoff-quote-0 > div.panel-body > div.row > div.col-xs-12.top-margin-15 > div > input.btn.btn-primary.btn-flight-plan.target-save-vendor-quote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Save Request'])[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ce1718d-fac0-4271-96b9-be9a6f83800a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f63df061-e527-4858-a713-cb8080e53262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Request</value>
      <webElementGuid>98dbacdb-21d4-4cf8-a969-b7d812cfee59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-flight-plan target-save-vendor-quote</value>
      <webElementGuid>728bd695-9f7f-472e-b0e6-e1913d68a693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-transportationtype</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>519af323-a101-4e95-bc02-c4c61d734592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909637</value>
      <webElementGuid>260a2356-9fe2-4a7f-afcb-eccd0fc4f31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quotetypeid</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>97167f0c-8141-4f12-8f4f-2d55e9d9fd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quoteid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>046cb7c2-7ecf-4f22-a5f9-e92090622d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-send</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bebd41b1-c263-4fb1-b64f-7ba4e3bdea42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;concierge-quotes-accoridion-leg-3&quot;)/div[@class=&quot;panel request&quot;]/div[@id=&quot;dropoff-quotes-leg-3&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;dropoff-quotes-workarea-leg-909637&quot;]/div[@id=&quot;dropoff-quotes-container-leg-909637&quot;]/div[@id=&quot;target-new-quote-type-3-leg-909637&quot;]/div[@id=&quot;new-carrental-quote-noorder&quot;]/div[@id=&quot;dropoff-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 top-margin-15&quot;]/div[1]/input[@class=&quot;btn btn-primary btn-flight-plan target-save-vendor-quote&quot;]</value>
      <webElementGuid>97bc3f5e-fa9b-46ec-a43e-df60ae6df4d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Save Request'])[18]</value>
      <webElementGuid>5c2ca3d8-ad55-48b5-8bcc-11e024be75bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='dropoff-quote-0']/div/div/div[4]/div/input)[13]</value>
      <webElementGuid>e77c739b-f8c0-4825-983d-58834f1e9379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div[2]/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>7ec31b57-e47e-48eb-8c72-95debc1b48c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>fddac78a-10a0-4c44-bf3b-39ab92c9305b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
