<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_textBox</name>
   <tag></tag>
   <elementGuidId>c22d7c58-541a-495f-948a-37267d4d503d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_City']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_City</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29fab258-d909-48d6-86d5-451177625974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19d6f182-f082-4e73-aa7e-64c3d13e7671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8800c653-d905-4653-af5a-9b6843c3af44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address dropoff-address ui-autocomplete-input</value>
      <webElementGuid>a5cb48d4-9f32-43f3-a688-f78f38866aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa8f3fa9-2e6e-4ef4-994c-064a249549bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7da0e737-1bed-4272-88ee-64380ff47bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field City must be a string or array type with a maximum length of '30'.</value>
      <webElementGuid>3d4debe9-a95e-4189-b916-2c9d24afa2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>36e8ec2b-a949-4f5d-be65-34a395ffc2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_City</value>
      <webElementGuid>73187e1f-23b3-45ba-bd5c-d70262795740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4b6fce4e-72b3-481d-9c7a-0529903326c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.City</value>
      <webElementGuid>2847151d-a127-41ee-bd52-43a876a113b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_City&quot;)</value>
      <webElementGuid>402aa0bb-b415-4ef8-affc-e25702bd77ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_City']</value>
      <webElementGuid>fefba2eb-9bfb-4abf-8a4b-abfd13f81ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-dropoffform']/div/div/div[3]/input</value>
      <webElementGuid>7cf68882-27fa-4514-87db-ad181169df5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div[3]/input</value>
      <webElementGuid>49f27fc0-0614-479b-8df8-97ea45182e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_City' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.City']</value>
      <webElementGuid>f3de72c4-ac89-4c4c-a916-5dbf44cf7d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
