<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_textBox</name>
   <tag></tag>
   <elementGuidId>de9badb6-655c-49ff-8067-c755649e2858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c3cf34c-3eee-453f-95cb-f8fc1c871cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8de1674d-3495-4e60-81bb-fc450360c07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1d68a593-dcbc-4619-82dd-fcd755f50d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-street-address dropoff-address ui-autocomplete-input</value>
      <webElementGuid>fd5ac9b7-0134-4c26-9d1e-5fb56194818b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57075f41-856f-4bf8-a99f-dcecc8cb1563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0496ae9d-f1b1-4a74-b508-26df7fb467c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Country must be a string or array type with a maximum length of '30'.</value>
      <webElementGuid>e810d860-6734-42f2-bb73-8058f9f04c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>7fd8567a-1657-4185-bd3e-5ea9b6f6f610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country</value>
      <webElementGuid>8e02f334-d103-42a9-86d9-fe001474646c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c1fc11f6-a16e-4c60-ae26-3c41d07bdeda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.Country</value>
      <webElementGuid>60356812-f721-4ab8-804c-49f3b9cb0129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country&quot;)</value>
      <webElementGuid>70254db7-9ab4-43e1-bde8-7d6d7f4a7023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country']</value>
      <webElementGuid>2c531ab8-7c0e-410e-a3c4-5ace61fc5deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-dropoffform']/div/div/div[6]/input</value>
      <webElementGuid>5d51f814-0e7f-43f2-b58d-c19ea03924e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div[6]/input</value>
      <webElementGuid>08bcd411-98b2-4fb0-80b3-dce911b656be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffFullAddress_Country' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffFullAddress.Country']</value>
      <webElementGuid>0f57e157-05f5-4f32-b41a-b2924e2c117e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
