<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>droppOffInstructions_textBox</name>
   <tag></tag>
   <elementGuidId>65d374f5-651f-4630-b39b-c95eee1dc0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffInstructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffInstructions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6700f191-219f-4d8e-bcc6-ae80306435e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>30f586ac-9457-47f4-971c-de42ead3a753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5f7e385-1f51-40b8-8998-dea1d7e7953d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffInstructions</value>
      <webElementGuid>60d99394-1383-4251-a7ec-bfa47e1acd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffInstructions</value>
      <webElementGuid>d93b8dc0-e8f9-45ac-9fae-be9c314e12e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffInstructions&quot;)</value>
      <webElementGuid>5d11d3c7-2f18-4c8c-bd31-ed53d70fc8dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffInstructions']</value>
      <webElementGuid>50dcbcb8-441a-458b-80fc-e126328fe894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Leg-1-dropoffform']/div/textarea</value>
      <webElementGuid>9303b078-d9b3-4f73-8025-e7647d8bebba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/textarea</value>
      <webElementGuid>e5f63269-d7a6-4f5a-92f7-42b1a965fd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'FlightPlan_Legs_1__ActiveConciergeOrder_ExecutiveDropoffInstructions' and @name = 'FlightPlan.Legs[1].ActiveConciergeOrder.ExecutiveDropoffInstructions']</value>
      <webElementGuid>a43642e0-6e8b-4a1c-866d-83826ff8ea42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
