<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorOk_button</name>
   <tag></tag>
   <elementGuidId>e1c7f4f7-6edf-4b60-99fe-f5ffee57ab17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='target-scroll-to-luggage-pets-firearms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#target-scroll-to-luggage-pets-firearms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dcc0e37-8779-4527-bc4a-b1c05b367aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>295ef569-d5dd-40f5-b14c-d283d490eab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>target-scroll-to-luggage-pets-firearms</value>
      <webElementGuid>44b19d86-e549-4173-b5b1-3fbd406d1f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn-small</value>
      <webElementGuid>11b0a68f-1980-4cfe-8a17-484edd8098fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>a15752fe-611e-4884-b8b4-a9c0f82b1900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-scroll-to-luggage-pets-firearms&quot;)</value>
      <webElementGuid>6391365a-9a54-4f16-a913-27a397bf979a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='target-scroll-to-luggage-pets-firearms']</value>
      <webElementGuid>636f07aa-fff2-4e73-b3f6-2f9b0610066b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='target-luggage-firearms-pets-error-modal']/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>66a76e8d-9e69-4832-97ce-932845844fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>140c7bb9-9aac-4243-978e-40526e5e28f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'target-scroll-to-luggage-pets-firearms']</value>
      <webElementGuid>df612f8b-f5b2-4571-a3d9-59925cedfd57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
