<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>luggage_checkBox</name>
   <tag></tag>
   <elementGuidId>4e692890-ad2a-4eab-b7b2-6f1328245f61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Legs_0__LuggageDescriptionNone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Legs_0__LuggageDescriptionNone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>610f116f-2065-4c6d-9825-5f856ac2e754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-custom form-check-input target-luggage-nonecheckbox</value>
      <webElementGuid>f0174edc-ef86-462e-b257-59484d7bbf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ea91d85-8338-4f02-9a9a-2259a9275790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LuggageDescriptionNone field is required.</value>
      <webElementGuid>d086fee6-d3c8-47d8-b63f-8764a9954fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Legs_0__LuggageDescriptionNone</value>
      <webElementGuid>3576f3b0-7bb3-437c-bc37-76dfc1154b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Legs[0].LuggageDescriptionNone</value>
      <webElementGuid>f44fa63a-cdb0-433a-abe3-44a90f1bf2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>520ae627-6d5d-4335-b122-3dd5be4d1c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c7993213-3959-4932-b807-18f04da51bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Legs_0__LuggageDescriptionNone&quot;)</value>
      <webElementGuid>01debb40-f358-4953-8ea4-66b081b666a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Legs_0__LuggageDescriptionNone']</value>
      <webElementGuid>34ba8ae7-0678-46ae-a204-6f794908f383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='baj-results-leg-luggage-div']/div/div/div[3]/div/div/input</value>
      <webElementGuid>e4b63819-2fed-478a-82a8-a83a70b16024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div/input</value>
      <webElementGuid>87d67294-6ea1-468d-9654-81d2ec3d8d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Legs_0__LuggageDescriptionNone' and @name = 'Legs[0].LuggageDescriptionNone' and @type = 'checkbox']</value>
      <webElementGuid>ba37dcf3-aade-411c-9ec5-cf2f45704027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
