<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>caesarDressing_checkBox</name>
   <tag></tag>
   <elementGuidId>7e076a97-2b6e-484f-abfb-30234d717a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='GardenSalad-options']/li[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c1cb07ee-e762-41a6-973d-3fb9678828fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>GardenSaladCaesar Dressing</value>
      <webElementGuid>e8f94d8a-8daf-4518-95ae-5cb904c0a24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Caesar Dressing</value>
      <webElementGuid>f944fddc-a3c2-454c-b0e2-afaeadbe169f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GardenSalad-options&quot;)/li[3]/label[1]</value>
      <webElementGuid>ddd96424-0474-49ea-a20f-0737e754abdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='GardenSalad-options']/li[3]/label</value>
      <webElementGuid>74798079-c500-4bf0-9ae8-b8407082e8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Dressing'])[2]/following::label[1]</value>
      <webElementGuid>d9b01ab0-04de-4104-aad0-f5796df7569b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[15]/following::label[2]</value>
      <webElementGuid>44754f64-5966-4298-82a2-2686c34ef1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blue Cheese Dressing'])[2]/preceding::label[1]</value>
      <webElementGuid>63ff56b3-fefd-45f2-b0c8-c916ce3804f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinaigrette Dressing'])[2]/preceding::label[2]</value>
      <webElementGuid>51eae9ad-2a15-4768-924c-ed482a401596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[4]/ul/li[3]/label</value>
      <webElementGuid>a8385edf-ccc2-4829-9bb2-403afa2f489d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Caesar Dressing' or . = 'Caesar Dressing')]</value>
      <webElementGuid>e4c7c182-45f2-41b4-9bf3-56252229a279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
