<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gardenSaladRequest_button</name>
   <tag></tag>
   <elementGuidId>c2cf889b-65e7-4889-8501-7be12cd80d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='GardenSalad']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GardenSalad > button.catering-select-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3298c5ca-65fc-4d9e-87f6-18df91d9f8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-select-button</value>
      <webElementGuid>8af3e0aa-6fe3-470a-9245-433b9a692ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Garden Salad</value>
      <webElementGuid>05b0bbda-4179-4148-812b-3652e2c5a6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>b3e14161-5576-420e-9488-88a10814df96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>acd0f4d1-c9f6-4fe8-9902-7066e0c3adaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>1a46adc2-4e99-47eb-a129-623b108f2d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request for Leg 1</value>
      <webElementGuid>bcfb6eba-ad83-4527-a013-eb15dda1e4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GardenSalad&quot;)/button[@class=&quot;catering-select-button&quot;]</value>
      <webElementGuid>d2d3fae2-3cca-4544-bba9-59c69b2d5825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='GardenSalad']/button</value>
      <webElementGuid>c26ea944-498f-4549-9af4-c9083e6fd1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[8]/following::button[1]</value>
      <webElementGuid>3c141fb2-a905-40b5-a332-d73d131155c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[15]/preceding::button[1]</value>
      <webElementGuid>df3743c5-01dc-4549-af52-f84b4a342227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranch Dressing'])[2]/preceding::button[1]</value>
      <webElementGuid>1a76dfe4-85a3-43bc-b82a-5acfefdbab58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/h4[4]/button</value>
      <webElementGuid>0e4b232b-38c5-46e4-a755-2a809fe135b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request for Leg 1' or . = 'Request for Leg 1')]</value>
      <webElementGuid>c26ae791-f839-48d0-94c9-7eeda676bc2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
