<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>savingGuestCancel_button</name>
   <tag></tag>
   <elementGuidId>0180b88c-306c-40ca-a261-220b244abfce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Cancel'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#propagatepassengermodal-leg-1-passenger-2 > div.modal-dialog > div.modal-content > div.modal-body > div.row > div.col-xs-4 > #Cancel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7609d81b-5143-4533-9fd6-c21f6b6d96cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>baj-btn-small</value>
      <webElementGuid>1e051e32-0311-46ec-aa25-9e19a072f740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bd0e9ac-1597-4c7a-8a09-8e9574293487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>cad3ce10-3812-4288-9b10-1ac9a392cccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>5f3a4673-b428-4e75-be54-a47af9b0682b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propagatepassengermodal-leg-1-passenger-2&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4&quot;]/input[@id=&quot;Cancel&quot;]</value>
      <webElementGuid>a06e8dc8-2f9e-4636-bac2-7121760e2d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Cancel'])[2]</value>
      <webElementGuid>bf30ac52-442c-47f0-97ac-6e90e5a497d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='propagatepassengermodal-leg-1-passenger-2']/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>bd2291b0-528c-47be-ac9e-5a9fc44a427f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[4]/div/div/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>1fb4d4bc-d78d-462e-8731-8999629a63e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'Cancel']</value>
      <webElementGuid>2e9df36a-41e2-431f-a9b7-df0dc1bea5b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
