<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lunch_tab</name>
   <tag></tag>
   <elementGuidId>4f2a2872-f549-466c-8f45-336a726eccd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CateringMenuAccordion']/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18ecb0a5-00e4-4f13-9651-237815046482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-heading accordion-toggle collapsed</value>
      <webElementGuid>db4cbafd-5c34-4984-8e55-6b183df70559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41e7aa1e-248d-45f8-9dd1-dc9850d836fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Lunch</value>
      <webElementGuid>522c53e9-9580-4cfa-8641-06c18dad6f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>868702e9-4b21-40c3-baec-161cfd4d219f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#CateringMenuAccordion</value>
      <webElementGuid>15326af0-5ded-41af-8f19-0f6d1fae606d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Lunch
                                        </value>
      <webElementGuid>76f44064-b63f-444b-8f21-0dfe53ade731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CateringMenuAccordion&quot;)/div[@class=&quot;panel panel-default&quot;]/a[@class=&quot;panel-heading accordion-toggle collapsed&quot;]</value>
      <webElementGuid>b2baf0f2-3beb-405d-a2a5-041337a37f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CateringMenuAccordion']/div[3]/a</value>
      <webElementGuid>ca3302ff-9511-43f7-8ee8-e0065416d680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[3]/following::a[1]</value>
      <webElementGuid>324f4c51-07bc-481f-a261-7723b66efc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinaigrette Dressing'])[2]/following::a[1]</value>
      <webElementGuid>65ad5428-f6e2-400c-abf0-8d32da1468eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Lunch')]</value>
      <webElementGuid>914c1173-2fce-4b2d-81ef-818cd0ca6326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/a</value>
      <webElementGuid>b236bcd5-937c-4e36-b241-d76ea0fd5cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Lunch' and (text() = '
                                            Lunch
                                        ' or . = '
                                            Lunch
                                        ')]</value>
      <webElementGuid>8d47ef10-6e28-4316-a6aa-6bcf2b869723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
