<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addPassenger_button</name>
   <tag></tag>
   <elementGuidId>79e35e0e-d89f-4d91-b057-ffb15b0c6986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PaxTab-0']/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.target-add-passenger-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c068f622-861e-4ba8-bb24-9253a7b6af65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-add-passenger-button</value>
      <webElementGuid>28757d5f-be89-449c-af2e-bd563cddc365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-total-passengers</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8f7d33bd-3864-4c0e-b05f-474ce1587921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recommended-passengers</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>fa9a40d3-f3e7-48e4-9493-f0b4eecd89a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909577</value>
      <webElementGuid>f2d29159-c02f-4f0c-8359-ae0369e6d366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legnumber</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6865ca00-a6a8-45b4-aa59-55b60d64776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-numberoflegs</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>abe7be38-47a8-4cfe-ba76-f9aa41595fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        ADD A PASSENGER
                                    </value>
      <webElementGuid>96eae9d8-7e8b-4522-aef7-78496c19d3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaxTab-0&quot;)/div[@class=&quot;ams-passenger-container center-text&quot;]/a[@class=&quot;target-add-passenger-button&quot;]</value>
      <webElementGuid>4213b56b-1a47-4009-a442-2ca333a29d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PaxTab-0']/div[4]/a</value>
      <webElementGuid>b9c9e4b6-5894-4ccb-a68d-859ff319239d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ADD A PASSENGER')]</value>
      <webElementGuid>97f38f15-d3f1-4f0d-ac3d-d3eb8e4c5bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save to My Passengers'])[3]/following::a[1]</value>
      <webElementGuid>33b24484-72fb-420d-883c-e1fef8be1e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Required'])[3]/following::a[1]</value>
      <webElementGuid>41c21013-17f2-4269-9ba9-61ef787e3459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luggage'])[1]/preceding::a[1]</value>
      <webElementGuid>09d4051a-8226-4865-8811-47983082846c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check for None'])[1]/preceding::a[1]</value>
      <webElementGuid>ab6b9728-5e89-4cd5-807f-ca56856380d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ADD A PASSENGER']/parent::*</value>
      <webElementGuid>2f0c2a98-d537-4f0e-82f4-b441a8e929a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>2c29ef2c-5304-46f1-ae8b-ccf7931eaa55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                                        ADD A PASSENGER
                                    ' or . = '
                                        ADD A PASSENGER
                                    ')]</value>
      <webElementGuid>f4e4ac91-cf44-460f-8a23-495a65df2565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
