<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PickupAddress1_textBox</name>
   <tag></tag>
   <elementGuidId>226a9454-f14e-4a3e-8067-9d27a828139f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Address_Street1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Address_Street1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a2fdfa6-5317-418d-b1ef-85858e646090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da3148e3-2516-4322-ab95-ea84190847cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control auto-complete-street-address ui-autocomplete-input</value>
      <webElementGuid>ef1842fa-fdac-4487-8cba-3078a770f661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3accf949-5222-4c30-a013-85c59c44bb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Address must be a string or array type with a maximum length of '50'.</value>
      <webElementGuid>664371ae-4eeb-4056-a8e7-3842a1d6b9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>dc01a407-08ba-4a01-90f4-64f9059d3764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Address_Street1</value>
      <webElementGuid>2846c996-3de2-4284-9347-e9efae4157a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3a864a1e-e4f6-4ddc-9bb8-51882ba242fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Address.Street1</value>
      <webElementGuid>425acbcf-42da-411b-a7f4-fbeb6177afb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>79d023ff-13ca-4715-978f-373d38334dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909635&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-5&quot;]/div[@class=&quot;row auto-complete-address&quot;]/div[@class=&quot;col-xs-12&quot;]/input[@id=&quot;Address_Street1&quot;]</value>
      <webElementGuid>f096c031-3bee-4617-9cb2-52471fda7a9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Address_Street1']</value>
      <webElementGuid>46c54ff9-2905-4f80-9e31-88b82fbfbbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickup-quote-0']/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>37788410-6629-4855-a433-487de387e3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>867a1d8b-f88a-4c93-b537-479abd9a6648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Address_Street1' and @name = 'Address.Street1']</value>
      <webElementGuid>437fb0c2-4fee-4362-a590-aad42c8830a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
