<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sUV_textBox</name>
   <tag></tag>
   <elementGuidId>1c4a6eb5-85ac-4fed-be39-d8ea4fa772a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ConciergeQuoteXExecutiveVehicles_0__Quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ConciergeQuoteXExecutiveVehicles_0__Quantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b5cc362-6f45-4da7-9fdd-690425d680ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ed5b14c9-b9e8-44cb-b56f-54e24145ddcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-vehicle-quantities</value>
      <webElementGuid>01b0608b-bdb7-4812-87aa-0fea486c88a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0ef40d16-94e2-4a87-a88f-918b2c4aed94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02e81f1d-96c3-477d-9a4f-344c4bdb121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9cb6d97f-9085-41c5-9f91-be4c0fa193ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vehicletype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d9290b76-e1cc-4282-ac96-6dd9d03bb377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48</value>
      <webElementGuid>e8fb431f-157a-4830-8577-7270fc314bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42c3dbd0-d59f-4b0e-8524-023ce2f025bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Quantity field is required.</value>
      <webElementGuid>d421f75e-7b94-4bf0-a0dd-c7cf74bc093c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConciergeQuoteXExecutiveVehicles_0__Quantity</value>
      <webElementGuid>63595f23-094f-48f6-be24-62543339eceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConciergeQuoteXExecutiveVehicles[0].Quantity</value>
      <webElementGuid>7fcf427d-e0d5-40ce-8cd7-0eb19edb7fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f351748-3a87-4e39-821a-896461eff87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-new-quote-type-2-leg-909635&quot;)/div[@id=&quot;new-executive-quote-noorder&quot;]/div[@id=&quot;pickup-quote-0&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-7&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 flex-start&quot;]/input[@id=&quot;ConciergeQuoteXExecutiveVehicles_0__Quantity&quot;]</value>
      <webElementGuid>83c81724-aad0-4db4-b144-4a25521c331b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ConciergeQuoteXExecutiveVehicles_0__Quantity']</value>
      <webElementGuid>753d24e6-0e26-46f7-ade4-2b925eba3627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pickup-quote-0']/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>f66f3796-a250-47a9-8458-c7c5f2026f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div[4]/input</value>
      <webElementGuid>eaa61f50-4a36-4017-bf5c-421f52256594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ConciergeQuoteXExecutiveVehicles_0__Quantity' and @name = 'ConciergeQuoteXExecutiveVehicles[0].Quantity']</value>
      <webElementGuid>3be74e8a-15b0-42e1-91b4-8e077e2be2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
