<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name_textBox</name>
   <tag></tag>
   <elementGuidId>5ab01183-c84c-4192-8d7a-5eba70f8eee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OperatorFilterViewModel_FilterName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OperatorFilterViewModel_FilterName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6137ca83-65cf-415a-a2c5-c3a77895689e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control target-clearable-field</value>
      <webElementGuid>9da01c3d-ee0f-4f32-93d2-335fec8ba9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OperatorFilterViewModel_FilterName</value>
      <webElementGuid>2a1afadb-6b0d-4e9f-b762-52a87817204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OperatorFilterViewModel.FilterName</value>
      <webElementGuid>bb2ff90f-dbc0-4455-ab22-dd7809cb86e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b581ce4b-4d43-4466-9296-4f22008f1dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OperatorFilterViewModel_FilterName&quot;)</value>
      <webElementGuid>01822fc4-8227-4cad-9d00-67c8b4292492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OperatorFilterViewModel_FilterName']</value>
      <webElementGuid>53fec00a-ba58-44ea-beaa-628392d439ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ams-operator-form']/row/div/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>493ebffc-643e-4c04-8c64-15848a32cf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>331165bf-9ad7-4263-b580-63e2fc51afb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OperatorFilterViewModel_FilterName' and @name = 'OperatorFilterViewModel.FilterName' and @type = 'text']</value>
      <webElementGuid>b19715e3-cb96-44b8-b6a3-1ac524ebe691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
