<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coffee_checkBox</name>
   <tag></tag>
   <elementGuidId>a5b855a7-7b89-4725-97bf-e45c0d78da6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CoffeeandTea-options']/li[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>edace41b-7e50-49ab-8f54-a821c42df8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CoffeeandTeaCoffee</value>
      <webElementGuid>891cda15-4c52-4170-965b-16fcc86f7c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coffee</value>
      <webElementGuid>9571763e-6c40-477b-87ab-8d598c6c35a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoffeeandTea-options&quot;)/li[2]/label[1]</value>
      <webElementGuid>7de21f78-86b8-4b47-9625-c2e86abc80a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoffeeandTea-options']/li[2]/label</value>
      <webElementGuid>a8300086-77a6-4685-b5d5-a7e0044e2263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[18]/following::label[1]</value>
      <webElementGuid>53f1f4a1-86af-46cf-81ef-31c7fa4771b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for Leg 1'])[19]/following::label[1]</value>
      <webElementGuid>58788d11-0d72-4997-93bf-89d5540b5d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tea'])[1]/preceding::label[1]</value>
      <webElementGuid>8d0ea708-7772-41c6-a6ab-ef9cf0f92138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[6]/preceding::label[2]</value>
      <webElementGuid>db380522-bd66-4dc8-b2ef-96cfe0c955db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Coffee']/parent::*</value>
      <webElementGuid>3e5dffd8-95cf-4d14-886d-c6991fd5fcfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4/ul/li[2]/label</value>
      <webElementGuid>e1840f72-ea4b-4859-adb6-63d663cd5ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Coffee' or . = 'Coffee')]</value>
      <webElementGuid>02d31d42-39ca-403e-ac74-48a8ab41f7f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
