<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tea_checkBox</name>
   <tag></tag>
   <elementGuidId>340065f5-38e0-4153-8bcb-42979a267f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='CoffeeandTea-options']/li[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b9f0e2d-a50b-4197-9f84-83c4f8904688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>CoffeeandTeaTea</value>
      <webElementGuid>e134675d-0efc-4ae0-8f63-fe8c037e4f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tea</value>
      <webElementGuid>51f5d5a2-40f1-4da3-8a09-da93e4f05803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoffeeandTea-options&quot;)/li[3]/label[1]</value>
      <webElementGuid>359c5cea-43d6-4d0d-8c91-2874d7feede2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='CoffeeandTea-options']/li[3]/label</value>
      <webElementGuid>fbcea535-d49f-48b0-85e0-d0410566b7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coffee'])[1]/following::label[1]</value>
      <webElementGuid>86bd8646-c29a-4780-982a-739af52df40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[18]/following::label[2]</value>
      <webElementGuid>7e57bbf0-511e-4153-be15-73462dd484c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[6]/preceding::label[1]</value>
      <webElementGuid>ea6ac03e-22e7-4bb6-97d5-06c4afaefb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tea']/parent::*</value>
      <webElementGuid>5d066881-d731-4e14-a666-c381fa1d5d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4/ul/li[3]/label</value>
      <webElementGuid>5d97b60f-cc9c-4787-a980-12cc75e8b276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Tea' or . = 'Tea')]</value>
      <webElementGuid>58579e71-7cb4-4b63-827b-b5dcffdf8104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
