<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightCostNonPersistent_value</name>
   <tag></tag>
   <elementGuidId>60270a09-d37d-4e04-b5ee-24eaa2d3e19a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ONEflightDownDropDivContents']/table/tbody/tr[4]/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7194731d-0d69-4d35-ba9d-5d2c65776449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-txt dd-align-r</value>
      <webElementGuid>eb02d8e4-4a83-420c-a8cb-7cbfb02b46b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$130.50</value>
      <webElementGuid>9eea2156-d336-4215-a1a4-6dc151869475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONEflightDownDropDivContents&quot;)/table[1]/tbody[1]/tr[4]/td[@class=&quot;dd-txt dd-align-r&quot;]</value>
      <webElementGuid>8a6dfe0a-643a-49e1-83f9-3eb1dd73f599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ONEflightDownDropDivContents']/table/tbody/tr[4]/td[6]</value>
      <webElementGuid>bb2fa512-dd59-43ee-bdf3-599dc59f9d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='='])[4]/following::td[1]</value>
      <webElementGuid>de6c86eb-8dec-4c8c-8bf0-b92956c28b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$130.50'])[1]/following::td[2]</value>
      <webElementGuid>db406fd3-a7ad-4c64-9363-613cb7d2bf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/preceding::td[1]</value>
      <webElementGuid>bd23ae8a-7d19-4dcb-b7ea-0dba6454ad87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$78,239.10'])[2]/preceding::td[2]</value>
      <webElementGuid>484b40bf-ba7e-41ff-8831-a360eaee3a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]</value>
      <webElementGuid>15235089-a202-46d0-a150-fd1bb1f41ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$130.50' or . = '$130.50')]</value>
      <webElementGuid>84c18e97-01ff-4d28-a799-69097cee10e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
