<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flightCostClose_button</name>
   <tag></tag>
   <elementGuidId>f05433b7-76a8-47a9-82d7-472c314f56f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ONEflightDownDropDiv']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.glyphicon.glyphicon-triangle-top.bad.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>675048a7-ae41-4b25-bdce-963817813476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-triangle-top bad pull-right</value>
      <webElementGuid>39130e36-c8db-42d7-8dec-014a6da2fd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONEflightDownDropDiv&quot;)/div[@class=&quot;glyphicon glyphicon-triangle-top bad pull-right&quot;]</value>
      <webElementGuid>9cd3a5ac-a41c-4aa8-9490-ee3c9a2d0e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ONEflightDownDropDiv']/div</value>
      <webElementGuid>3cbbcafb-4900-40c5-a198-51f5a8adfb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div</value>
      <webElementGuid>58e77941-f790-4c19-857b-5e7569adfc3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
