<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>milk_button</name>
   <tag></tag>
   <elementGuidId>5eadef49-52af-4c51-aadf-748c5ac501ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='Milk']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Milk > button.catering-select-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d55943e8-f2f7-4aa4-bda1-4fd3d6c78e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>catering-select-button</value>
      <webElementGuid>fc9f868c-496d-4a5a-bca9-2b7669d19e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Milk</value>
      <webElementGuid>0e5997e7-589a-49c4-aad6-b58009afb2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-legid</name>
      <type>Main</type>
      <value>909215</value>
      <webElementGuid>9afbd0f2-bf7d-4c07-8f12-b78fcf4546b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itemid</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a08df608-374a-4911-a9e8-5d8d10e4d477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-options</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>f06e6b63-855c-4084-aa9c-111344a79f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request for Leg 1</value>
      <webElementGuid>fb545317-4907-4b06-899d-0894befed3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Milk&quot;)/button[@class=&quot;catering-select-button&quot;]</value>
      <webElementGuid>ae325875-22e9-4b2e-88b1-561bbce8a7c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h4[@id='Milk']/button</value>
      <webElementGuid>7247128c-ab25-4275-b200-91e76283f8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[6]/following::button[1]</value>
      <webElementGuid>507dfff5-2189-494f-84e6-05f90aeac345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[19]/preceding::button[1]</value>
      <webElementGuid>9bafe3e0-7dc9-46aa-9f43-37813316de62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whole Milk'])[1]/preceding::button[1]</value>
      <webElementGuid>cedc85fd-69d1-4f3f-b835-7d1edbbc0559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4[2]/button</value>
      <webElementGuid>b80a1838-96ee-4403-bbd4-1dbb84628459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Request for Leg 1' or . = 'Request for Leg 1')]</value>
      <webElementGuid>e03f2cc3-d50b-4156-bb6b-28ea02d95397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
