<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pestoSauce_checkBox</name>
   <tag></tag>
   <elementGuidId>0335383b-363c-43d7-9b36-17f93fc7b58e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Pasta-options']/li[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0a7e963d-a5c4-400a-9c1a-b1ba46235c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>PastaPesto Sauce</value>
      <webElementGuid>4d47d07d-0474-4813-9062-4965dfce7478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesto Sauce</value>
      <webElementGuid>d2e723d2-ddf1-4aec-b983-c83b90291f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Pasta-options&quot;)/li[5]/label[1]</value>
      <webElementGuid>dbc87105-782a-4d8a-92ab-73d932bcf9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Pasta-options']/li[5]/label</value>
      <webElementGuid>5d729f61-48e9-4385-ad3e-b32deedf3845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alfredo Sauce'])[1]/following::label[1]</value>
      <webElementGuid>9d22f8c4-1b50-4b67-94cf-388bcb9236d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marinara Sauce'])[1]/following::label[2]</value>
      <webElementGuid>1efeb98b-da74-4313-99cc-3ac7d061dfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[5]/preceding::label[1]</value>
      <webElementGuid>8f7bbbdb-8b04-4130-9b95-d5596e50caec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platters'])[1]/preceding::label[1]</value>
      <webElementGuid>2d126488-d583-481a-b33e-121a9facac91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pesto Sauce']/parent::*</value>
      <webElementGuid>3f0f6770-348a-443d-a8df-0abe0b5ca4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/h4[4]/ul/li[5]/label</value>
      <webElementGuid>3c1a8c84-6529-4cfa-81fc-8c4f15671f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pesto Sauce' or . = 'Pesto Sauce')]</value>
      <webElementGuid>129ccd5b-1cc8-4eaf-967d-3b123f7651ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
