<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_button</name>
   <tag></tag>
   <elementGuidId>458e8293-9c19-466e-a907-eef86be3d560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.target-operator-add-note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Add'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b856e2a7-b9de-42cb-9e75-e5e700d9fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>92981a08-b541-4276-a626-a39f98a6efab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>42807027-72c7-4fd4-9730-4226d9ed432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary target-operator-add-note</value>
      <webElementGuid>4fb249f9-d54b-46cb-a988-328e5b34a529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Notes&quot;)/div[1]/input[@class=&quot;btn btn-primary target-operator-add-note&quot;]</value>
      <webElementGuid>5ee89589-db1a-4960-aa7d-f9b60dbe1390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Add'])[2]</value>
      <webElementGuid>88db69f0-ef90-421f-b76c-ec0f517e360a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Notes']/div/input</value>
      <webElementGuid>f812d885-d2f0-470c-aecf-4b80a5eda495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//row/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>ecf3784f-9e72-41a6-9bd1-17b5497710da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>febd6b88-8805-4cd4-aa85-7f70b0e75ffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
