<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accounts_tab</name>
   <tag></tag>
   <elementGuidId>5382b43b-0c29-4d8c-a866-e9fe31524c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div/div/div[2]/div[2]/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.target-tab.target-link-to-accounts-tab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fa10931-2dab-48a7-8fab-95de4e99f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-tab target-link-to-accounts-tab</value>
      <webElementGuid>5024b69b-f8b5-40c3-8591-8ac217fc0c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-client-id</name>
      <type>Main</type>
      <value>67819</value>
      <webElementGuid>f2f7ed2e-8d90-4e42-8bc0-3ad85413001f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab-id</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4c6d8473-b264-4262-9342-d486ae10dcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3bbcff45-47ac-426d-99b3-9209752fa83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#Accounts</value>
      <webElementGuid>4c7366bd-a3c9-47ba-8133-77f92aa585ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accounts</value>
      <webElementGuid>fb188feb-c93c-47cf-99e9-abfa91e9070e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;top_wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;container prospect-form-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-10&quot;]/div[@class=&quot;row&quot;]/ul[@class=&quot;nav nav-tabs target-tab-container&quot;]/li[9]/a[@class=&quot;target-tab target-link-to-accounts-tab&quot;]</value>
      <webElementGuid>7e29dd73-bdc9-4506-bd5c-1e2cf11744fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div/div/div[2]/div[2]/ul/li[9]/a</value>
      <webElementGuid>e5accab0-a8ba-4a2f-82e5-be2e90e3c681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accounts')]</value>
      <webElementGuid>b6424a4b-a69d-4ffa-bfaf-5ef0cf64cc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract'])[1]/following::a[1]</value>
      <webElementGuid>6ffa0d0e-0224-4477-9dc0-e7a14260d13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::a[2]</value>
      <webElementGuid>39bad803-5000-42b9-9d23-7d1ac80759b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/preceding::a[1]</value>
      <webElementGuid>bb55fe67-c751-43b3-9ccf-d3cf04b18a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source:'])[1]/preceding::a[2]</value>
      <webElementGuid>13be222b-f1d4-4db0-a5be-7cad9198dfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accounts']/parent::*</value>
      <webElementGuid>a7b8c6f9-19ec-4937-9e9b-af56650c1bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#Accounts')]</value>
      <webElementGuid>19b53c9a-70cc-43f7-9624-3f557074907e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/ul/li[9]/a</value>
      <webElementGuid>4192fc58-a568-4ed7-9fa7-087213a74857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#Accounts' and (text() = 'Accounts' or . = 'Accounts')]</value>
      <webElementGuid>0113e539-70af-4f7c-bde1-55aa8c113e41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
