<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>balanceCheck_checkBox</name>
   <tag></tag>
   <elementGuidId>1c56b761-8809-43e8-beba-fd7b1d431469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='3']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b5e102d-fe62-4124-b726-450a6dce4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e4cddc50-e13c-48f9-a3f9-0f7a14770a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a9b2e718-3a71-465c-8b1f-5e7ce63087a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfo&quot;)/div[@class=&quot;row target-account-detail&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group col-xs-12 row_margin_bottom&quot;]/div[@class=&quot;target-client-account-overrides-div&quot;]/div[1]/div[@class=&quot;row col-xs-12 target-add-flight-plan-override-div&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 account-override-multi-selectlist&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[@class=&quot;active&quot;]/a[1]/label[@class=&quot;checkbox&quot;]/input[1]</value>
      <webElementGuid>c0ea2258-1cac-488c-9822-bd273f3004a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='3']</value>
      <webElementGuid>6fdac0ec-e900-4cda-abeb-31b6de6095b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div[5]/div/div/div[2]/div/div[3]/div[2]/div/span/div/ul/li[4]/a/label/input</value>
      <webElementGuid>b177285e-9773-4c8b-bba2-6ba784d5d9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/label/input</value>
      <webElementGuid>1ec568ad-dea3-4227-8f0c-7db8ace92545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>960aa0b5-4792-4e2d-a8cd-384a1f62f0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
