<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hoursCheck_checkBox</name>
   <tag></tag>
   <elementGuidId>6c3116ea-89fb-465f-8bd2-508c458571ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='4']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d78464e-e627-4fb7-b112-d38c7fe55585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>09183936-733f-4eac-9dbd-6be0ff671d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8b3192bd-f40e-4a44-8939-862eab4ca456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfo&quot;)/div[@class=&quot;row target-account-detail&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group col-xs-12 row_margin_bottom&quot;]/div[@class=&quot;target-client-account-overrides-div&quot;]/div[1]/div[@class=&quot;row col-xs-12 target-add-flight-plan-override-div&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 account-override-multi-selectlist&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[@class=&quot;active&quot;]/a[1]/label[@class=&quot;checkbox&quot;]/input[1]</value>
      <webElementGuid>c181cc1a-26c2-4111-958e-504fadc25d4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='4']</value>
      <webElementGuid>777a29fb-49ff-4e36-9057-17079354a8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div[5]/div/div/div[2]/div/div[3]/div[2]/div/span/div/ul/li[5]/a/label/input</value>
      <webElementGuid>4f11c888-6e5e-4277-bb21-261b04aebd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/label/input</value>
      <webElementGuid>2fac0e99-4b79-4a7d-8800-f15c76434f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>89b555b5-5c9c-46f2-b997-a27b09eb9f82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
