<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submit_button</name>
   <tag></tag>
   <elementGuidId>0cdbe1da-5bd3-4c5a-a09b-9f50f46c7dba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.target-add-account-x-override.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3728352-d1ad-4543-89fb-855c5d61a719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>deee7f84-1251-4468-9995-47fc01e4135a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>527fe88b-bf6e-41bf-b3cb-38bd75fd51fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-add-account-x-override button</value>
      <webElementGuid>2de539b3-2772-43d8-a00d-149dc9d99a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountInfo&quot;)/div[@class=&quot;row target-account-detail&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-group col-xs-12 row_margin_bottom&quot;]/div[@class=&quot;target-client-account-overrides-div&quot;]/div[1]/div[@class=&quot;row col-xs-12 target-add-flight-plan-override-div&quot;]/div[@class=&quot;row&quot;]/input[@class=&quot;target-add-account-x-override button&quot;]</value>
      <webElementGuid>9cc292c1-62a8-417f-acf4-73379f4e71aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Submit']</value>
      <webElementGuid>f1f97fa7-a3d7-4657-a08f-698e31ee757e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountInfo']/div/div[5]/div/div/div[2]/div/div[3]/div[2]/input</value>
      <webElementGuid>8718f44f-c311-48f5-86e8-b303fb4f85b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>ac32d879-8802-4847-b5fd-edc5a1db0ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>df6c2647-7503-40b7-9dcd-176643aed1ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
