<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chocolateMilk_checkBox</name>
   <tag></tag>
   <elementGuidId>99d083fa-3669-4c66-86b4-577207e9a8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Milk-options']/li[7]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e139376a-f50f-48a7-a989-51ad43ee2e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>MilkChocolate Milk</value>
      <webElementGuid>908b1439-91c8-4fa5-8eb6-18dfa4002d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chocolate Milk</value>
      <webElementGuid>939f527f-4eef-41c3-bf6f-762604f4e2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Milk-options&quot;)/li[7]/label[1]</value>
      <webElementGuid>f60cb073-0e7d-4dfa-8677-e246a255bfa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Milk-options']/li[7]/label</value>
      <webElementGuid>995812e0-0662-4a40-b876-207827e16730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soy Milk'])[1]/following::label[1]</value>
      <webElementGuid>e41169cd-d2dd-4c9c-8708-6a2580735842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organic Milk'])[1]/following::label[2]</value>
      <webElementGuid>f0e558e8-b8fb-4c5b-9d18-3b604ef5b2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[7]/preceding::label[1]</value>
      <webElementGuid>6381ef23-ce38-44b1-b52d-d85aaccd89a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chocolate Milk']/parent::*</value>
      <webElementGuid>de9d4b78-f39c-4337-88c4-e77a3fe535f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4[2]/ul/li[7]/label</value>
      <webElementGuid>f933738e-2610-4aa8-a29c-71cb063dadb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Chocolate Milk' or . = 'Chocolate Milk')]</value>
      <webElementGuid>70841b2f-939e-4685-b92b-6059cfdf6754</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
