<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>organicMilk_checkBox</name>
   <tag></tag>
   <elementGuidId>ec3fe72e-0701-487a-ba22-258bb99b4d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Milk-options']/li[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>49e9e731-aa95-4180-b690-77f3d012f309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>MilkOrganic Milk</value>
      <webElementGuid>300af587-505b-4dde-8098-8d5d53e67bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Organic Milk</value>
      <webElementGuid>22bf36c0-1b2d-467c-859e-c1c6e98c8ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Milk-options&quot;)/li[5]/label[1]</value>
      <webElementGuid>0b12b3e4-bfaa-4381-a556-3ff27a038e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Milk-options']/li[5]/label</value>
      <webElementGuid>bd3b0885-26ee-4925-beb1-2bf150159254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skim Milk'])[1]/following::label[1]</value>
      <webElementGuid>ad7f1a27-5caf-4a2d-8837-3f8c26766eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whole Milk'])[1]/following::label[3]</value>
      <webElementGuid>4263c58f-9f92-485f-a15a-4ca35912108b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soy Milk'])[1]/preceding::label[1]</value>
      <webElementGuid>44d9b45f-9505-4648-9596-b7607c98c936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate Milk'])[1]/preceding::label[2]</value>
      <webElementGuid>ba660dd2-2491-450d-b2b8-bf92146f0221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Organic Milk']/parent::*</value>
      <webElementGuid>a1197ef8-b414-4611-8db6-fa9d636fdf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4[2]/ul/li[5]/label</value>
      <webElementGuid>bbfd337c-a577-43f5-a4bd-0f391224d840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Organic Milk' or . = 'Organic Milk')]</value>
      <webElementGuid>6cfe6ccc-49c3-43fc-addd-63cfbe884691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
