<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skimMilk_checkBox</name>
   <tag></tag>
   <elementGuidId>3b2e3b85-b5d5-4786-b27e-d9216c0a2305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='Milk-options']/li[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>35ee7c52-5401-4b13-8c2f-109258049bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>MilkSkim Milk</value>
      <webElementGuid>492aecc9-c838-42d6-825b-1ec40f1039b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skim Milk</value>
      <webElementGuid>550614c5-26b5-43b6-a1a4-bb92cf9cb95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Milk-options&quot;)/li[4]/label[1]</value>
      <webElementGuid>d5bd8dd4-cad5-4724-9815-2b5791d77125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='Milk-options']/li[4]/label</value>
      <webElementGuid>455f2787-9844-4e21-94d0-d05f1ae5641a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whole Milk'])[1]/following::label[2]</value>
      <webElementGuid>e5bd7a80-bfbc-4892-97c5-0ac8110c92eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Select'])[19]/following::label[3]</value>
      <webElementGuid>33975843-b152-459a-b072-0d9791d615ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organic Milk'])[1]/preceding::label[1]</value>
      <webElementGuid>adb981e2-dba8-49ca-9f86-864b61960957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soy Milk'])[1]/preceding::label[2]</value>
      <webElementGuid>d57ef800-edd1-4caa-a5d2-2455389d35a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skim Milk']/parent::*</value>
      <webElementGuid>a771bf81-0dde-486b-9461-3409d0443db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/h4[2]/ul/li[4]/label</value>
      <webElementGuid>2aed151a-1100-49b8-809b-d0b70d4eea83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Skim Milk' or . = 'Skim Milk')]</value>
      <webElementGuid>ae1840ef-d5f1-471d-b54f-29e5ebd87626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
