<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>signIn_button</name>
   <tag></tag>
   <elementGuidId>ea46abeb-a52b-4b6e-808a-be4edfc39bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SelectAircraftLoginButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectAircraftLoginButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df35757d-4aa6-431a-8d92-299c742b269a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary guest-submit</value>
      <webElementGuid>527c2342-1c9b-4ab6-aea0-3c28b1781666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e2303f9-7160-44c6-a228-94da3f9afff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectAircraftLoginButton</value>
      <webElementGuid>8ed12b04-5c56-4f31-ba55-9c6655db774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>BAJ.login(this)</value>
      <webElementGuid>1c8a9844-4f34-485a-aab3-1ca9e39786b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>e5978fc9-ccb9-4259-b71d-145c186eec1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectAircraftLoginButton&quot;)</value>
      <webElementGuid>02919528-9e21-4a6d-9dea-2ce16753c2e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SelectAircraftLoginButton']</value>
      <webElementGuid>c52eb8b4-04d0-46bc-95ff-b2418d72e163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='SignInForm']/div/div/div/div/div[5]/input</value>
      <webElementGuid>7c07ee17-ba14-4cf3-8b14-7fcbfcdd3116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>2b786214-e1c4-480a-90a2-940d7068d607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'SelectAircraftLoginButton']</value>
      <webElementGuid>fa5a4c49-288a-4a9f-b5da-00bc466ed402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
