<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leg1_checkBox</name>
   <tag></tag>
   <elementGuidId>258391ca-ae6a-4d9a-bb55-1b4d96f18040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[14]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.target-operator-quote-group-select.cursor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c200b2a7-3759-42f2-b57b-53b925219717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>target-operator-quote-group-select cursor</value>
      <webElementGuid>a63eab97-bb76-4a5e-9046-f60a1174f866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-leg-id</name>
      <type>Main</type>
      <value>910183</value>
      <webElementGuid>c8762538-39ec-4dac-b804-fbda4eff0e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-operator-quote-id</name>
      <type>Main</type>
      <value>137604</value>
      <webElementGuid>fa043175-35fa-45a5-8b02-91a626bbf340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c48328d-f3ae-4d3b-b733-194b4c172275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-op-quote-form&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-xs-12 target-leg-operator-quotes-group&quot;]/div[@class=&quot;target-leg-quotes-div&quot;]/input[@class=&quot;target-operator-quote-group-select cursor&quot;]</value>
      <webElementGuid>16ed352d-0af4-4be4-93ef-a2626d19eeb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[14]</value>
      <webElementGuid>6f07bc73-20b8-47e1-a34d-96d20e1ea54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-op-quote-form']/div/div/div/div/div[2]/input</value>
      <webElementGuid>8ad87a5f-3fd5-4aad-8cd6-d69e06ca9b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]/input</value>
      <webElementGuid>25018f3c-f7dd-4207-8ee5-0490ff76e942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b5168ee2-b7d0-453d-a1c2-e8cbd7f564fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
