<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noDecline_button</name>
   <tag></tag>
   <elementGuidId>3df8cfb2-9337-466d-b395-c33fb028aa9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='No']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.reject-button.itinerary-button.target-modal-cancel-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f12de9ae-be2d-4040-9508-a9c0ec890567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9edc1262-0cea-4046-b1ab-6e9a54e26b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn reject-button itinerary-button target-modal-cancel-button</value>
      <webElementGuid>4f57a51f-8817-441a-83c1-02bf5e10d725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>6759c9b4-1251-47e0-a780-760f0bd38c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;target-accept-changes&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 float-right&quot;]/input[@class=&quot;btn reject-button itinerary-button target-modal-cancel-button&quot;]</value>
      <webElementGuid>efc4ed79-e857-46f6-aa76-782eb5efb131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='No']</value>
      <webElementGuid>ee2761d5-c38e-4cc4-8c1e-8e94c24941d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='target-accept-changes']/div/div[3]/input</value>
      <webElementGuid>d92745e4-2f02-4599-9345-24b13e850afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/input</value>
      <webElementGuid>901c821e-639e-4bd5-8271-99757db9dfe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>8fe10b4d-5cad-49df-9789-4bc6f0e11a7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
